HathorNetwork/hathor-core

- hathor/merged_mining/coordinator.py
This fixes an issue with NiceHash not being able to validate the minimum difficulty.
> fix(mergedmining): set initial diff only after subscribe AND authorize

- hathor/cli/grafana_dashboard.py
- hathor/cli/util.py
- hathor/conf/testnet.py
- hathor/util.py
We cannot top-level import from `hathor.util` in command files  because `hathor.util` loads `HathorSettings`.
Closes #108
> fix(cli): Don't load HathorSettings before entering command main method

- hathor/merged_mining/bitcoin.py
- hathor/merged_mining/bitcoin_rpc.py
- hathor/merged_mining/coordinator.py
- tests/tx/test_merged_mining.py
This PR preserves the transaction data given by Bitcoin's
getblocktemplate as much as possible. The only transaction we build from
scracth now is the coinbase.
Transactions are temporarily removed (along with the fees) and other
errors on bitcoin.submitblock were also fixed, like bad-cb-height and unexpected-witness
Additionally a proposed merged block is now validated against
bitcoin.getblocktemplate which only affects logging, but should give a
preview of whether bitcoin.submitblock will fail.
> fix(mergedmining): bad-txnmrklroot and other errors on bitcoin.submitblock

- hathor/conf/settings.py
- hathor/manager.py
In my notebook:
`dev`: between 19 - 24 tx/s
`feat/skip-block-weight-validation`: between 80 - 120 tx/s
> feat: skipping block difficulty validation while initializing the node

- hathor/manager.py
- hathor/util.py
- tests/resources/transaction/test_mining.py
This regression was caught because of an error on the tx-mining-service after yesterdays v0.37.3 deploy.
> fix(api): regression when calling get_block_template without address

- poetry.lock
- pyproject.toml
- tests/p2p/test_split_brain.py
That test is known to randomly fail. We will always re-run it manually when that happens. This PR adds the [flaky](https://github.com/box/flaky) plugin that will do just that automatically for tests marked as flaky (`@pytest.mark.flaky` like this one is now) with the following strategy: out of 2 runs it has to pass one.
This is what it looks like when it passes the first time:
```
===Flaky Test Report===
test_split_brain passed 1 out of the required 1 times. Success!
===End Flaky Test Report===
```
And this is what it looks like when it fails once and has to run again (which took several tries):
```
===Flaky Test Report===
test_split_brain failed (1 runs remaining out of 2).
<class 'twisted.trial.unittest.FailTest'>
Items in the first set but not the second:
Interval(3177661205, inf, …
```
> fix(tests): retry tests/p2p/test_split_brain once if it fails

- hathor/transaction/resources/validate_address.py
- tests/resources/base_resource.py
- tests/resources/transaction/test_validate_address.py
This is a regression that passes the tests but not on actual usage. I'm figuring out how to test this, it can potentially affect other endpoints that rely on a request parameter to be passed as `str`, but so far this is the only known case (maybe because it's the only usage of `getChild`).
> fix(api): validate_address returns 500 on valid address

- hathor/manager.py
- hathor/p2p/manager.py
This PR was created to fix an issue, but it's actually a feature.
To fix the problem of rejecting every peer before getting the whitelist I added the feature of re-running the discovery process periodically if there are no connected peers.
> fix(p2p): re-run discovery when no peers are connected

- .github/workflows/main.yml
I thought about just disabling the caches or just hijacking the cache key to force it to be rebuilt (since there isn't a way to force cache invalidation for Github Actions), but after reviewing all builds, not using this cache will add about 3min to build time, which is not much (it usually takes about 30min for the whole matrix to finish).
Given that we don't really know what caused the cache to become a problem, and thus we don't know how to incorporate that into the key to make it "imcompatible" (for instance we already incorporate the OS and Python version, so one cache can't be used on a different os or Python version), we don't know when something like this will happen again. And given that we can't "quickly" solve this by force-invalidating a cache (I think it takes 7 days of no …
> chore(ci): remove poetry cache, which was causing tests to crash

- .github/workflows/docker.yml
- Dockerfile
- Dockerfile.github
- Dockerfile.github-pypy
> Recent updates on the cryptography package introduced the need for rustc
> for compiling it from source. Although the required runtime version of
> cryptography is locked in `poetry.lock`, when installing Poetry (from
> outside the controlled virtualenv) it gets pulled by some dependency and
> the latest version is installed. The bare `Dockerfile` has been updated
> to support these changes (install Rust and update alpine).
> 
> The last update to the workflow script that builds and pushes the image
> stopped adding the `latest` tag. I ported the script to Python because
> it's better to maintain than the Bash script we had. This update also
> includes some small adjustments to support easier testing of this build
> script and use the Python version on the `Dockerfile`s as the default
> …
> chore(docker): fix build, broke due to recent updates

- .github/workflows/docker.yml
After the last docker build fix I noticed scheduled builds broke on my fork. I realized we removed the poetry log cache for the tests but not for the docker build, and this was causing the failures.
Scheduled build history:
- hadn't failed yet but problem was there: https://github.com/jansegre/hathor-core/actions/runs/594827023
- failed: https://github.com/jansegre/hathor-core/actions/runs/598270493
- ...
- last one that failed: https://github.com/jansegre/hathor-core/actions/runs/606957181
- fix pushed: https://github.com/jansegre/hathor-core/actions/runs/608344826
- first scheduled build, no problem: https://github.com/jansegre/hathor-core/actions/runs/609282150
> chore(docker): disable poetry cache on docker build

- hathor/metrics.py
I recently got a traceback like this:
```
File ".../python3.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
self._runCallbacks()
File ".../python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File ".../python3.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
callable(*args, **kwargs)
File ".../python3.7/site-packages/twisted/internet/base.py", line 706, in disconnectAll
failure.Failure(main.CONNECTION_LOST))
--- <exception caught here> ---
File ".../python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
return callWithContext({"system": lp}, func, *args, **kw)
File …
```
> fix(metrics): protocol_state=None case not accounted for

- hathor/cli/main.py
- hathor/cli/util.py
This is what a regular log looks like:
```
2021-06-15 21:56:36 [info     ] [hathor.cli.run_node] hathor-core v0.39.1            genesis=3fdff62 hathor=0.39.1 my_peer_id=c68251cd14fb3d02eb743f39c5663f291f17d40f466fc0207eae28a82cd4e0ba pid=20658 platform=Darwin-20.5.0-x86_64-i386-64bit python=3.7.10-CPython
2021-06-15 21:56:36 [info     ] [hathor.cli.run_node] with storage                   path=/Users/jan/Projects/hathor-core4/datamain storage_class=TransactionRocksDBStorage
2021-06-15 21:56:36 [info     ] [hathor.cli.run_node] with cache                     capacity=100000 interval=5
2021-06-15 21:56:36 [info     ] [hathor.manager] start manager                  network=mainnet
2021-06-15 21:56:36 [info     ] [hathor.p2p.manager] update whitelist
2021-06-15 21:56:36 [info     ] …
```
> feat(cli): option to log in plain JSON

- .codecov.yml
- Makefile
This moves the minimum coverage check to codecov. The pipeline will still fail if coverage is not reached, but the tests checks will still pass, this should make it easier to see coverage specific failures.
> chore(ci): use codecov for minimum coverage check

- hathor/conf/settings.py
- hathor/p2p/states/peer_id.py
This change makes it so we have to explicitly enable "peer blocked" warnings. Which should make it so "internal nodes" that don't use the default whitelist don't annoy everyone.
> feat(p2p): only say the peer is "blocked" when explicitly configured

- hathor/cli/run_node.py
- hathor/transaction/storage/__init__.py
- hathor/transaction/storage/old_rocksdb_storage.py
- hathor/transaction/storage/rocksdb_storage.py
- tests/tx/test_tx_storage.py
Use single rocksdb database with multiple tables (instead of multiple databases), split metadata from tx/block data, and use simpler/faster serialization (struct/json instead of protobuf).
The new storage is created and included in tests but hathor-cli will use the `OldRocksDBStorage` which is s copy of the old storage, so the changes on this PR cannot break any deploy.
> feat(storage): new rocksdb storage with improved performance

- hathor/consensus.py
- hathor/transaction/transaction_metadata.py
Example of the duplicate entries:
> fix(tx): Fix duplicate entries in metadata.conflict_with

- .github/workflows/docker.yml
Docker build will prefer a cache from dev when there isn't one for the current branch. This can be a problem because the `dev` branch isn't always built as often as the `master` branch (which is built daily from a scheduled task). And an outdated cache can have some problems. This might be the cause of the recent docker build fails on the `dev` branch, even though the scheduled `master` builds are fine. I'm not sure if this will fix those builds though, because the `dev` builds might still try to load the cache from the `dev` branch.
> chore(ci): use docker cache from master instead of dev

- .github/workflows/docker.yml
We're using official PyPy docker images from https://hub.docker.com/_/pypy and they are no longer providing images for `pypy-3.6-*` which were being used as the base for the build that is failing. Since we're slowly moving away from Python 3.6, and since we also don't officially support PyPy, I think it's best to just drop that build.
> chore(ci): dropping pypy-3.6 because image is no longe provided

- Makefile
- extras/check_version.sh
- hathor/cli/openapi_files/openapi_base.json
- hathor/version.py
- pyproject.toml
I also included a small reorder on check-version (so it fails faster when there is an error) and made it more silent (like the others one are).
> chore: bump version

- .codecov.yml
This happened because the coverage decreased which was allowed because of a configuration problem of the codecov bot.
> chore(ci): lower min coverage, CI check wasn't actually running before

- hathor/conf/settings.py
- hathor/manager.py
The sync-v2 capability was wrongly added to the broadcasted capabilities, which would lead to nodes currently not having sync-v2 implemented to appear as having it enabled and new nodes would try to use sync-v2 and fail
Since the capability name is now tainted, I've renamed it.
> fix(sync-v2): wrongly included sync-v2 capability

- hathor/websocket/factory.py
- tests/websocket/test_websocket.py
I think this is a regression from the mempool API. I made this fix quickly, I haven't added any tests, I'm open to suggestions on how to test this (and possibly any JSON serialization error on events).
> fix(websocket): bytes is not JSON serializable on 'first_block' field

- hathor/cli/run_node.py
> feat(cli): Add --unsafe-mode argument to run_node

- hathor/cli/run_node.py
- hathor/debug_resources.py
Unresolved questions:
- Should these endpoints only by added when enabled from the command line? (like `--enable-debug-api`)
- Is the prefix `_debug/` OK? I wanted it to look as something clearly made for internal use, that's why the `_`
- Should these endpoints be registered to the openapi generator? I just added them without putting much thought into it, they're all missing the parameters supported and/or examples, like we have on other endpoints
- Is there any possibly useful functionality missing?
> feat(debug): add APIs to allow forcing exceptions/prints/etc

- tests/simulation/test_simulator_itself.py
- tests/unittest.py
Fixes https://github.com/HathorNetwork/hathor-core/pull/279.
> fix(tests): assertConsensusEqual() must convert conflict_with to a set for comparison

- .github/workflows/main.yml
- README.md
- poetry.lock
- pyproject.toml
Acceptance criteria: don't run any tests/build on Python 3.6, remove any mentions to Python 3.6, and instead have all texts (and internal settings) use "Python 3.7 (or later)" (or equivalent).
> chore: drop support for Python 3.6

- hathor/transaction/storage/cache_storage.py
- tests/tx/test_tx_storage.py
Also the tests were updated to cover this, with a small refactor, the diff might not make much sense but none of the code that was un-indented had any changes whatsoever.
Acceptance criteria: when calling `CacheStorage.remove_transaction` the transaction must also be removed on the backend storage, and tests should account for that and fail when this doesn't happen.
> fix(storage): TransactionCacheStorage.remove_transaction not forwarded

- hathor/conf/testnet.py
These are valid either on testnet-golf or testnet-foxtrot, so we can discuss the checkpoints independently.
> chore: add checkpoints for testnet

- hathor/conf/testnet.py
- hathor/transaction/storage/exceptions.py
- hathor/transaction/storage/transaction_storage.py
Acceptance criteria: after this version is in use (i.e., after nodes have upgraded), a database used on the mainnet should be rejected immediately when trying to use it for the testnet, and vice-versa; additionally when upgrading mainnet should be implied, but testnet-golf must be explicit (i.e., do not try to "import" a testnet-foxtrot database).
> feat(db): testnet-golf and prevent mixing networks

- hathor/cli/run_node.py
- hathor/indexes.py
- hathor/manager.py
- hathor/transaction/resources/transaction.py
- hathor/transaction/storage/transaction_storage.py
- hathor/wallet/resources/thin_wallet/address_balance.py
- hathor/wallet/resources/thin_wallet/address_history.py
- hathor/wallet/resources/thin_wallet/address_search.py
- hathor/wallet/resources/thin_wallet/token_history.py
- hathor/wallet/resources/thin_wallet/tokens.py
- hathor/websocket/factory.py
- tests/resources/transaction/test_tx.py
- tests/resources/wallet/test_thin_wallet.py
- tests/tx/test_tokens.py
- tests/tx/test_tx.py
- tests/tx/test_tx_storage.py
- tests/wallet/test_index.py
1. Move current indexes to `MemoryIndexesManager`.
2. Remove direct access to internal parts of the indexes (because it will have a different implementation soon).
3. Turn `IndexesManager` into an interface that will be implemented by `DiskIndexesManager` in the near future.
> refactor(indexes): Move all indexes to MemoryIndexesManager

- .github/workflows/main.yml
- hathor/cli/run_node.py
- hathor/indexes/__init__.py
- hathor/indexes/address_index.py
- hathor/indexes/manager.py
- hathor/indexes/memory_address_index.py
- hathor/indexes/rocksdb_address_index.py
- hathor/manager.py
- hathor/transaction/base_transaction.py
- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/rocksdb_storage.py
- hathor/transaction/storage/transaction_storage.py
- hathor/websocket/factory.py
- tests/tx/test_tx.py
- tests/tx/test_tx_storage.py
- tests/unittest.py
1. Create `AddressesIndex` interface.
2. Implement `AddressesRocksDBIndex`.
3. Implement `RocksDBIndexesManager`.
4. Test `RocksDBIndexesManager`.
5. Skip add/del from `AddressesRocksDBIndex` during initialization.
6. Use `RocksDBIndexesManager` when using `TransactionRocksDBStorage`.
> feat(indexes): add RocksDBAddressIndex stored in disk

- .github/workflows/main.yml
This is what happens on a repo that is not the main repo: https://github.com/jansegre/hathor-core/pull/7
This PR is largely based off https://www.cynkra.com/blog/2020-12-23-dynamic-gha/
Acceptance criteria:
- On the main repo (HathorNetwork/hathor-core), the build matrix should be the complete build matrix, the same as it currently is;
- On any other repo, the build matrix should be reduced (I chose Python-3.7 on Ubuntu);
> chore(ci): dynamic matrix for reduced private fork build time

- hathor/manager.py
- hathor/transaction/storage/transaction_storage.py
This index was supposed to be used on sync-v2, but it will not be needed now and will just get in the way of the new index structure.
> refactor(indexes): remove parent-blocks-index

- hathor/p2p/manager.py
- hathor/p2p/peer_storage.py
- tests/p2p/test_protocol.py
https://github.com/HathorNetwork/internal-issues/issues/73
Peers that have no entrypoints and have disconnected must be removed from the known peers list because there is no more use for them.
> feat: remove peers that were disconnected and cant be reconnected anymore

- hathor/cli/run_node.py
- hathor/conf/get_settings.py
This is what it looks like on my machine:
```
2022-01-13 02:32:58 [info     ] [hathor.cli.run_node] hathor-core v0.46.0            genesis=3fdff62 hathor=0.46.0 my_peer_id=7181d232a16ba95001de22d3151b027ed31677c8cd6dc7eb88d538b250186bbf pid=28656 platform=Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29 python=3.8.10-CPython settings=/home/jan/Projects/hathor-nodes/data-1/conf.py
2022-01-13 02:32:58 [info     ] [hathor.cli.run_node] with storage                   path=/home/jan/Projects/hathor-nodes/data-1 storage_class=TransactionRocksDBStorage
2022-01-13 02:32:58 [info     ] [hathor.cli.run_node] with cache                     capacity=100000 interval=5
2022-01-13 02:32:58 [info     ] [hathor.manager] start manager                  network=mainnet
```
I think this will help …
> feat(logs): show settings location on startup

- .github/workflows/main.yml
Since https://github.com/Homebrew/homebrew-core/pull/95667 has been merged, which now fixed homebrew's rocksdb bottle, this PR makes the CI update the package manager's repo before installing packages (i.e. `brew update` before `brew install`, also the same for `apt-get` for consistency). With this we will get the fixed homebrew bottle sooner, otherwise we would only get when either Github's worker is updated or we reach homebrew's autoupdate date (not sure when it is).
All in all, this should be safe and ensure fresher packages (things will break sooner when packages are updated, but also be fixed sooner).
> chore(ci): update package manager's repo before install

- .github/workflows/main.yml
This is a workaround for the issue on #384 while it is not properly fixed. These set of changes will allow the CI tests (but not the docker builds) to keep working, but #384 will a need a fix anyway before we can make a new release. The expectation should be to commit the reverse of this commit before we make any release. Should I create and leave open the reversal of this commit?
> chore(ci): temporarily remove macOS from test matrix

- .github/workflows/main.yml
- poetry.lock
- pyproject.toml
> chore(ci): use rocksdb bindings compatible with latest release

- Dockerfile
- Dockerfile.pypy
This PR fixes a regression from #385 
We introduced a package that installs directly from a git repository instead of from pypi, this makes git a requirement on the Dockerfile step that installs the poetry dependencies. This PR includes installing git on the correct step.
A CI run testing this change is running my fork: https://github.com/jansegre/hathor-core/actions/runs/2054361752
> chore(dockerfile): also install git and pkg-config on setup step

- .github/workflows/docker.yml
- Dockerfile
- hathor/cli/main.py
- hathor/cli/quick_test.py
A trial run is running here: https://github.com/jansegre/hathor-core/runs/5760065789?check_suite_focus=true
This PR has three separate improvements:
- add a subcommand `quick_test` that will exit with success (exit_code==0) when a transaction is added to the database, or exit with failure (exit_code!=0) in any other case (including timing out if it take too long)
- add a step on the CI to test the built image before pushing the image to the repositories, this makes sure that an image which for any reason does not pass the `quick_test` check will not be uploaded
- use debian-slim instead of alpine as the base python image, this is mostly because in alpine rocksdb is not "stable", so we're subject to a lot more of instability, for example, the latest build of rocksdb depends on a version of …
> chore(docker): improve image generation and testing

- hathor/indexes/memory_timestamp_index.py
- hathor/indexes/rocksdb_timestamp_index.py
- hathor/indexes/timestamp_index.py
- hathor/transaction/storage/transaction_storage.py
- tests/simulation/test_simulator.py
- tests/unittest.py
I ran this on ipython after initializing the indexes, on a database with about 2.9M objects.
```
In [9]: def countit(it):
...:     return sum(1 for _ in it)
...:
In [10]: %time countit(tx_storage._topological_fast())
CPU times: user 11min 57s, sys: 0 ns, total: 11min 57s
Wall time: 11min 57s
Out[10]: 2895834
In [11]: %time countit(tx_storage._topological_sort())
CPU times: user 26min 40s, sys: 2.45 s, total: 26min 43s
Wall time: 26min 43s
Out[11]: 2895834
In [12]: %time countit(tx_storage._topological_fast())
CPU times: user 12min 4s, sys: 19.5 ms, total: 12min 4s
Wall time: 12min 4s
Out[12]: 2895834
In [13]: %time countit(tx_storage._topological_sort())
CPU times: user 23min 35s, sys: 3.75 s, total: 23min 39s
Wall time: 23min 39s
Out[13]: 2895834
```
There's some variation, but it's …
> feat(storage): add fast topological iterator

- hathor/indexes/manager.py
- slow_tests/test_simulator.py
- tests/simulation/test_simulator.py
- tests/tx/test_indexes3.py
A standalone test suggests that there initialization time should drop by about half:
This was run on a modified version of `HathorManager.start` to not reset the existing rocksdb indexes and to use the `_topological_fast` iterator:
```
In [1]: %time manager.start()
2022-04-14 19:19:33 [info     ] [hathor.manager] start manager                  network=mainnet
2022-04-14 19:19:33 [info     ] [hathor.p2p.manager] update whitelist
2022-04-14 19:19:33 [info     ] [hathor.manager] initialize
2022-04-14 19:49:42 [info     ] [hathor.manager] ready                          blocks=0 height=0 total_dt=<1ms tx_count=0 tx_rate=? txs=0
2022-04-14 19:49:42 [info     ] [hathor.p2p.manager] listen on                      endpoint=tcp:9101
CPU times: user 30min 3s, sys: 4.51 s, total: 30min 7s
Wall time: …
```
> feat(indexes): add manual tips-index initialization

- tests/tx/test_indexes3.py
These tests were added recently and they both use the simulator in a way that will sometimes fail, which has nothing to do with what is being tested. I think it makes sense to have them as flaky and avoid having to re-run the failed jobs when it occasionally happens.
> chore(tests): mark flaky tests

- .github/workflows/docker.yml
The image pre-build and testing was added recently, but it wasn't setup properly, so it has always been building a single configuration (the Dockerfile's default), instead of using the specific build-args from the job's matrix unit. This PR fixes that and also fixes the pull/cache strategy used on the final build. Because the final build still uses the same arguments as before, it wasn't affected, and the only effect the current changes will have is increasing the chance of cache hits.
A test run was made here: https://github.com/jansegre/hathor-core/actions/runs/2265019983
> chore(ci): fix docker image pre-build for testing

- .github/workflows/docker.yml
- Dockerfile
- Dockerfile.pypy
- Makefile
- hathor/cli/main.py
- hathor/cli/run_node.py
- hathor/cli/top.py
- hathor/merged_mining/coordinator.py
- poetry.lock
- pyproject.toml
- setup.cfg
Test run of docker CI updates: https://github.com/jansegre/hathor-core/runs/6309343035?check_suite_focus=true
Together with the updating of the dependencies is making the fixes necessary for the updated linters and also updating the PyPy images to 3.8 and 3.9 (with PyPy 3.7 removed). We can now start dropping support for Python 3.7 if we want to.
> chore: update dependencies

- hathor/graphviz.py
- hathor/indexes/manager.py
- hathor/manager.py
- hathor/transaction/storage/transaction_storage.py
- hathor/wallet/hd_wallet.py
- tests/tx/test_cache_storage.py
- tests/tx/test_indexes3.py
- tests/tx/test_tx_storage.py
This alternative topological iterator that is significantly faster over the traditional one, nearly as fast as the other one added recently and has a good advantage in that is doesn't need the timestamp indexes to be up-to-date. Which in turn makes it so it can be used for speeding up the rebuilding of indexes, and also other cases where we don't want to rely on the timestamp index, however it cannot be used to rebuild the metadata.
> feat(storage): add an alternative fast topological iterator

- hathor/simulator/simulator.py
- tests/simulation/test_simulator.py
I'm not really sure how this bug remained here for so long. In short, this is what happens:
```
_________________ SyncV1StratumJobTest.test_min_share_weight __________________
self = <tests.tx.test_stratum.SyncV1StratumJobTest testMethod=test_min_share_weight>
def test_min_share_weight(self):
nonce = self._get_nonce()
>       self._submit(self.job['job_id'], nonce)
tests\tx\test_stratum.py:225: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests\tx\test_stratum.py:172: in _submit
self.protocol.lineReceived(
hathor\stratum\stratum.py:207: in lineReceived
return self.handle_request(data['method'], data.get('params'), msgid)
hathor\stratum\stratum.py:421: in handle_request
return self.handle_submit(params, msgid)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> fix(simulator): ignore additional arguments on overriden verify_pow

- hathor/cli/db_export.py
- hathor/cli/db_import.py
- hathor/cli/main.py
- hathor/util.py
This PR depends on #410, it's basically two commands (prefixed with `x-` to indicate they are experimental): `x-import` and `x-export`, that will export raw blocks+transactions with no metadata with a trivial serialization. The format is intended to be simple enough so it can be stable, it's useful for recreating a database without having to sync to the network, and also useful for running experiments related to the loading of transactions.
> feat(cli): add experimental db export/import commands

- hathor/exception.py
- hathor/indexes/address_index.py
- hathor/indexes/base_index.py
- hathor/indexes/deps_index.py
- hathor/indexes/height_index.py
- hathor/indexes/manager.py
- hathor/indexes/memory_address_index.py
- hathor/indexes/memory_deps_index.py
- hathor/indexes/memory_height_index.py
- hathor/indexes/memory_mempool_tips_index.py
- hathor/indexes/memory_timestamp_index.py
- hathor/indexes/memory_tokens_index.py
- hathor/indexes/mempool_tips_index.py
- hathor/indexes/rocksdb_address_index.py
- hathor/indexes/rocksdb_deps_index.py
- hathor/indexes/rocksdb_height_index.py
- hathor/indexes/rocksdb_mempool_tips_index.py
- hathor/indexes/rocksdb_timestamp_index.py
- hathor/indexes/rocksdb_tokens_index.py
- hathor/indexes/rocksdb_utils.py
- hathor/indexes/timestamp_index.py
- hathor/indexes/tips_index.py
- hathor/indexes/tokens_index.py
- hathor/manager.py
- hathor/transaction/base_transaction.py
- hathor/transaction/storage/transaction_storage.py
- tests/tx/test_indexes2.py
- tests/tx/test_indexes4.py
- tests/tx/test_tx_storage.py
Using the latest snapshot (`data-20220303175324.tar.gz`) as a base, initialization is about 60% faster when using all existing in-disk indexes (some indexes are still in-memory only), and about 120% faster than using all in-disk indexes but rebuilding them on every initialization (the current behavior before this PR):
- cold run (all indexes rebuilt, in-disk will be reused later):
```
2022-05-11 20:55:29 [info     ] [hathor.indexes.manager] loaded                         blocks=2267901 height=2259960 total_dt=~3509s tx_count=2895834 tx_rate=825.1686592546121 txs=627933
```` 
- hot run (only in-memory indexes are rebuilt):
```
2022-05-11 21:29:53 [info     ] [hathor.indexes.manager] loaded                         blocks=2267901 height=2259960 total_dt=~1596s tx_count=2895834 …
```
> feat(init): speed up initialization

- .github/workflows/docker.yml
- Dockerfile.pypy
This PR updates a few actions and tweaks to accept failures on the builds of PyPy docker images. There have been a few failures and more investigation is needed, in the mean time, since PyPy does not have first-class support, failures will not stop the build of the other images.
Test run: https://github.com/jansegre/hathor-core/actions/runs/2449232482
> chore(ci): update some CI actions and make docker build more robust

- .github/workflows/main.yml
This PR updates the base OS used by the runners to explicit versions instead of "latest", particularly to update to `macos-12` (becase `macos-latest` is `macos-11`, which is already breaking in Python 3.10).
> chore(ci): update base runners and small tweaks

- hathor/consensus.py
- hathor/indexes/deps_index.py
- hathor/indexes/manager.py
- hathor/indexes/memory_utxo_index.py
- hathor/indexes/rocksdb_tokens_index.py
- hathor/indexes/rocksdb_utils.py
- hathor/indexes/rocksdb_utxo_index.py
- hathor/indexes/utxo_index.py
- hathor/manager.py
- hathor/transaction/storage/binary_storage.py
- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/compact_storage.py
- hathor/transaction/storage/memory_storage.py
- hathor/transaction/storage/rocksdb_storage.py
- hathor/transaction/storage/transaction_storage.py
- hathor/util.py
- tests/tx/test_blockchain.py
- tests/tx/test_indexes.py
- tests/tx/test_indexes4.py
- tests/tx/test_tx_storage.py
- tests/unittest.py
- tests/utils.py
Mini-design:
Provide an API that can be used to query UTXOs given an address/tokenid, and provide some type of filtering by amount that can be used to allow for users to easily implement their own UTXO selection algorithm. It is important to note that some UTXOs may not be "spendable", since the API should be primarily used for cases where "spendable" outputs are the only that make sense, the API will not include them. We could in the future add an option to include locked (not spendable) UTXOs as well, but this is out of the scope of this initial implementation.
User inputs:
- `address`
- `token_uid`
- `target_amount`
- optional: `target_timestamp` (defaults to the timestamp of the best block)
- optional: `target_height` (defaults to the height of the best block)
- optional: `max_count` …
> feat(indexes): add UTXO index

- hathor/api_util.py
- hathor/cli/run_node.py
- hathor/transaction/resources/__init__.py
- hathor/transaction/resources/utxo_search.py
- tests/resources/transaction/test_utxo_search.py
Currently the API looks like this:
```
curl 'localhost:9000/v1a/utxo_search?token_uid=00&address=HJpSx3KCqMTPvHwEEj26SfPMGGQqijY6au&target_amount=1' | jq
{
"success": true,
"utxos": [
{
"txid": "4299c78120b59ff2eef5c10afb3c93e3e255dbec62342e9f0ef6c546d7810084",
"index": 0,
"amount": 6400,
"timelock": null,
"heightlock": 15
}
]
}
```
Undecided:
- should we include the address for each utxo? maybe in the future we can support multiple addresses in a single API and that would work with the same format if it included the address
- should we include any indication that there were UTXOs with that address that were not included (and maybe the reason they were not included, like maximum number of outputs or target_amount sum reached)
- should we include whether there is an UTXO with an amount …
> feat(api): add UTXO search API

- poetry.lock
The latest release of rocksdb (7.3.1) available on homebrew has removed the `hash_index_allow_collision` option. I've updated the binding on the following commit: https://github.com/HathorNetwork/python-rocksdb/commit/bec21991121f9ea03bdaf2f6b91dfaecd0d2b275 and this PR updates the lockfile to use that commit. We don't use the removed option so the removal has no practical consequences.
> chore(ci): update rocksdb bindings to work with latest release

- .github/workflows/main.yml
- hathor/crypto/util.py
- poetry.lock
- pyproject.toml
There are some discussions that can be reached from these links:
- https://github.com/openssl/openssl/issues/16994
- https://github.com/ethereum/execution-specs/issues/506
But basically ripemd160 was put on legacy on OpenSSL and that basically means it's not built by default. Which is already reflected on the Ubuntu 22.04 release.
This affects some `pycoin` calls and our `get_hash160` function. Since this was already addressed on `pycoin`, updating it is enough, and also we can use the same fallback to make `get_hash160` work when the system's OpenSSL does not have ripemd160 available.
This PR also takes the opportunity to update the Ubuntu release used by the CI, since it now works, but also adds the 20.04 release to the matrix so we continue running tests on it.
> chore: update pycoin and add ripemd160 fallback

- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/transaction_storage.py
- tests/tx/test_cache_storage.py
- tests/tx/test_tx_storage.py
When we use a "compound" storage (i.e. when enabling the cache layer), the inner storage instance will not have indexes, only the outer storage instance, and when the database is fresh, while running `_save_or_verify_genesis` the genesis will not be found on the database so `add_to_indexes` will be called, however this happens during construction phase, so because the inner storage is constructed before the outer storage, it doesn't have the context to know if it's OK to skip this or not.
This PR simply changes the behavior from raising an exception to returning. Raising an exception is useful to prevent situations that were constructed incorrectly, but in this case the situation is correct but it's not possible to know that from within the `add_to_indexes`.
In the future, a better …
> fix(cache): unexpected crash when using cache and no snapshot

- hathor/indexes/manager.py
This PR is basically filling a gap that was left when adding the improved progress helper. The storage already has a method to get the total count and the progress helper can already receive a total to improve the log with a percent tracker.
> feat(loading): add total to progress logger

- hathor/cli/quick_test.py
This PR was made because I needed to run quick tests and did not want to wait for it to receive a transaction (which is what it does by default).
> feat(cli): add --no-wait option to quick_test subcommand

- hathor/util.py
This optimization was made during memory usage analysis. During the initialization phase, when loading transactions, we have a timer what will log a warning when the processing of a transaction takes longer than a certain threshold. It will very often go off for random transactions that aren't particularly slow to be processed and it almost never goes off for the same transaction on subsequent runs. What was noticed is that the longer processing time is actually caused by GC pauses, and has nothing to do with the transaction itself.
This PR introduces a helper that will pause automatic garbage collection within a region and uses that helper to make collection happen only during a phase where it won't interfere with the timing of processing a …
> feat(loading): optimize GC so pauses only happen when we want

- hathor/indexes/memory_tokens_index.py
- hathor/util.py
- hathor/wallet/resources/thin_wallet/tokens.py
- tests/resources/wallet/test_thin_wallet.py
This was noticed after the latest deploy. The RocksDB index implementation is stricter than the Memory implementation, so when using a token_uid of invalid length an assertion error is raised when it wasn't before. This PR fixes this behavior.
> fix(api): validate token_uid before using it internally

- hathor/p2p/peer_id.py
When setting up an environment on a M1 Mac, which has a low `ulimit -n` value by default, before any tuning it would frequently fail to open new connections because `PeerId.get_certificate_options` would not be able to open `settings.CA_FILEPATH`. Although some tuning can get rid of the symptom, it showed that a static file is being unnecessarily re-opened multiple times.
This PR basically caches the result of the implementation of `get_certificate_options` so it doesn't have to open the same file multiple times.
> feat(p2p): cache peer certificate options

- hathor/cli/run_node.py
- hathor/conf/settings.py
- hathor/manager.py
User can now start the full node with `--enable-event-queue` and `--retain-events`. The full-node manager will handle these flags. Subsequent PR's will use this value to manage the events inside the full node.
More information can be found on [the design](https://github.com/HathorNetwork/hathor-core/issues/405).
Manual tests on Manager were performed. These were the results:
| INPUT - Flags        |                    |OUTPUT - Manager value |    |           
|----------------------|-----------------|------------------------|--------------
| --enable-event-queue | --retain-events | enable_event_queue     | retain_events |
| TRUE | TRUE | TRUE | TRUE 
| TRUE | FALSE | TRUE | FALSE 
| FALSE | FALSE | FALSE | FALSE
These results just state that `--retain-events` will only be considered if …
> feat: add flags related to the event mechanism

- hathor/indexes/rocksdb_address_index.py
- tests/tx/test_indexes.py
These issue was caught recently. In short it happens because the behavior of the RocksDB key iterator's `get` method is to return the key that was given to seek when it falls through the end of the database, so the method that was prepared to only accept keys that can be found in the database would fail because the seek key is always a prefix and not a key that could be in the database.
In practice this was found happening on wallets that have a multisig address which when they start loading will open a websocket connection and send a subscribe command, which will end up calling the empty address check which before this fix would raise an AssertionError and cause the alert that generated this incident: https://github.com/HathorNetwork/on-call-incidents/issues/50
The test added fails …
> fix(indexes): RocksDB empty address test fail for some multisig addresses

- hathor/p2p/manager.py
- An exception when updating the p2p whitelist stops the looping call nowadays. We must handle this case, restarting the looping call in case it's stopped by an exception.
- The whitelist update GET request must have a client timeout in order to prevent hanging forever waiting for a server response.
Root Cause Analysis: https://github.com/HathorNetwork/hathor-core/issues/406#issuecomment-1213019357
Closes https://github.com/HathorNetwork/on-call-incidents/issues/35
Closes https://github.com/HathorNetwork/hathor-core/issues/406
> feat: add client timeout to whitelist update GET request

- poetry.lock
Changes on python-rocksdb: https://github.com/HathorNetwork/python-rocksdb/commit/947f68a80d97c4a5621ee681ae01602ebd883f3a
> chore(ci): update python-rocksdb to restore CI on macOS

- README.md
The README still references `-E rocksdb` which is not needed anymore and will also not work.
> docs(readme): fix `poetry install` command line

- .github/workflows/docker.yml
- .github/workflows/main.yml
- README.md
- hathor/cli/run_node.py
- hathor/indexes/rocksdb_tokens_index.py
- poetry.lock
- pyproject.toml
This PR includes all the necessary changes to drop support for Python 3.7, which hasn't been used in a while. While this hasn't been discussed too much, impact should be minimal as there are no known deployments using this version. It should also help move closer enabling us to use features not available on Python 3.7, although most of the features that we recently been interested in would require also dropping support for Python 3.8, but it's probably best to do drop support one by one so we could at least start by dropping Python 3.7.
Some of the features of Python 3.9 we're interested in:
- [PEP 585](https://www.python.org/dev/peps/pep-0585), type hinting generics in standard collections;
- maybe [PEP …
> chore(python): drop support for Python 3.7

- hathor/cli/run_node.py
- hathor/metrics.py
- hathor/prometheus.py
- tests/others/test_metrics.py
- tests/tx/test_prometheus.py
Design: https://github.com/HathorNetwork/ops-tools/issues/433
- We should have a metric of number of hits/misses in the cache during execution
- We should log the number of cache hits/misses during initialization phase
- Add a CLI option to set the prefix for all Prometheus metrics.
> feat: monitor tx cache hits/misses

- hathor/p2p/manager.py
- hathor/p2p/peer_storage.py
Fixes [internal-issues #115](https://github.com/HathorNetwork/internal-issues/issues/115).
Full nodes have been logging a lot of connection failure during startup. Together with these messages, there are many "maximum number of connections" and "no file description available" errors.
Here are a few examples:
```
2022-09-02 05:26:05 [warning  ] [hathor.p2p.manager] connection failure             endpoint=tcp://18.159.135.6:40403 failure=Couldn't bind: 24: Too many open files.
2022-09-02 05:26:05 [warning  ] [hathor.p2p.manager] reached maximum number of connections max_connections=125
```
1) Stop trying to connect multiple times to the same endpoints at startup.
2) Stop reaching the maximum number of connections at startup.
> fix(p2p): Fix too many connection failures at startup

- hathor/cli/run_node.py
- hathor/conf/settings.py
- hathor/manager.py
- hathor/p2p/resources/__init__.py
- hathor/p2p/resources/healthcheck.py
- tests/resources/p2p/test_healthcheck.py
design: https://github.com/HathorNetwork/ops-tools/issues/431
- We should have a new endpoint `/p2p/readiness` that checks if:
- The node has blocks with a recent timestamp
- The node has at least one connected and synced peer
> feat: p2p readiness healthcheck

- hathor/consensus.py
- hathor/indexes/memory_address_index.py
- hathor/indexes/rocksdb_address_index.py
- hathor/manager.py
- hathor/pubsub.py
- hathor/simulator/simulator.py
- hathor/simulator/tx_generator.py
- hathor/transaction/storage/transaction_storage.py
- hathor/wallet/base_wallet.py
- tests/consensus/test_consensus2.py
- tests/consensus/test_consensus5.py
- tests/consensus/test_soft_voided.py
- tests/consensus/test_soft_voided2.py
- tests/consensus/test_soft_voided3.py
- tests/consensus/test_soft_voided4.py
- tests/simulation/base.py
- tests/tx/test_tx_storage.py
- tests/utils.py
Fixes https://github.com/HathorNetwork/hathor-core/issues/481.
1. Fix calling events out-of-order.
2. Fix wallet wrongfully adding utxos of voided transactions.
3. Remove hard-coded hash from `tests/consensus/test_soft_voided.py`.
4. Refactor events: replace `STORAGE_TX_WINNER` and `STORAGE_TX_VOIDED` by `CONSENSUS_TX_UPDATE`.
> fix(pubsub): Calling events out-of-order

- hathor/indexes/base_index.py
- hathor/indexes/info_index.py
- hathor/indexes/manager.py
- hathor/indexes/memory_info_index.py
- hathor/indexes/memory_tips_index.py
- hathor/indexes/partial_rocksdb_tips_index.py
- hathor/indexes/rocksdb_info_index.py
- hathor/indexes/tips_index.py
- hathor/transaction/storage/transaction_storage.py
- tests/others/test_init_manager.py
- tests/p2p/test_double_spending.py
- tests/tx/test_tx_serialization.py
- tests/tx/test_tx_storage.py
This is how it looks like on my machine, while still loading the deps and mempool indexes:
```
2022-09-15 13:59:03 [info     ] [hathor.cli.run_node] hathor-core v0.50.2            genesis=3fdff62 hathor=0.50.2 my_peer_id=7181d232a16ba95001de22d3151b027ed31677c8cd6dc7eb88d538b250186bbf pid=5375 platform=macOS-12.5.1-arm64-arm-64bit python=3.10.4-CPython settings=/Users/jan/Projects/hathor-nodes/data-1/conf.py
2022-09-15 13:59:04 [info     ] [hathor.cli.run_node] with storage                   path=/Users/jan/Projects/hathor-nodes/data-1 storage_class=TransactionRocksDBStorage
2022-09-15 13:59:04 [info     ] [hathor.cli.run_node] with cache                     capacity=100000 interval=5
2022-09-15 13:59:04 [info     ] [hathor.cli.run_node] with indexes …
```
> feat(indexes): partial optimization of tips indexes using rocksdb

- hathor/manager.py
- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/transaction_storage.py
fixes: https://github.com/HathorNetwork/hathor-core/issues/487
We shouldn't corrupt the database when stopping the node.
There is a better description of the error and the exact scenario that triggered it in the issue above.
I've only observed this when running a local fullnode and stopping it with `Ctrl + C`, but I'm not sure if this couldn't also happen when running it with Docker in the cloud.
> fix: database corruption when stopping node with cache enabled

- hathor/indexes/rocksdb_utxo_index.py
- tests/tx/test_indexes.py
- tests/unittest.py
Also included in the fix is a small change in the internal implementation of the RocksDB UTXO index for the internal iterator to only yield entries that match the relevant prefix, instead of having to do the filtering from outside the iterator.
- the RocksDB implementation of UTXO index must correctly return the UTXO when the target amount is smaller than the smallest UTXO and it is the only UTXO for that address
> fix(indexes): RocksDB UTXO index could miss some results

- hathor/cli/run_node.py
- Starting the node with no specific parameters should default to using the rocksdb indexes (when rocksdb storage is used, which is already default);
- Setting the node to use memory storage should still imply memory indexes;
- There should be an option to use memory indexes with rocksdb storage;
- Using the old `--x-rocksdb-indexes` parameter should work but give a warning that it is deprecated (it basically has no effect now anyway);
> feat(cli): make rocksdb indexes the default for rocksdb storage

- hathor/cli/run_node.py
I noticed the issue during [this CI run](https://github.com/HathorNetwork/hathor-core/actions/runs/3274465137/jobs/5388027001) logs the following:
```
Run docker run --rm hathor-core:test quick_test --data / --testnet
docker run --rm hathor-core:test quick_test --data / --testnet
shell: /usr/bin/bash -e {0}
env:
TEST_TAG: hathor-core:test
2022-10-18 14:50:56 [error    ] [hathor.cli.main] Uncaught exception:            
File "/usr/local/lib/python3.8/site-packages/hathor/cli/main.py", line 159, in main
sys.exit(CliManager().execute_from_command_line())
File "/usr/local/lib/python3.8/site-packages/hathor/cli/main.py", line 154, in execute_from_command_line
module.main()
File "/usr/local/lib/python3.8/site-packages/hathor/cli/quick_test.py", line 62, in …
```
> fix(cli): regression made it so testnet couldn't be selected

- hathor/storage/rocksdb_storage.py
- tests/unittest.py
1) Be able to run tests without increasing the maximum number of open files.
2) Properly close the file descriptor after it's been used.
> test: Fix too many files open errors

- hathor/consensus.py
- hathor/indexes/base_index.py
- hathor/indexes/manager.py
- hathor/indexes/memory_info_index.py
- hathor/indexes/mempool_tips_index.py
- hathor/indexes/partial_rocksdb_tips_index.py
- hathor/indexes/rocksdb_info_index.py
- hathor/manager.py
- hathor/transaction/resources/mempool.py
- hathor/transaction/storage/transaction_storage.py
- tests/p2p/test_sync_mempool.py
- tests/simulation/test_simulator.py
- tests/tx/test_indexes.py
- tests/tx/test_reward_lock.py
- tests/tx/test_tips.py
This was originally included in #480 but was removed for that to be implemented and reviewed quicker.
The main advantage of this PR is a significant initialization speed up and slight memory usage reduction when not using sync-v2 (the default).
Before:
```
2022-10-18 17:28:40 [info     ] [hathor.cli.run_node] hathor-core v0.51.0            genesis=3fdff62 hathor=0.51.0 my_peer_id=c68251cd14fb3d02eb743f39c5663f291f17d40f466fc0207eae28a82cd4e0ba pid=96302 platform=macOS-12.5.1-arm64-arm-64bit python=3.10.4-CPython settings=/Users/jan/Projects/hathor-nodes/data-2/conf.py
2022-10-18 17:28:40 [info     ] [hathor.cli.run_node] with storage                   path=/Users/jan/Projects/hathor-nodes/data-2 storage_class=TransactionRocksDBStorage
2022-10-18 17:28:40 [info     ] [hathor.cli.run_node] …
```
> feat(indexes): make sync-v2 indexes only load when sync-v2 is enabled

- hathor/cli/db_export.py
- hathor/cli/db_import.py
- hathor/cli/quick_test.py
- hathor/cli/run_node.py
- hathor/cli/shell.py
I noticed this when looking into why the docker image build CI job was timing out: https://github.com/HathorNetwork/hathor-core/actions/runs/3389892806/jobs/5639384404
> fix(cli): builder refactor regression skipped register_resources

- hathor/transaction/storage/cache_storage.py
This was noticed after we tried to deploy a node on the testnet using an old snapshot that happened to have cache enabled and the migration failed.
This is the error that happened:
```
File "/usr/local/lib/python3.9/site-packages/hathor/transaction/storage/transaction_storage.py", line 220, in _check_and_apply_migrations
migration.run(self)
File "/usr/local/lib/python3.9/site-packages/hathor/transaction/storage/migrations/add_min_height_metadata.py", line 34, in run
for tx in storage.topological_iterator():
File "/usr/local/lib/python3.9/site-packages/hathor/transaction/storage/transaction_storage.py", line 683, in topological_iterator
assert self.indexes is not None
AssertionError
The above exception was the direct cause of the following exception: …
```
> fix(init): indexes could not be used on migrations when using cache

- hathor/builder.py
- hathor/manager.py
- hathor/simulator/simulator.py
- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/transaction_storage.py
- tests/others/test_init_manager.py
- tests/others/test_metrics.py
- tests/p2p/test_connections.py
- tests/resources/base_resource.py
- tests/resources/transaction/test_utxo_search.py
- tests/resources/wallet/test_lock.py
- tests/resources/wallet/test_unlock.py
- tests/tx/test_tx_storage.py
- tests/unittest.py
1) Remove `wallet_index` and `utxo_index` from `HathorManager`'s constructor.
2) Refactor tests to use `self.create_peer(...)` instead of instantiating `HathorManager` directly.
3) Remove `TransactionStorage.with_index` attribute as a preparation to move the `IndexManager` instantiation to the builder.
> refactor(manager): Move contructor's parameter wallet_index and utxo_index to builder

- .github/workflows/docker.yml
- .github/workflows/main.yml
- README.md
- hathor/merged_mining/coordinator.py
- hathor/p2p/protocol.py
- hathor/stratum/stratum.py
- hathor/wallet/hd_wallet.py
- hathor/wallet/resources/thin_wallet/send_tokens.py
- poetry.lock
- pyproject.toml
Test run of the docker image build: https://github.com/jansegre/hathor-core/actions/runs/3489935997/jobs/5840702121
- All dependencies should be updated to the latest release that doesn't cause significant disruption;
- In particular, also update `python-hathorlib` to `v0.3.0`;
- Python 3.11 should be added to build/test workflows;
- A test run for the changes on the docker CI should be successful;
- Minor typing/docs adjustments should be made according to what changed and what the updated linters caught;
> chore: update dependencies and add support for Python 3.11

- hathor/consensus.py
- hathor/event/event_manager.py
- hathor/pubsub.py
- hathor/simulator/miner.py
- tests/event/test_event_manager.py
- tests/event/test_event_reorg.py
- tests/unittest.py
Relevant design is [here](https://github.com/HathorNetwork/hathor-core/issues/405).
- `REORG_STARTED` and `REORG_FINISHED` must be correctly emitted with their corresponding groups
> feat(events): emit reorg event during consensus

- .github/workflows/main.yml
- README.md
- [Broken README from v0.52.1 release](https://github.com/HathorNetwork/hathor-core/blob/v0.52.1/README.md)
- [Fixed README from this PR](https://github.com/HathorNetwork/hathor-core/blob/chore/fix-workflow-badges/README.md)
This is related to https://github.com/badges/shields/issues/8671
- badges for `tests` and `build` workflows should be rendered correctly now
> chore(docs): fix worflow badges on rendered README

- .gitignore
- Makefile
- hathor/conf/get_settings.py
Implement `make dmypy` and `make dcheck` commands, analogous to the existing `make mypy` and `make check`.
[Mypy daemon](https://mypy.readthedocs.io/en/stable/mypy_daemon.html) is a mypy server running in the background. Once started, each subsequent `dmypy` call is 10 or more times faster than the regular `mypy` command, according to the docs. In my setup, `dmypy` runs almost instantaneously while `mypy` can take several minutes sometimes, really slowing down the workflow when you're fighting with type hints.
I set a timeout of `86400` seconds (1 day) in the command, that is, the daemon will shut down itself after 1 day of inactivity. It can also be stopped manually before that with the `dmypy stop` command.
> feat(mypy-daemon): implement mypy daemon commands

- hathor/indexes/address_index.py
- hathor/indexes/memory_address_index.py
- hathor/indexes/memory_tx_group_index.py
- hathor/indexes/rocksdb_address_index.py
- hathor/indexes/rocksdb_tx_group_index.py
- hathor/indexes/tx_group_index.py
1) Create a `TxGroupIndex`, which is an abstract class to group transactions according to a key. It will be used in future PRs.
2) Implemente `MemoryTxGroupIndex` and `RocksDBTxGroupIndex`, which are abstract classes as well.
3) Refactor `AddressIndex` to use the `TxGroupItem`. Specifically, `MemoryAddressIndex` must use `MemoryTxGroupIndex`, and `RocksDBAddressIndex` must use `RocksDBTxGroupIndex`.
> refactor(indexes): Create a generic TxGroupIndex and uses it on AddressIndex

- hathor/event/event_manager.py
- hathor/pubsub.py
After discussing with @jansegre , we came to the conclusion that this event is not necessary and its meaning will be covered be the `TX_METADATA_CHANGED` / `BLOCK_METADATA_CHANGED` events.
> feat(events): remove NETWORK_NEW_TX_VOIDED event

- .github/workflows/main.yml
- CI run for macos should be working again
- nothing else must be affected
> chore(ci): fix installing dependencies on macos

- hathor/event/event_manager.py
- hathor/event/model/base_event.py
- hathor/pubsub.py
- tests/event/test_event_manager.py
- Remove `NETWORK_BEST_BLOCK_FOUND` event
- Remove `NETWORK_ORPHAN_BLOCK_FOUND` event
Just like in https://github.com/HathorNetwork/hathor-core/pull/529, where `NETWORK_NEW_TX_VOIDED` was removed, after discussing with @jansegre we came to the conclusion that these two events are not necessary and can be removed as well. Their functionality is already covered by existing events. It may be necessary, though, to add new attributes in the event body to represent the different types. This will be clearer when implementing an use case, and then a new PR may be created.
> feat(events): remove NETWORK_BEST_BLOCK_FOUND and NETWORK_ORPHAN_BLOCK_FOUND events

- hathor/cli/events_simulator/events_simulator.py
- hathor/cli/events_simulator/scenario.py
- hathor/cli/main.py
- Implement new `events_simulator` CLI command to enable a dummy stream of events to a WebSocket endpoint, simulating real scenarios
- Option `--scenario` to choose the scenario between `SINGLE_CHAIN`, `BEST_CHAIN_WITH_SIDE_CHAINS`, and `MULTIPLE_FORKS`
- Option `--port` to chose the WebSocket server port
- Actual list of dummy events for each scenario not implemented yet.*
*That's as simple as setting the list of `BaseEvent`s for each scenario in the `scenario.py` file. This will be done in a separate PR after pending design discussions and definition of which events should be emitted in each case. Creating this list should be almost a 1:1 conversion from the list of events that will be specified in the design.
> feat(events): CLI tool for testing event integration

- .github/workflows/docker.yml
- Add the git commit sha in nightly Docker images tag
For the schedule event, which is the one we use to build nightlies, the commit sha of the default branch is the one included in the build context: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
This is enough for us, since we will always build nightlies from the default branch.
> ci: add commit sha on nigthly image tags

- hathor/event/websocket/factory.py
- hathor/transaction/base_transaction.py
- poetry.lock
- pyproject.toml
- Update `mypy`, `mypy-zope`, and `pydantic` dependencies
- Include pydantic's `init_typed` config to improve type checking robustness
- Fix in `base_transaction.py` (alerted by the new mypy version)
- Fix in `factory.py` (alerted by the `init_typed` config)
> Update static-typing related packages

- README.md
- hathor/p2p/resources/status.py
- tests/resources/p2p/test_status.py
This addition will allow the hathor-p2p-monitor to monitor synchronization with sync-v2 peers in a simplified way.
Ref.: https://github.com/HathorNetwork/hathor-p2p-monitor/pull/69
- add `best_block` and `best_block_tips` to dag property of `/status`
> feat: add best_block and best_block_tips to dag on status

- hathor/cli/events_simulator/events_simulator.py
- hathor/event/event_manager.py
- hathor/event/websocket/factory.py
- hathor/manager.py
- Fix bug that was preventing node initialization due to incorrect import order
- The Event Simulator indirectly imported code that used `get_settings` before it was called by `run_node` with the correct configuration, therefore generating a `loading config twice with a different file` error.
- Fix bug that was preventing node initialization with the events feature due to incorrect start order
- The `HathorManager` was sending events relevant to the `EventManager` before starting it.
> bugfix: fix initialization order bugs

- Makefile
- extras/check_version.sh
- hathor/version.py
- tests/resources/test_version.py
1. We should be able to overwrite the version reported by hathor-core by creating a BUILD_VERSION file with the new version.
2. We should allow an optional arg in our `check_version.sh` script containing an additional version against which we should check
These mechanisms will be used mainly by CI/CD to inject the built version into Docker images and validate it.
> feat: allow version overwriting by creating a BUILD_VERSION file

- hathor/builder.py
- hathor/manager.py
- hathor/simulator/simulator.py
- tests/consensus/test_soft_voided2.py
- tests/others/test_init_manager.py
- tests/tx/test_tx_storage.py
- tests/unittest.py
1) Refactor to build the `ConsensusAlgorithm` object outside of `HathorManager`.
2) Refactor `HathorManager` to require a `ConsensusAlgorithm` object.
3) Remove `HathorManager.soft_voided_tx_ids` attribute.
> refactor(builder): HathorManager stops building ConsensusAlgorithm itself

- .github/workflows/TESTING.md
- .github/workflows/docker.yml
- .github/workflows/main.yml
- extras/check_version.sh
- Disable caching of Docker layers when building `nightly` builds
- Write the BUILD_VERSION file with the version that was just built. This should be done only for `nigthly`, `release-candidate` and `release` builds.
- For the `release-candidate`, we should only build a Docker image for the default Python version (currently 3.9), and it should have only the main tag on it, not the tags for specific python versions/implementations)
- We should send messages to Slack for builds of `release-candidate` and `release` images, but only for the default python version in our version matrix. Otherwise we would be sending many alerts at once.
- Fix a previous error in the workflow where we were apparently making comparisons like `if: steps.prep.outputs.login-dockerhub`, but we were assign the value …
> ci: adapt to the new release process

- .github/workflows/docker.yml
- .github/workflows/prep.py
- Makefile
- extras/check_version.sh
- extras/github/docker.py
- extras/github/test_docker.py
- tests/resources/test_version.py
- We should extract the python CI logic from inside `.github/workflows/docker.yml` to an actual .py file
- We should have unit tests for the extracted CI logic
- Change the variable `should-notify-slack` to `disable-slack-notification`, to make the code clearer
Note: I moved the logic to `extras/github/docker.py` alongside its test file, but if there is a better place just let me know.
> chore(ci): Change should-notify-slack to disable-slack-notification and extract scripts from the workflow definition

- hathor/builder/__init__.py
- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/manager.py
- hathor/simulator/simulator.py
- tests/others/test_builder.py
- tests/others/test_cli_builder.py
- tests/others/test_init_manager.py
- tests/tx/test_tx_storage.py
- tests/unittest.py
1) Make parameters `peer_id`, `tx_storage`, and `network` required on `HathorManager.__init__(...)`.
2) Create a `TestBuilder` to build all objects for tests.
3) Refactor tests to use `TestBuilder`.
Note: I was considering to refactor `CliBuilder` to use `Builder` but I felt it was too much for now. Besides that, I don't need to change the `CliBuilder` to move forward with my project.
> refactor(builder): Change HathorManager.__init__ and change tests to use TestBuilder

- extras/github/test_docker.py
1. Set envvar `GITHUB_REPOSITORY` as `hathornetwork/hathor-core` for tests. This fixes some tests failures when running on a fork repository.
> chore(extras): Fix missing envvar in GitHub extras tests

- hathor/simulator/simulator.py
- tests/simulation/test_trigger.py
Fixes https://github.com/HathorNetwork/hathor-core/issues/574.
1. Stop simulator on `tearDown()`.
> tests: Non-stopped simulator causing other tests to fail

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/manager.py
- hathor/simulator/simulator.py
- tests/event/test_event_manager.py
- tests/event/test_event_reorg.py
- tests/unittest.py
- Make `HathorManager` receive a required `EventStorage`
- This will be necessary on https://github.com/HathorNetwork/hathor-core/pull/555, to check if the event queue feature was enabled in the previous run
- `Builder` changes
- Add `peer_id` to builder artifacts
- Make memory be the default storage type
- Add RockDB's `cache_capacity` and `with_index` configs
- Add `enable_event_manager()` auxiliary method
- Update usages of `Builder`, (`CliBuilder` and `Simulator`) to use event related configs
> chore: add RocksDB and EventManager builder configs

- extras/github/docker.py
This should fix this issue: https://github.com/HathorNetwork/hathor-core/actions/runs/4829377170/jobs/8604345888
> chore(ci): use GITHUB_SHA env var instead of github.sha

- Dockerfile
- Dockerfile.pypy
Our built Docker images should contain the BUILD_VERSION file, so they are able to report the injected version when running.
1. Create a BUILD_VERSION file in your local repo:
```
cat <<EOF > BUILD_VERSION                         
1.2.3
EOF
```
2. Build the image with `docker build -t local/hathor-core .`
3. Run it with `docker run -it local/hathor-core run_node`
The first log should contain the right version.
4. Remove the BUILD_VERSION file and build and run the image again. The version should now contain the `-local` prefix.
> fix(version): copy the BUILD_VERSION file into the Docker image

- hathor/cli/replay_logs.py
1. Add a `--color` parameter to the replay-log cli, so we can force it to replay logs with colors.
> feat(cli): Add --color parameter to replay-logs cli

- hathor/builder/cli_builder.py
- hathor/conf/settings.py
- hathor/manager.py
- hathor/p2p/manager.py
- hathor/p2p/node_sync.py
- hathor/p2p/protocol.py
- hathor/p2p/rate_limiter.py
- hathor/p2p/sync_manager.py
- hathor/transaction/storage/transaction_storage.py
- tests/p2p/test_cmds.py
- tests/p2p/test_sync.py
- tests/p2p/test_sync_enabled.py
- tests/p2p/test_sync_rate_limiter.py
- tests/unittest.py
The reasoning behind this change is described in https://github.com/HathorNetwork/on-call-incidents/issues/109#issuecomment-1535409697
- Limit the number of syncs that can happen simultaneously
- Ability to configure that number via `HathorSettings`
- Rotate the group of peers that are syncing every 10 minutes
- Connections should not be changed. Only whether the connected peer is syncing or not.
- Set a group of peers to always run the sync
- Create a `cmd_path`, a place to put files to communicate with the full node.
- Use `force_sync_rotate` file to force a sync rotation.
- Use `always_enable_sync.txt` file to set peers to always have sync enabled.
- Add a global rate limiter to the number of calls per second to `NodeSyncTimestamp.send_tips()`.
> feat(sync): Limit number of sync running simultaneously

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/manager.py
- hathor/p2p/manager.py
- hathor/p2p/sync_v1_1_factory.py
- hathor/p2p/sync_version.py
- tests/others/test_cli_builder.py
- tests/p2p/test_sync.py
- tests/unittest.py
This is a complimentary PR to #581 
The reasoning is to create a barrier between peers using the new sync code. The protocol and implementation are backwards compatible, but a barrier helps ensure that peers that are only running sync-v1.1 (not the bridge peer running both versions) will almost certainly (unless someone is intentionally spoofing the sync version) connect to other peers running sync-v1.1, and that should be of great help to #581
- add a new sync-v1.1 version marker that will use the same class as sync-v1.0 (which was just sync-v1 before)
- disable sync-v1.0 by default, requiring the use of a cli param to enable it
- enable sync-v1.1 whenever sync-v1.0 would be enabled before
- builder will keep referencing a single sync-v1 version, which will only enable sync-v1.1 and not …
> feat(sync): boilerplate for sync-v1.1 protocol

- hathor/p2p/states/peer_id.py
- hathor/p2p/sync_version.py
- tests/p2p/test_whitelist.py
1) Consider `SyncVersion.v1_1` as v1.
> fix(p2p): Fix v1.1 not enforcing whitelist

- extras/github/docker.py
- hathor/version.py
- tests/resources/test_version.py
- We should not include a `\n` on the generated BUILD_VERSION file
> fix: do not include newline in the BUILD_VERSION file

- hathor/sysctl/protocol.py
- hathor/sysctl/sysctl.py
- tests/sysctl/test_sysctl.py
1) Validate date types before calling setter. This is important to prevent sending a `str` where the setter expects and `int`, for instance.
> feat(sysctl): Validate types before calling setter

- hathor/builder/__init__.py
- hathor/builder/cli_builder.py
- hathor/builder/resources_builder.py
- hathor/cli/run_node.py
- tests/others/test_cli_builder.py
1) Move resources builder from `CliBuilder` to `ResourcesBuilder`.
2) Move `listenTCP()` call from builder to `run_node` cli.
> refactor(builder): Split resources creation from CliBuilder to ResourcesBuilder

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/builder/resources_builder.py
- hathor/cli/run_node.py
- hathor/event/event_manager.py
- hathor/event/model/node_state.py
- hathor/event/storage/event_storage.py
- hathor/event/storage/memory_storage.py
- hathor/event/storage/rocksdb_storage.py
- hathor/manager.py
- hathor/pubsub.py
- hathor/transaction/util.py
- tests/event/test_event_manager.py
- tests/event/test_event_reorg.py
- tests/event/test_event_storage.py
- tests/others/test_cli_builder.py
Implement changes described in https://github.com/HathorNetwork/rfcs/pull/52
- Implement new `EventStorage` functionality
- Storage and retrieval of `NodeState`
- Storage and retrieval of event queue feature state
- Clearing events
- Update `HathorManager`
- Remove `event_storage` arg, make `event_manager` required, and add `enable_event_queue`
- Initialization fails if it starts without the event queue feature, and it was enabled in a previous start
- Handling of LOAD phase events
- Update `EventManager` to support handling of LOAD phase events
- Remove `--x-emit-load-events` CLI flag, as it's not necessary anymore in the way events are handled in the LOAD phase
- New `bytes_to_int()` function in `transaction.util`
> feat(events): realiable integration during the load phase

- hathor/conf/settings.py
- hathor/consensus/consensus.py
- hathor/graphviz.py
- hathor/indexes/base_index.py
- hathor/indexes/manager.py
- hathor/indexes/memory_height_index.py
- hathor/indexes/rocksdb_deps_index.py
- hathor/simulator/fake_connection.py
- hathor/simulator/simulator.py
- hathor/simulator/trigger.py
- hathor/simulator/tx_generator.py
- hathor/transaction/base_transaction.py
- hathor/transaction/storage/memory_storage.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/transaction.py
- hathor/transaction/transaction_metadata.py
- tests/consensus/test_consensus.py
- tests/consensus/test_soft_voided.py
- tests/consensus/test_soft_voided3.py
- tests/consensus/test_soft_voided4.py
- tests/p2p/test_protocol.py
- tests/resources/transaction/test_tx.py
- tests/tx/test_cache_storage.py
- tests/tx/test_tx.py
- tests/tx/test_tx_storage.py
- tests/wallet/test_wallet.py
- tests/wallet/test_wallet_hd.py
1. Void all partially validated transactions.
2. Show partially validated transactions in yellow in Graphviz.
3. Fix wrong method names in `IndexManager`: `enable_deps_index` and `enable_mempool_index`.
4. Fix `RocksDBDepsIndex` when new transactions are added.
5. Add some tools for `Simulator` and related classes.
6. Add trigger `StopAfterNTransactions` for simulators.
7. Check `ValidationState` with `meta.voided_by` before saving metadata to storage.
8. Fix some flaky tests using `StopAfterNTransactions`.
> feat: Add safeguards for partially validated transactions [part 1/2]

- hathor/sysctl/protocol.py
- hathor/sysctl/sysctl.py
- tests/sysctl/test_sysctl.py
1) Add `!help` command, which shows all commands available.
2) Add `!help [cmd]` command, which shows a help message for the command.
```
!help
p2p.always_enable_sync
p2p.always_enable_sync.readtxt
p2p.force_sync_rotate
p2p.max_enabled_sync
p2p.rate_limit.global.send_tips
p2p.sync_update_interval
!help p2p.always_enable_sync
getter() -> List[str]:
Return the list of sync-always-enabled peers.
setter(values: List[str]) -> None:
Change the list of sync-always-enabled peers.
!help p2p.rate_limit.global.send_tips
getter() -> Tuple[int, float]:
Return the global rate limiter for SEND_TIPS.
setter(max_hits: int, window_seconds: float) -> None:
Change the global rate limiter for SEND_TIPS.
The rate limiter is disabled when `window_seconds == 0`.
```
> feat(sysctl): Add helper command

- hathor/event/websocket/request.py
- hathor/indexes/rocksdb_utils.py
- Update code to use new Python 3.9 features
> chore: python 3.9 updates

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/manager.py
- hathor/p2p/factory.py
- hathor/p2p/manager.py
- hathor/p2p/protocol.py
- hathor/p2p/sync_v1_1_factory.py
- hathor/p2p/sync_v1_factory.py
- hathor/simulator/fake_connection.py
- tests/others/test_init_manager.py
- tests/others/test_metrics.py
- tests/p2p/netfilter/test_factory.py
- tests/p2p/test_peer_id.py
- tests/p2p/test_sync.py
- tests/unittest.py
1) Build `ConnectionsManager` in builders.
2) Move `ssl: bool`, `enable_sync_v1`, `enable_sync_v1_1`, and `enable_sync_v2` to `ConnectionsManager`.
3) Remove `HathorManager.server_factory` and `HathorManager.client_factory`.
There are still some network-related attributes and methods on `HathorManager`. I'll move those on a separate refactor to keep this one small for reviewers. Some attributes and methods yet-to-be moved out of `HathorManager` are:
- `listen_addresses: List[str]`
- `capabilities`
- `has_sync_version_capability()`
- `add_peer_to_whitelist()`
- `remove_peer_from_whitelist_and_disconnect()`
- `listen()`
- `do_discovery()`
> refactor(p2p): Build ConnectionsManager in builder

- hathor/consensus/consensus.py
- hathor/manager.py
- hathor/transaction/base_transaction.py
- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/exceptions.py
- hathor/transaction/storage/memory_storage.py
- hathor/transaction/storage/rocksdb_storage.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/storage/tx_allow_scope.py
- hathor/transaction/transaction_metadata.py
- tests/others/test_init_manager.py
- tests/tx/test_tx_storage.py
- tests/tx/test_validation_states.py
This change was split out from #577. The main objective is to be able to do this:
```python
tx.set_validation(ValidationState.BASIC)  # this is a partially validated transaction
tx_storage.save_transaction(tx)  # this fails with an assertion error
with stx_storage.allow_partially_validated_context():
tx_storage.save_transaction(tx)  # but this succeeds
tx_storage.get_transaction(tx.hash)  # this also fails, but with an error that inherits from "not found"
with stx_storage.allow_partially_validated_context():
tx_storage.get_transaction(tx.hash)  # but this succeeds
```
This change is only exists to reduce the scope where the storage APIs accept reading/writing partially validated transactions so that the changes needed by sync-v2 can have a very reduced an limited impact on the rest of the …
> feat: add safeguards for partially validated transactions [part 2/2]

- hathor/builder/sysctl_builder.py
- hathor/conf/settings.py
- hathor/sysctl/p2p/manager.py
- hathor/sysctl/websocket/__init__.py
- hathor/sysctl/websocket/manager.py
- hathor/websocket/factory.py
- tests/sysctl/test_websocket.py
1) Change `settings.WS_MAX_SUBS_ADDRS_CONN` default value to `None`, which means unlimited.
2) Change `settings.WS_MAX_SUBS_ADDRS_EMPTY` default value to `None`, which means unlimited.
3) Create sysctl command `ws.max_subs_addrs_conn`.
4) Create sysctl command `ws.max_subs_addrs_empty`.
> feat(ws): Change default configuration of WS_MAX_SUBS_ADDRS_CONN and WS_MAX_SUBS_ADDRS_EMPTY to infinite

- hathor/builder/cli_builder.py
- hathor/conf/get_settings.py
This wasn't _exactly_ the case before this commit. On one side when using the deprecated module settings the same module would always be loaded, and the same `SETTINGS` property would be accessed, but reloading the module (or at least leaving that up to importlib) unnecessary. On the new YAML system the file is reloaded everytime, this is also unnecessary.
This commit will make it the last HathorSettings instantiated will be returned, as long as the source is the same, otherwise an exception is raised.
There is a little small caveat that is fixed in this commit is that in the YAML file could in theory be altered between different calls to HathorSettings, which would lead to different content being loaded silently. What happens now is that the first time it is loaded is what is used for …
> refactor(settings): make HathorSettings always return the same instance

- hathor/transaction/base_transaction.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/transaction_metadata.py
- hathor/transaction/validation_state.py
- tests/resources/transaction/test_tx.py
- tests/tx/test_cache_storage.py
- tests/tx/test_tx.py
- tests/tx/test_tx_storage.py
- tests/tx/test_validation_states.py
- tests/wallet/test_wallet.py
- tests/wallet/test_wallet_hd.py
- Move `ValidationState` class to its own file
Reason: cleaning up code to prepare for Transaction-related refactors
> refactor: move ValidationState to its own file

- hathor/client.py
- hathor/transaction/base_transaction.py
- hathor/transaction/block.py
- hathor/transaction/merge_mined_block.py
- hathor/transaction/token_creation_tx.py
- hathor/transaction/transaction.py
- tests/tx/test_tx.py
- tests/tx/test_tx_deserialization.py
- Change `TxVersion` enum so it fails instantiation for values larger than one byte, instead of ignoring it.
- Create new `signal_bits` attribute in `BaseTransaction`, derived from the first byte of the `version` field.
**ATTENTION**: this PR touches important parts of the code
> feat(feature-activation): implement signal_bits field in txs

- hathor/feature_activation/feature_service.py
- hathor/feature_activation/model/feature_description.py
- hathor/transaction/block.py
- tests/feature_activation/test_feature_service.py
- tests/tx/test_block.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/623
This is an exact copy of https://github.com/HathorNetwork/hathor-core/pull/613, since it was merged in the incorrect order and reverted.
- Implement `Block.get_feature_activation_bits()` method and tests
- Implement `FeatureService` class and tests
> feat(feature-activation): implement feature service

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- Remove deprecated `--x-fast-init-beta` CLI option
> chore: remove --x-fast-init-beta CLI option

- hathor/manager.py
- hathor/transaction/base_transaction.py
- hathor/transaction/transaction.py
- hathor/types.py
- hathor/util.py
1. Create the common Hathor types: `TxId`, `Address`, `TxOutputScript`, `Timestamp`, `TokenUid`, and `Amount`.
2. Refactor `hathor.manager`, `hathor.transaction.base_transaction`, and `hathor.transaction.transaction` as the initial refactor.
> refactor: Add common Hathor types

- tests/event/test_simulation.py
These flaky event tests have been failing a lot recently. So I think it's best to skip them for now while they are fixed in another PR.
1. Skip flaky event tests.
> tests: Skip flaky event tests

- hathor/simulator/simulator.py
1. Patch `BaseTransaction.resolve()` to prevent updating timestamp.
Notice that `BaseTransaction.resolve()` calls `BaseTransaction.start_mining()`, which updates the timestamp using `time.time()` if mining takes more than two seconds. This might be causing tests to randomly fail.
The reasons for tests to randomly fail is that `Transaction.start_mining()` is using `time.time()` to get the timestamp (instead of `reactor.seconds()`). As the reactor time is not related to the current timestamp, the transaction timestamp can be too much in the future raising a `InvalidNewTransaction` exception.
For more details, check out this part of the code: https://github.com/HathorNetwork/hathor-core/blob/master/hathor/manager.py#L976-L982
> fix(simulator): Patch BaseTransaction.resolve() to prevent updating timestamp

- hathor/cli/db_export.py
- hathor/cli/db_import.py
- hathor/indexes/manager.py
- hathor/indexes/partial_rocksdb_tips_index.py
- hathor/util.py
- Move `progress` function from `partial_rocksdb_tips_index.py` to `util.py`, making it generic
- Add ETA to `progress` function, solving TODO
> chore: improve progress function

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/indexes/manager.py
- hathor/metrics.py
- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/memory_storage.py
- hathor/transaction/storage/rocksdb_storage.py
- hathor/transaction/storage/transaction_storage.py
- tests/others/test_metrics.py
- tests/tx/test_cache_storage.py
- tests/tx/test_indexes4.py
- tests/tx/test_tx.py
- tests/tx/test_tx_storage.py
- tests/unittest.py
1. Build `IndexesManager` on builders.
2. Remove default value for `Metrics.tx_storage`.
> refactor(builder): Build IndexesManager on builders

- hathor/conf/unittests.py
- hathor/conf/unittests.yml
- hathor/feature_activation/feature_service.py
- hathor/transaction/base_transaction.py
- hathor/transaction/block.py
- hathor/transaction/transaction.py
- hathor/transaction/transaction_metadata.py
- hathor/utils/int.py
- tests/feature_activation/test_feature_service.py
- tests/resources/transaction/test_mining.py
- tests/tx/test_block.py
Implements the suggestion in https://github.com/HathorNetwork/hathor-core/pull/613#discussion_r1205747507
- Implement new `get_bit_list()` utils function
- Create new `TransactionMetadata.feature_activation_bit_counts` attribute
- Implement new `BaseTransaction.calculate_feature_activation_bit_counts()` abstract method and concrete implementations on `Block` and `Transaction`
- Add `feature_activation_bit_counts` to `BaseTransaction.get_metadata()` and `BaseTransaction.update_initial_metadata()`
- Update `FeatureService` to use the `feature_activation_bit_counts` metadata attribute instead of calculating the bit count itself
> feat(feature-activation): bit count optimization

- hathor/manager.py
1. Rename `HathorManager._initialize_components()` to `_initialize_components_full_verification()`.
2. Create method `HathorManager._verify_soft_voided_txs()`.
3. Use `HathorManager._sync_v2_resume_validations()` on `_initialize_components_full_verification`.
> refactor(init): Remove duplicate code and simplify full verification method

- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/storage/tx_allow_scope.py
- Refactor `TransactionStorage.allow_scope` to use getters/setters and have the actual value private;
- Make `TransactionCacheStorage` override the getters/setters so the external storage and internal storage have the same scope.
> fix(storage): incorrect validation store when using cache storage

- hathor/builder/builder.py
- hathor/builder/resources_builder.py
- hathor/cli/run_node.py
- hathor/feature_activation/feature_service.py
- hathor/feature_activation/model/criteria.py
- hathor/feature_activation/resources/feature.py
- hathor/transaction/block.py
- tests/feature_activation/test_feature_service.py
- tests/feature_activation/test_settings.py
- tests/others/test_cli_builder.py
- tests/resources/feature/test_feature.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/633
- Implement `GET /feature` endpoint
Resolves #632
> feat(feature-activation): implement get endpoint

- hathor/cli/db_export.py
- hathor/consensus/block_consensus.py
- hathor/consensus/consensus.py
- hathor/daa.py
- hathor/indexes/deps_index.py
- hathor/indexes/height_index.py
- hathor/indexes/utxo_index.py
- hathor/manager.py
- hathor/transaction/block.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/transaction.py
- hathor/transaction/transaction_metadata.py
- hathor/util.py
- hathor/wallet/base_wallet.py
- `height` metadata type should change from `int` to `Optional[int]`
- initial value should go from `0` to `None`
- any code accessing the `height` metadata directly should preferably use `Block.get_height` method (for both ensuring that the vertex in question is a block and asserting that it is not None)
> refactor: use None by default for height metadata

- hathor/cli/run_node.py
- Fix import order that was causing a settings initialization issue
> fix: settings initialization

- hathor/builder/cli_builder.py
- hathor/builder/resources_builder.py
- hathor/cli/db_export.py
- hathor/cli/db_import.py
- hathor/cli/quick_test.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/cli/shell.py
- tests/cli/test_db_export.py
- tests/cli/test_db_import.py
- tests/cli/test_quick_test.py
- tests/cli/test_run_node.py
- tests/cli/test_shell.py
- tests/others/test_cli_builder.py
- Implement new `from_namespace()` utils function to instantiate typed CLI args from `argparse.Namespace`
- Implement new `RunNodeArgs` named tuple to provide typed `run_node` CLI args
> refactor: implement typed RunNodeArgs

- hathor/p2p/manager.py
- hathor/p2p/sync_v1/agent.py
- hathor/p2p/sync_v1/downloader.py
- hathor/p2p/sync_v1/factory_v1_0.py
- hathor/p2p/sync_v1/factory_v1_1.py
- tests/p2p/test_sync.py
- move all modules related to sync-v1 into `hathor.p2p.sync_v1`
- do not change anything else
> refactor(sync): move sync-v1 files to a separate module

- tests/tx/test_tx.py
This test broke due to a regression after the latest on_new_tx refactor. However this test isn't actually adding anything right now. This should be reviewed in #648
- `test_checkpoint_validation` should be removed
- all tests should now pass on the CI run
> fix(tests): remove undeeded broken tests

- hathor/transaction/base_transaction.py
I noticed that many flaky tests fail with a "future transaction" exception, possibly caused by the `BaseTransaction.resolve()`. As this is used only for testing, we can safely change its behavior.
1. Stop updating time by default on `BaseTransaction.resolve()`.
> tests: Do not update time by default on BaseTransaction.resolve()

- hathor/builder/builder.py
- hathor/event/event_manager.py
- hathor/event/model/base_event.py
- hathor/event/model/event_data.py
- hathor/event/model/event_type.py
- hathor/event/websocket/factory.py
- hathor/event/websocket/protocol.py
- tests/event/event_simulation_tester.py
- tests/event/test_event_manager.py
- tests/event/test_event_reorg.py
- tests/event/test_event_simulation_responses.py
- tests/event/test_simulation.py
- tests/event/test_tx_metadata.py
- tests/event/websocket/test_protocol.py
- tests/unittest.py
- Add missing docstrings and typings
- Fix parsing bug in `EventData` and add tests for it
- Fix edge cases bugs in `EventWebsocketProtocol` and add tests for them
- Implement `BaseEventSimulationTester` to help writing event queue feature tests, and new tests using it
> fix(events): fix bugs in the event stream and improve tests

- hathor/builder/builder.py
- hathor/cli/run_node.py
- hathor/feature_activation/feature_service.py
- hathor/simulator/simulator.py
- hathor/transaction/storage/transaction_storage.py
- tests/feature_activation/test_feature_service.py
- tests/feature_activation/test_feature_simulation.py
- tests/simulation/test_trigger.py
- Optimize `FeatureService._get_ancestor_at_height()` by using the height index if the block is in the best blockchain.
- Implement `create_peer_artifacts()` method on simulator
- Implement `TransactionStorage.get_transaction_by_height()`
- Implement feature activation simulation test
> feat(feature-activation): implement block ancestor optimization

- hathor/transaction/base_transaction.py
- hathor/transaction/storage/transaction_storage.py
- use `None` instead of `0` in `BaseTransaction.get_metadata` when creating a new `TransactionMetadata`
- add validations to save/get on `TransactionStorage` so we make sure blocks always have a height when being saved
> fix(metadata): actually use None for unset height

- hathor/consensus/block_consensus.py
- hathor/consensus/transaction_consensus.py
- hathor/indexes/mempool_tips_index.py
- hathor/transaction/base_transaction.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/storage/traversal.py
- tests/tx/test_traversal.py
- `BFSWalk` should be renamed to `BFSTimestampWalk` to reflect that it prioritizes by timestamp
- add `BFSOrderWalk` which uses actual neighbor order to yield
> feat(traversal): add BFS order traversal

- hathor/feature_activation/feature_service.py
- hathor/transaction/block.py
- hathor/transaction/transaction_metadata.py
- tests/feature_activation/test_feature_service.py
- tests/feature_activation/test_feature_simulation.py
- Implement `TransactionMetadata.feature_states` attribute
- Implement `Block.get_feature_state()` and `Block.update_feature_state()` methods
- Implement feature state caching in `FeatureService` using block metadata
Resolves https://github.com/HathorNetwork/hathor-core/issues/630
> feat(feature-activation): implement caching mechanism

- hathor/feature_activation/feature_service.py
- hathor/manager.py
- hathor/mining/block_template.py
- hathor/simulator/miner/geometric_miner.py
- tests/feature_activation/test_feature_service.py
- tests/feature_activation/test_feature_simulation.py
- Add `signal_bits` to block templates
- Add `signal_bits` arg to miner simulator
- Change rule where an error would be raised if trying to retrieve a feature that is only defined in another network
- Add feature activation reorg test
Resolves #631
> tests(feature-activation): implement reorg test

- .github/PULL_REQUEST_TEMPLATE/feature_branch_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/release_candidate_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/release_pr_template.md
- .github/pull_request_template.md
- We should have multiple PR templates for the different kinds of PRs, as agreed in https://github.com/HathorNetwork/internal-issues/issues/151 (search for "PR templates")
- The solution is based on https://stackoverflow.com/a/75030350/3477266
> docs: add PR templates for the new release process

- .github/workflows/main.yml
- extras/github/docker.py
Update the soon to be deprecated `set-output` command ([reference](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/))
> chore: deprecate set output

- poetry.lock
- pyproject.toml
Update typing-related dependencies to increase robustness, especially `mypy-zope` that has reached `1.0.0`.
Note: `pydantic` has reached `2.0` but has breaking changes and requires a manual code migration, so I only updated it to `1.x.x`. I suggest we wait a few months before making the change, so more people are using it.
- Update `mypy`
- Update `mypy-zope`
- Update `pydantic`
> chore: update mypy, mypy-zope, and pydantic

- tests/pubsub/test_pubsub2.py
There were some untested PubSub use cases, so this PR implements them in preparation for https://github.com/HathorNetwork/hathor-core/pull/694, which changes the PubSub. This PR's objective is to cover changed behaviors in #694, so we can be sure it's changing what it should.
- Add new PubSub tests
> tests: implement new PubSub tests

- hathor/consensus/consensus.py
Bugfix triggered from artificial case.
- When a tx's voided-by includes a consensus-fail-id marker, the marker should not be treated as a tx-id.
> fix: consensus-fail-id marker should not be treated as a tx-id

- hathor/metrics.py
- hathor/p2p/manager.py
- hathor/pubsub.py
This PR is in preparation for PubSub changes in https://github.com/HathorNetwork/hathor-core/pull/694. The current implementation of the `test_p2p_network_events()` test,
https://github.com/HathorNetwork/hathor-core/blob/0dd129d904d9ad0625dec2c226b927b7b7ecd38d/tests/others/test_metrics.py#L68-L69
Tries to start a connection, which fails because the reactor used in tests (`Clock`) doesn't support TCP connections. This fail is expected and triggers the emission of the PubSub `NETWORK_PEER_CONNECTION_FAILURE` event, which is what triggers the `Metrics` update, making the test work.
In #694, the `Clock` is getting changed to a `MemoryReactorClock`, which does support TCP connections (but doesn't complete them), so the `NETWORK_PEER_CONNECTION_FAILURE` is not triggered.
We add an almost …
> chore: add peer connecting event

- hathor/consensus/consensus.py
- hathor/feature_activation/feature_service.py
- hathor/indexes/rocksdb_height_index.py
- hathor/manager.py
- hathor/p2p/sync_manager.py
- hathor/simulator/fake_connection.py
- hathor/simulator/trigger.py
- hathor/transaction/base_transaction.py
- hathor/transaction/block.py
- hathor/transaction/storage/rocksdb_storage.py
- hathor/transaction/storage/transaction_storage.py
- hathor/util.py
- tests/p2p/test_sync_rate_limiter.py
- tests/resources/p2p/test_healthcheck.py
- tests/resources/transaction/test_tx.py
- tests/simulation/test_simulator.py
- tests/tx/test_reward_lock.py
This PR contains refactors needed by sync v2. These changes DO NOT change any external behavior. They are mostly adjustments and fixes so tests can be easily adapted to run with sync v2.
1. Add asserts on `FeatureService` to gracefully fail and prevent infinite loop.
2. Fix scope verification on `TransactionStorage.get_all_transactions()`.
3. Assert that a transaction is fully validated on `ConsensusAlgorithm.update()`.
4. Fix `RocksDBHeightIndex._add()` method. It was wrongfully identifying a reorg when a reorg wasn't happening.
5. Prepare `HathorManager` to initialize with partial and invalid transactions stored in the database.
6. Add missing `@abstractmethod` decorators on `SyncManager`.
7. Improve simulator `FakeConnection` with an auto-reconnect feature.
8. Add …
> refactor: Prepare for sync-v2

- extras/custom_checks.sh
- hathor/cli/run_node_args.py
- hathor/consensus/consensus.py
- hathor/consensus/context.py
- hathor/event/websocket/factory.py
- hathor/indexes/memory_mempool_tips_index.py
- hathor/indexes/memory_tx_group_index.py
- hathor/indexes/mempool_tips_index.py
- hathor/indexes/tips_index.py
- hathor/transaction/storage/cache_storage.py
- hathor/websocket/protocol.py
I noticed some uses of `typing.Set` in the code, even after we removing those, because there's no linter it's very easy to forget we can use `set` instead.
- add custom linter script to check for deprecated uses of typing
> refactor: remove deprecated typing uses and add custom linter script

- extras/gen_release_candidate_changes.py
Getting the list of PRs to include in the release-candidate description was getting cumbersome and error prone.
- new script in `extras` that will generate a markdown list of PRs to be used when creating a new release-candidate
- script requires `gh` to be installed and authenticated in order to use Github's API
> chore(extras): script to generate list of PRs that master is ahead of rc

- hathor/cli/events_simulator/events_simulator.py
I noticed that the event simulator CLI tool was not working correctly due to some previous changes.
- Fix the event simulator CLI tool `--scenario` option parsing
> fix(event-queue): fix event simulator scenario parsing

- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/feature_activation/bit_signaling_service.py
- hathor/feature_activation/feature.py
- hathor/feature_activation/model/criteria.py
- hathor/feature_activation/model/feature_state.py
- tests/feature_activation/test_bit_signaling_service.py
This PR implements the `BitSignalingService` as defined in [this RFC](https://github.com/HathorNetwork/rfcs/blob/master/projects/feature-activation/0002-bit-signaling.md).
- Add `--signal-support` and `--signal-not-support` CLI options
- Add `Criteria.signal_support_by_default` attribute
- Add `FeatureState.get_signaling_states()` method
- Implement `BitSignalingService`
> feat(feature-activation): implement bit signaling service

- hathor/feature_activation/model/criteria.py
- hathor/feature_activation/resources/feature.py
- hathor/transaction/block.py
- hathor/utils/api.py
- tests/resources/feature/test_feature.py
- tests/tx/test_block.py
Implement a missing Feature Activation endpoint that will be required to implement the Explorer UIs described in [this RFC](https://github.com/HathorNetwork/rfcs/pull/60).
- Add support for `block` parameter on the `GET /feature` endpoint, returning feature information for a specific block
- Add `Block.get_feature_activation_bit_value()` method
- Improve typing of `QueryParams.from_request()` method
> feat(feature-activation): block features endpoint

- poetry.lock
- pyproject.toml
Fix the following warning when running tests:
```
../../***/lib/python3.11/site-packages/autobahn/twisted/resource.py:36: 10 warnings
/***/lib/python3.11/site-packages/autobahn/twisted/resource.py:36: DeprecationWarning: twisted.web.resource.NoResource was deprecated in Twisted 22.10.0: Use twisted.web.pages.notFound instead, which properly escapes HTML.
from twisted.web.resource import NoResource
```
- Update autobahn package to latest version
> chore: update autobahn package

- tests/p2p/test_protocol.py
The CI broke because a test was not passing after sync-v2 was merged.
- The `GET-BLOCK-TXS` command was removed, adapt test to use `GET-TRANSACTIONS-BFS` instead
> fix(test): regression after sync-v2 command was removed

- hathor/p2p/manager.py
- hathor/p2p/protocol.py
- hathor/p2p/resources/status.py
- hathor/p2p/states/ready.py
- hathor/p2p/sync_agent.py
- hathor/p2p/sync_factory.py
- hathor/p2p/sync_v1/agent.py
- hathor/p2p/sync_v1/factory_v1_0.py
- hathor/p2p/sync_v1/factory_v1_1.py
- hathor/p2p/sync_v2/factory.py
- hathor/p2p/sync_v2/manager.py
- hathor/p2p/sync_v2/mempool.py
- hathor/simulator/fake_connection.py
- tests/p2p/test_capabilities.py
- tests/p2p/test_split_brain.py
- tests/p2p/test_split_brain2.py
- tests/p2p/test_sync.py
- tests/p2p/test_sync_rate_limiter.py
- tests/p2p/test_sync_v2.py
We've been using the term "manager" for the class that deals with the sync from the point of view of an individual connection but we've already agreed to changing it to "agent" instead. This PR finishes the transition to this term.
- Use `sync_agent`/`SyncAgent*` instead of `sync_manager`/`SyncManager*` everywhere throughout the code.
> refactor(p2p): rename sync *manager* to sync *agent*

- hathor/p2p/sync_v2/manager.py
Simplify deferred-handling code by removing repetition and improving typing robustness.
- Remove usage of string keys for "singular" deferreds (`tips`, `best-block`, and `peer-block-hashes`), by using a specific, typed attribute for each of them, instead of storing them in a generic dictionary.
- By doing that, the deferreds dictionary is now only used for transactions, so it has been renamed and typed accordingly. The key type has also been changed to `VertexId`, so the `origin` is removed from it.
- Change `None` handling in `get_tx()` from `if/raise` to `assert`, as the typing guarantees `tx` will never be `None`.
> refactor(sync-v2): improve deferreds handling

- hathor/indexes/height_index.py
- hathor/indexes/memory_height_index.py
- hathor/indexes/rocksdb_height_index.py
- tests/tx/test_indexes.py
PR #686 needs this method
- Add new method to the height index that allows getting a list of blocks starting from the tip
> feat(indexes): add get_n_height_tips method to height index

- hathor/conf/settings.py
- hathor/p2p/states/peer_id.py
While sync-v2 is in beta it's better to keep using the whitelist until it is stable.
- Add a bool option to the settings to choose whether the peer whitelist should be considered for sync-v2 peers
> feat(p2p): add setting to enable/disable peer whitelist for sync-v2

- hathor/cli/openapi_files/register.py
- hathor/feature_activation/resources/feature.py
Currently, trying to access Feature Activation endpoints on our public nodes returns 403 Forbidden, like on https://node1.mainnet.hathor.network/v1a/feature. This PR updates the endpoint visibility so it can be used by the Hathor Explorer UIs.
- Change `GET /feature` visibility to public and add rate limits (the same used by `GET /transaction`)
> chore(feature-activation): update feature endpoint visibility to public

- hathor/transaction/aux_pow.py
Improve the error log of a merkle path length when it's higher than the maximum allowed.
- Change the log to include the merkle path length value.
> chore: improve merkle path log

- hathor/event/event_manager.py
- hathor/utils/iter.py
The previous code was consuming too much memory when loading events from an existing database.
- Create new `batch_iterator()` utils function that converts an iterator of items into an iterator of batches.
- Change `EventManager.handle_load_phase_vertices()` so it saves events to RocksDB in write batches of 10.000 events instead of a single batch with all events.
> fix(event-queue): improve memory usage during the load phase

- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/storage/tx_allow_scope.py
- tests/tx/test_tx.py
When testing sync-v2 on v0.55.0, one of the nodes got stuck in a particular situation logging this exception:
```
File "/usr/local/lib/python3.10/site-packages/hathor/p2p/sync_v2/manager.py", line 746, in handle_blocks
self.on_new_tx(blk, propagate_to_peers=False, quiet=True)
File "/usr/local/lib/python3.10/site-packages/hathor/p2p/sync_v2/manager.py", line 1137, in on_new_tx
if not self.manager.on_new_tx(tx):
File "/usr/local/lib/python3.10/site-packages/hathor/profiler/cpu.py", line 207, in _wrapper
ret = fn(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/hathor/manager.py", line 949, in on_new_tx
self.tx_storage.compare_bytes_with_local_tx(tx)
File "/usr/local/lib/python3.10/site-packages/hathor/transaction/storage/transaction_storage.py …
```
> fix(sync-v2): compare to local bytes broke in some cases

- hathor/simulator/fake_connection.py
- tests/simulation/test_simulator.py
This test became very flaky after the latest changes on sync-v2.
- The test should avoid building two chains with the same score
> fix(tests): make simulator test not flaky on sync-v2

- hathor/simulator/miner/geometric_miner.py
- hathor/simulator/trigger.py
- tests/feature_activation/test_mining_simulation.py
Due to the expected behavior of the `StopAfterNMinedBlocks` trigger, which is to stop the simulation after finding "at least N blocks", some tests were flaky. A new mechanism is introduced directly on the miner simulator to guarantee it stops producing blocks after exactly N blocks are found.
This new mechanism is used specifically in Feature Activation mining simulation tests, but any other tests that are found to be flaky because of this behavior, could be migrated to this alternative.
- Implement new `pause_after_exactly()` method for miner simulators
- Update Feature Activation mining simulation tests to use this new method
> chore: improve miner simulator flakiness

- hathor/cli/run_node.py
We want to remove support for Python 3.9 on hathor-core v0.57.0
- Print warning message when using Python-3.9, but do not alter any behavior.
> chore: add deprecation warning for Python 3.9

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/conf/testnet.py
- hathor/conf/testnet.yml
- hathor/feature_activation/settings.py
- hathor/manager.py
Use the Feature Activation for the first time for logging the state of features every time a block is accepted, as described in the Phased Testing RFC.
- Add `FeatureService` to `HathorManager`, and on `Builder` and `CliBuilder`
- Add `enable_usage` configuration for Feature Activation settings
- Add basic Feature Activation configuration on `testnet.yml` and `testnet.py`
- Add logging of NOP features states in `HathorManager`
> feat(feature-activation): add logging of NOP features

- hathor/cli/run_node.py
- hathor/sysctl/exception.py
- hathor/sysctl/factory.py
- hathor/sysctl/protocol.py
- hathor/sysctl/runner.py
- tests/sysctl/test_sysctl.py
Segregates the line parsing from the protocol.
- Extracts a SysctlRunner from SysctlProtocol
- Instantiates the SysctlRunner in the RunNode
- Passes the runner to the SysctlFactory
> refactor: extracts SysctlRunner from SysctlProtocol

- hathor/conf/testnet.py
- hathor/conf/testnet.yml
Depends on https://github.com/HathorNetwork/hathor-core/pull/760
Configure the NOP features in testnet according to the definition in the Phased Testing RFC.
- Configure NOP features in `testnet.yml` and `testnet.py`
> feat(feature-activation): configure NOP features on testnet

- hathor/cli/run_node.py
There's an incorrect import preventing full node initialization.
- Fix import
> fix: imports

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/consensus/consensus.py
- hathor/debug_resources.py
- hathor/p2p/sync_v1/agent.py
- hathor/p2p/sync_v2/streamers.py
- hathor/pubsub.py
- hathor/reactor/reactor.py
- hathor/reactor/reactor_core_protocol.py
- hathor/reactor/reactor_protocol.py
- hathor/reactor/reactor_tcp_protocol.py
- hathor/reactor/reactor_time_protocol.py
- hathor/simulator/clock.py
- hathor/simulator/simulator.py
- hathor/stratum/stratum.py
- hathor/transaction/block.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/transaction.py
- hathor/transaction/transaction_metadata.py
- hathor/util.py
- hathor/utils/zope.py
- tests/event/websocket/test_factory.py
- tests/others/test_metrics.py
- tests/p2p/test_connections.py
- tests/pubsub/test_pubsub2.py
- tests/test_memory_reactor_clock.py
- tests/unittest.py
This PR resolves https://github.com/HathorNetwork/hathor-core/issues/552. There are 3 goals:
1. Improve typing of code using Twisted reactors
2. Change tests to use a `MemoryReactorClock` instead of a `Clock`, so it's compatible with the reactor used in production (that is, it implements the `IReactorCore`, `IReactorTime`, and `IReactorTCP` Twisted interfaces. `Clock` only implements `IReactorTime`)
3. Remove PubSub support for reactors that don't implement `IReactorCore`
This was done by leveraging [Python protocols](https://peps.python.org/pep-0544/) to represent an intersection of Twisted interfaces, which allows us to better represent the reactor type. By doing this, we were able to change tests to use a reactor that is more similar to the one used in production, as previously we were …
> chore: improve pubsub

- hathor/simulator/miner/geometric_miner.py
- tests/feature_activation/test_mining_simulation.py
PR https://github.com/HathorNetwork/hathor-core/pull/753 introduced the new `pause_after_exactly()` miner simulator ability, and changed Feature Activation mining simulation tests to use it instead of the `StopAfterNMinedBlocks`, removing flakiness. Since the trigger was removed, the test running times were unnecessarily too long.
- Decrease running times of Feature Activation mining simulation tests
- Increase miner hash rate to make sure enough blocks are found
> tests: decrease tests duration

- hathor/conf/get_settings.py
- hathor/p2p/sync_v1/agent.py
- hathor/p2p/sync_v1/downloader.py
- hathor/p2p/sync_v2/agent.py
- hathor/p2p/utils.py
- hathor/prometheus.py
- hathor/simulator/fake_connection.py
- hathor/simulator/miner/geometric_miner.py
- hathor/simulator/simulator.py
- hathor/simulator/tx_generator.py
- hathor/stratum/stratum.py
- hathor/transaction/__init__.py
- hathor/transaction/base_transaction.py
- hathor/transaction/block.py
- hathor/transaction/token_creation_tx.py
- hathor/transaction/transaction.py
- tests/tx/test_tx.py
- tests/unittest.py
This PR is the first on of a series of PRs focused on improving settings handling in the project, aiming to remove "global settings" that often cause importing order problems and limit varying settings for tests.
Those improvements will be made in two phases:
1. Renaming the `HathorSettings()` function to `get_settings()` and removing all invocations from module-level, moving them to inside functions/methods. This will be done incrementally in multiple PRs, and this PR is part 1 of that.
2. Changing all usages of settings to use injection instead of direct access.
Eventually the objective is that `get_settings()` is only called once in the whole system, and then injected as arguments on all objects/functions that need it.
In this PR, changes are very simple, code is mostly just renamed …
> refactor: move get settings [part 1]

- hathor/cli/run_node.py
- hathor/p2p/resources/mining_info.py
- hathor/p2p/resources/status.py
- hathor/p2p/states/hello.py
- hathor/p2p/states/ready.py
- hathor/transaction/resources/dashboard.py
- hathor/transaction/resources/mempool.py
- hathor/transaction/resources/push_tx.py
- hathor/transaction/resources/transaction.py
- hathor/transaction/resources/utxo_search.py
- hathor/transaction/scripts.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/storage/tx_allow_scope.py
- hathor/transaction/util.py
- hathor/util.py
- hathor/version_resource.py
- hathor/wallet/resources/balance.py
- hathor/wallet/resources/thin_wallet/address_balance.py
- hathor/wallet/resources/thin_wallet/address_history.py
- hathor/wallet/resources/thin_wallet/address_search.py
- hathor/wallet/resources/thin_wallet/send_tokens.py
- hathor/wallet/resources/thin_wallet/token_history.py
- hathor/wallet/resources/thin_wallet/tokens.py
- hathor/wallet/util.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/768
Please read the description on https://github.com/HathorNetwork/hathor-core/pull/768, this PR is just a follow-up part.
- Remove some usages of `HathorSettings()` from the module level and move it to inside functions/methods
- For functions, the function just calls the new `get_settings()`
- For classes we set `self._settings = get_settings()` in the class' `__init__()`, and update all methods to use that new attribute
> refactor: move get settings [part 3]

- hathor/p2p/resources/status.py
- hathor/p2p/states/ready.py
- tests/p2p/test_protocol.py
RTT information was weak and almost useless because we kept only the latest sample and the minimum value since the connection has been established. Besides that, RTT information was subject to manipulation.
1. Add a salt to PING/PONG messages to prevent RTT manipulation.
2. Store the latest 200 samples for RTT.
3. Present the RTT samples in the `/v1a/status` API.
4. Keep compatibility with PING/PONG without salt.
5. Connections with older full nodes will not calculate rtt because they will lack the salt.
> feat(p2p): Add ping salt and improve rtt information

- hathor/builder/sysctl_builder.py
- hathor/cli/run_node.py
- hathor/sysctl/init_file_loader.py
- hathor/sysctl/runner.py
- tests/cli/test_sysctl_init.py
- tests/sysctl/test_sysctl.py
- Add `--sysctl-init-file` CLI command option that should use the sysctl subsystem to configure the node.
- The configuration file is a txt file with a simple key value pair scheme.
Closes:
- https://github.com/HathorNetwork/hathor-core/issues/684
- https://github.com/HathorNetwork/hathor-core/issues/685
> feat: add --sysctl-init-file as cli command option

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/manager.py
- hathor/p2p/sync_v2/agent.py
- hathor/transaction/base_transaction.py
- hathor/transaction/block.py
- hathor/transaction/token_creation_tx.py
- hathor/transaction/transaction.py
- hathor/verification/block_verification.py
- hathor/verification/token_creation_transaction_verification.py
- hathor/verification/transaction_verification.py
- hathor/verification/verification_service.py
- hathor/wallet/resources/send_tokens.py
- hathor/wallet/resources/thin_wallet/send_tokens.py
- tests/consensus/test_consensus.py
- tests/event/test_event_reorg.py
- tests/p2p/test_sync.py
- tests/p2p/test_sync_mempool.py
- tests/tx/test_blockchain.py
- tests/tx/test_indexes.py
- tests/tx/test_reward_lock.py
- tests/tx/test_tips.py
- tests/tx/test_tokens.py
- tests/tx/test_tx.py
- tests/tx/test_tx_storage.py
- tests/utils.py
- tests/wallet/test_balance_update.py
- tests/wallet/test_wallet.py
- tests/wallet/test_wallet_hd.py
This PR is the first one on a series of refactors related to vertex verification, aiming to move all verification related code out of model classes and to their own files, improving code modularity and enabling other future improvements related to injection of dependencies, patching, etc.
The 4 main entrypoint methods used for validation/verification (detailed below) were moved to a new class and modules. Now, instead of using inheritance, we implement concrete methods and functions that are explicit about from where each implementation is coming from. This also allows to remove unused arguments from method signatures, as they're not overrides of the same method anymore. Verification of each vertex type accepts a specific set of arguments. Other than this change of structure, no behavior …
> refactor(verification): move vertex verification to its own service

- hathor/mining/block_template.py
- tests/tx/test_mining.py
The `BlockTemplate.generate_minimally_valid_block()` method is not setting signal bits as it should.
- Add signal bits to minimally valid block template
> fix(feature-activation): add signal bits to minimally valid block

- .github/workflows/main.yml
CI was no longer uploading codecov after removing Python 3.9 support.
- Use Python 3.11 instead of 3.9 on reduced matrix (not directly related to codecov), and for uploading codecov report
> chore(ci): upload codecov results on Python 3.11 test job

- .codecov.yml
Codecov branch config has been wrong since we changed the default branch, this likely only affects coverage comparisons.
- Use `master` as codecov branch
> chore(ci): fix codecov main branch name

- hathor/builder/cli_builder.py
- hathor/conf/settings.py
- hathor/manager.py
- hathor/p2p/manager.py
The DNS bootstrap mechanism used to run only when there were no longer any connections, however it's better to run it periodically to pick up new DNS records.
- move `PeerDiscovery` object from `HathorManager` to `ConnectionsManager`
- add new settings `PEER_DISCOVERY_INTERVAL` with interval that discovery should run again
> feat(p2p): run periodic bootstrap discovery

- hathor/types.py
- hathor/wallet/base_wallet.py
- tests/wallet/test_balance_update.py
Utility method to be used on tests and simulations.
1. Add method `BaseWallet.get_balance_per_address()` that returns the balances grouped by addresses.
2. This method ignores locks and returns the total balance (available + locked).
> feat(wallet): Add BaseWallet.get_balance_per_address() method

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/manager.py
- tests/p2p/test_get_best_blockchain.py
Continuing with the settings-related refactors, this PR updates `HathorManager` so it starts using injected settings, instead of global. This refactor is necessary for the Feature Activation mandatory signaling implementation.
- Add `settings` attribute to `HathorManager`, removing the module level settings
- Move `DEFAULT_CAPABILITIES` from module level to `HathorManager.get_default_capabilities()`
- Update `Builder` and `CliBuilder` accordingly
> refactor(settings): change HathorManager to use injected settings

- hathor/p2p/sync_v2/streamers.py
Fix one of the conditions that makes the `tests/simulation/test_simulator.py::SyncV2RandomSimulatorTestCase::test_many_miners_since_beginning` flaky.
If we do not stop the streaming, the later call to `get_next_block_best_chain()` will raise an assertion error since the next block will be voided.
1. Stop streaming blocks if the current block gets voided.
> fix(sync-v2): Stop streaming if current block becomes voided

- hathor/p2p/manager.py
- tests/p2p/test_sync_rate_limiter.py
Fix flaky test `FAILED tests/p2p/test_sync_rate_limiter.py::SyncV1RandomSimulatorTestCase::test_sync_rate_limiter - twisted.trial.unittest.FailTest: 7 != 8`.
This test fails when there's a pending call to `send_tips()` after simulation.
1. Reset rate limit hit counter after simulation.
> test(sync-v1): Reset rate limit hit counter after simulation

- hathor/p2p/manager.py
- hathor/p2p/peer_id.py
- hathor/p2p/protocol.py
- hathor/p2p/resources/status.py
- hathor/p2p/states/ready.py
- hathor/p2p/sync_v1/agent.py
- tests/p2p/test_protocol.py
The full node currently relays only connections in the ready state. So, if a connection drops for just a few seconds, we might not relay this peer information to our neighbors.
The current behavior of the full node involves requesting peer information from a neighboring node exclusively during the initial connection establishment phase. Consequently, if the full node attempts to establish a connection with a peer and that peer rejects the connection, there is a risk that the full node will subsequently remove this peer from its peer storage. As a result, there would be no further attempts made to connect to this particular peer in the future.
1. Clean up aged peers in `ConnectionsManager.peer_storage`.
2. Add `PeerId.last_seen: float`.
3. Update `protocol.peer.last_seen` when the …
> feat(p2p): relay all recently-seen peers for neighbors

- hathor/simulator/fake_connection.py
- tests/simulation/test_simulator.py
The following tests were too flaky:
- `tests/simulation/test_simulator.py::SyncV1RandomSimulatorTestCase::test_many_miners_since_beginning`
- `tests/simulation/test_simulator.py::SyncV2RandomSimulatorTestCase::test_many_miners_since_beginning`
- `tests/simulation/test_simulator.py::SyncBridgeRandomSimulatorTestCase::test_many_miners_since_beginning`
This PR does not fix the `HeightIndex` behavior. It just fixes the test itself.
Before this fix, one of these tests were failing every 3 executions. After this fix, I could locally run each of the three tests more than 50 times with only one failure coming from some other edge case. For clarity, 1 fail out of 150+ executions.
The only fail I got happened with seed `4231149425068099915`. Here is the log: `FAILED …
> test(simulation): Fix flaky test test_many_miners_since_beginning

- tests/p2p/test_sync_enabled.py
The `test_sync_rotate()` had an assert with 0.0877% change of failing. As every CI job executes it 6 times, it had a change of 0.52% of failing, i.e., 1 out of 200 CI executions.
1. Modify `test_sync_rotate()` to reduce the chance of failing to 0.000483%, which reduces the chance of a CI failing from 0.52% to 0.00289797% (1 out of 35,000 CI executions).
> test(sync): Improve test_sync_rotate to prevent false positives

- .github/workflows/main.yml
Very often we will push a new commit to a PR (recent rebase or otherwise) while the CI is still running and will continue to run wasting CI time and jamming the jobs queue.
- Use [`cancel-in-progress`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run) config to automatically cancel workflow runs when a new one in the same "ref" (branch or tag) starts.
> chore(ci): use cancel-in-progress to prevent useless CI runs

- hathor/builder/resources_builder.py
- hathor/healthcheck/models.py
- hathor/healthcheck/resources/__init__.py
- hathor/healthcheck/resources/healthcheck.py
- hathor/manager.py
- hathor/p2p/resources/healthcheck.py
- tests/resources/healthcheck/test_healthcheck.py
We are building a new healthcheck standard
- Create a `/health` endpoint that will check the health of the p2p sync and return our new health check format
> feat[healthcheck]: new healthcheck response format

- tests/feature_activation/test_bit_signaling_service.py
The `test_non_signaling_features_warning()` test was flaky. This PR tries to fix this. Before, it used `capture_logs()` from `structlog`. I believe the flakiness reason was related to that (maybe because it's not thread-safe).
- Change `test_non_signaling_features_warning()` to use a standard mock instead of capturing logs.
> tests: fix flaky log test

- hathor/exception.py
- hathor/manager.py
- hathor/simulator/miner/geometric_miner.py
- tests/tx/test_mining.py
Some flaky tests using simulator were failing with the following error: `hathor.exception.InvalidNewTransaction: Ignoring transaction in the future`.
Why?
Because a miner was trying to push a block with a timestamp set too far in the future.
Why?
Because `HathorManager.generate_mining_block()` was returning a block template with an invalid timestamp.
Why?
After a chain of calls started by `Hathor.generate_mining_block()`, the method `_make_block_template()` was called. This method was not taking into consideration the `MAX_FUTURE_TIMESTAMP_ALLOWED` when calculating the maximum allowed timestamp.
1. Add the following exceptions: `BlockTemplateError` and `BlockTemplateTimestampError`.
2. Fix `HathorManager._make_block_template()` to take `MAX_FUTURE_TIMESTAMP_ALLOWED` into consideration …
> fix(mining): Fix block template not checking for MAX_FUTURE_TIMESTAMP_ALLOWED

- hathor/sysctl/runner.py
- tests/sysctl/test_runner.py
1. Fix `SysctlRunner.deserialize()` leveraging the JSON-deserializer.
> fix(sysctl): Fix deserializer

- hathor/manager.py
[PR #822](https://github.com/HathorNetwork/hathor-core/pull/822) was not enough to fix the flaky tests because the caller of `_make_block_template()` was sending the wrong `current_timestamp`.
1. Fix the calculation of `current_timestamp` in `HathorManager.make_block_template()`.
> fix(mining): Wrong timestamp sent to _make_block_template

- tests/tx/test_verification.py
Improve the reliability of the "move verification" refactors, starting from https://github.com/HathorNetwork/hathor-core/pull/797.
This PR aims to assert that each verification method is called when it is supposed to be called, specially considering the inheritance hierarchy of vertices. New tests are implemented for `verify_basic()`, `verify_without_storage()`, and `verify()`, for each one of the 4 vertex types, totaling 12 new tests.
For the root types `Block` and `Transaction`, the tests are straightforward. For the derived types `MergeMinedBlock` and `TokenCreationTransaction`, the tests are the same as for their parent types, but with the modification considering  their custom methods. The only modifications are the following:
- For `MergeMinedBlock`:
- The …
> tests(verification): implement tests to improve refactor reliability

- hathor/cli/mining.py
- hathor/stratum/stratum.py
- hathor/transaction/resources/create_tx.py
- hathor/verification/block_verifier.py
- hathor/verification/merge_mined_block_verifier.py
- hathor/verification/token_creation_transaction_verifier.py
- hathor/verification/transaction_verifier.py
- hathor/verification/verification_service.py
- hathor/verification/vertex_verifier.py
- tests/simulation/test_simulator.py
- tests/tx/test_genesis.py
- tests/tx/test_tx.py
- tests/tx/test_tx_deserialization.py
- tests/wallet/test_wallet_hd.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/796
This is the second PR in a 5-part series of PRs that completely move verification-related code out of the vertex model classes.
The objective in this PR is to copy all verification methods _signatures_ from the vertex model classes to each respective `Verifier` class. The new methods simply call the original methods, effectively providing a new interface for existing implementations.
By doing this, we can update all callers of any verification method to use the new `Verifier` methods, while not touching the original model classes. This is the scaffolding necessary to actually move method implementations in the following PRs.
- Copy all existing verification methods to each respective `Verifier` class. The implementation is …
> refactor(verification): move verification methods signatures [part 2/5]

- hathor/transaction/block.py
- hathor/transaction/merge_mined_block.py
- hathor/verification/block_verifier.py
- hathor/verification/merge_mined_block_verifier.py
- tests/tx/test_verification.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/797
This is the third PR in a 5-part series of PRs that completely move verification-related code out of the vertex model classes.
This PR moves the verification method implementations of the `Block` inheritance branch.
- Remove all `Block` and `MergeMinedBlock` verification methods from the original model classes, moving the implementation to each respective `Verifier` class. The only exception is the `verify_outputs()` method, which is part of the inheritance tree up to `BaseTransaction`, and will be moved in a separate PR.
> refactor(verification): move block-only verification methods [part 3/5]

- hathor/cli/mining.py
- hathor/transaction/token_creation_tx.py
- hathor/transaction/transaction.py
- hathor/verification/token_creation_transaction_verifier.py
- hathor/verification/transaction_verifier.py
- tests/tx/test_verification.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/798
This is the fourth PR in a 5-part series of PRs that completely move verification-related code out of the vertex model classes.
This PR moves the verification method implementations of the `Transaction` inheritance branch.
- Remove all `Transaction` and `TokenCreationTransaction` verification methods from the original model classes, moving the implementation to each respective `Verifier` class. The only exception is the `verify_outputs()` method, which is part of the inheritance tree up to `BaseTransaction`, and will be moved in a separate PR.
- `check_authorities_and_deposit()` is renamed to `verify_authorities_and_deposit()`, for consistency.
- `update_token_info_from_outputs()` is also moved as it's only used by …
> refactor(verification): move transaction-only verification methods [part 4/5]

- hathor/simulator/simulator.py
- hathor/simulator/verification.py
- hathor/transaction/base_transaction.py
- hathor/transaction/block.py
- hathor/transaction/transaction.py
- hathor/verification/block_verifier.py
- hathor/verification/transaction_verifier.py
- hathor/verification/vertex_verifier.py
- tests/tx/test_tx.py
- tests/tx/test_verification.py
- tests/wallet/test_wallet_hd.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/799
This is the last PR in a 5-part series of PRs that completely move verification-related code out of the vertex model classes.
This PR moves the verification method implementations of `BaseTransaction`, finishing the code migration. This also allows us to remove the `verify_pow()` simulator patch, as it can now be customized via injected verifiers.
- Remove all `BaseTransaction` verification methods from the original model classes, moving the implementation to the `VertexVerifier` class.
- Move each respective `verify_outputs()` implementation.
- Create custom `Simulator` verifiers such that `verify_pow()` is overridden.
- Update `Simulator` to use the custom verifiers, removing the `verify_pow()` patch.
> refactor(verification): finish moving all verification methods [part 5/5]

- hathor/p2p/sync_v2/agent.py
Sync-v2 streamer was sending more blocks than expected. Then, the peer was closing the connection causing tests to randomly fail. I haven't confirmed yet but I think this edge case happens when a reorg occurs during the sync.
1. Send the expected number of blocks to receive when requesting a streaming of blocks.
2. Fix streamer to follow the limit requested by the other peer.
> fix(sync-v2): Fix streamer sending more blocks than expected

- hathor/p2p/sync_v2/agent.py
- tests/p2p/test_get_best_blockchain.py
- tests/p2p/test_sync.py
- tests/simulation/test_simulator.py
- tests/unittest.py
Sync-v2 agent code uses the pair `(block_height, block_hash)` multiple times. So this PR refactors it to use a namedtuple `BlockInfo` (instead of handling with both information separately).
1. Add `hathor.p2p.sync_v2.agent.BlockInfo`.
2. Add `hathor.p2p.sync_v2.agent.NodeBlockSync.get_my_best_block()` method.
3. Refactor `find_best_common_block()` and `run_sync_blocks()` methds to use `BlockInfo`.
4. Rename variables `(synced, not_synced)` to `(lo, hi)` in the n-ary search.
5. There are two behavior changes in this PR: (i) change of keys in the `get_status()`, and (ii) using `lo=0` instead of `lo=self.synced_block.height`.
> refactor(sync-v2): Refactor sync_v2 agent to hold (block_height, block_id) information in an internal namedtuple

- hathor/feature_activation/bit_signaling_service.py
- hathor/manager.py
- hathor/transaction/storage/migrations/add_feature_activation_bit_counts_metadata.py
- hathor/transaction/storage/transaction_storage.py
During the latest release, we noticed that full node initialization could fail depending on the snapshot state (only on testnet). This was caused by a missing migration on the new Feature Activation metadata attribute.
- Rename `BitSignalingService.start()` to `generate_initial_logs()` and add docstring. Also move call to after migrations are applied in `HathorManager`.
- Implement `add_feature_activation_bit_counts_metadata` migration.
> fix(feature-activation): add missing metadata migration

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/feature_activation/feature_service.py
- hathor/simulator/simulator.py
- hathor/transaction/base_transaction.py
- hathor/transaction/block.py
- hathor/transaction/exceptions.py
- hathor/transaction/transaction_metadata.py
- hathor/verification/block_verifier.py
- hathor/verification/verification_service.py
- tests/feature_activation/test_feature_service.py
- tests/feature_activation/test_feature_simulation.py
- tests/resources/transaction/test_mining.py
- tests/tx/test_block.py
- tests/tx/test_verification.py
- tests/utils.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/800
Implement the mandatory signaling mechanism required by the Feature Activation process.
- Improvements in `Builder`:
- Add `FeatureService` to `BuildArtifacts`
- Change implementation of some `_get_or_create_*` methods so they can all be used without arguments.
- Change private `_get_or_create_settings()` and `_get_or_create_feature_service()` methods to public so they can be used externally (specifically, so the `Simulator` can properly customize the builder).
- Implement `FeatureService.check_must_signal()`.
- Fix problem in caching mechanism in `FeatureService.get_state()` caused by must signal verification.
- Remove the original `Block.get_feature_activation_bit_counts()`, and change …
> feat(feature-activation): implement must signal

- hathor/p2p/sync_v2/agent.py
- tests/p2p/test_sync_v2.py
The n-ary search executed by sync-v2 was not taking into consideration that a reorg might occur during the search as it runs multiple async queries on the connected peer.
1. Detect when a reorg occurs on the peer and stop the search. Notice that a new search will be executed on the next sync loop.
> fix(sync-v2): Fix n-ary search to handle reorgs during its execution

- extras/custom_checks.sh
If a file is open in vim, this skip wrongfully fails because the `.swp` file concatenate lines using a custom separator so the whole file is considered as in one line.
1. Use grep `-I` option to skip binary files.
> chore(custom_checks): Skip binary files when checking for deprecated typing

- hathor/p2p/sync_v2/agent.py
The previous organization of responsibilities within sync-v2's internal methods was ambiguous. This Pull Request enhances the clarity by:
1. Distinctly delineating each method's responsibilities.
2. Standardizing the point at which we determine if blocks are synchronized.
3. Designating a consistent time to ask the peer to transmit vertices in real-time.
This refactoring aims to streamline the process, reduce potential errors, and make the codebase more maintainable.
1. Change `find_best_common_block()` to just find the best common block. So it will not set sync state and update relay anymore.
4. Simplify logic to decide whether we have something to sync or not.
5. Move the logic to set sync state and to enable/disable real-time relay to the `run_sync_blocks()` method.
> feat(sync-v2): Improve sync-v2 reliability

- tests/p2p/test_protocol.py
- tests/unittest.py
The `run_to_completion()` method is designed to advance a test's clock until all scheduled calls are executed. This approach works well in isolation but presents issues in a simulation environment where multiple nodes share a single clock. 
The crux of the problem emerges when a new node is created in the middle of a simulation. The `create_peer()` method invokes the `run_to_completion()`, which causes an unintended ripple effect: while the intention is to execute delayed calls only for the newly created node, the shared clock architecture means that the delayed calls for *all* nodes get executed.
In essence, while `run_to_completion()` aims to streamline the handling of delayed calls, its current design inadvertently interferes with the natural flow of the simulation, especially when new …
> tests: Fix a flaky protocol test

- hathor/p2p/sync_v2/agent.py
- hathor/p2p/sync_v2/mempool.py
Previously, the `_run_sync()` method checked for ongoing mempool syncs or open streamings to prevent concurrent cycle runs. Despite the presence of the `_is_running: bool` flag, it was prematurely marked as `false` due to mempool syncs and streamings returning at the start, not the end, of their execution. This led to complexity and potential errors in `_run_sync()`. This PR streamlines this process for better clarity and reliability.
1. Create the deferred `_deferred_blockchain_streaming` when we request the peer to open a block streaming.
2. Resolve the `_deferred_blockchain_streaming` when the streaming ends.
3. Create the deferred `_deferred_transactions_streaming` when we request the peer to open a transactions streaming.
4. Resolve the `_deferred_transactions_streaming` when the …
> feat(sync-v2): Wait for sync internal methods to finish before initiating next syncing cycle

- hathor/p2p/sync_v2/agent.py
- hathor/p2p/sync_v2/blockchain_streaming_client.py
- hathor/p2p/sync_v2/exception.py
- hathor/p2p/sync_v2/payloads.py
- hathor/p2p/sync_v2/streamers.py
- hathor/p2p/sync_v2/transaction_streaming_client.py
- tests/p2p/test_protocol.py
- tests/p2p/test_sync_v2.py
Even though streaming servers were implemented on separated classes, the clients were intertwined within the sync agent.
1. Add `BlockchainStreamingClient` to handle blockchain streamings.
2. Add `TransactionStreamingClient` to handle transaction streamings.
3. Rename `until_first_block` to `last_block_hash` in GET-TRANSACTION-BFS message.
4. Add `first_block_hash` parameter to GET-TRANSACTION-BFS message.
5. Besides the changes in the GET-TRANSACTION-BFS, the changes in this PR can be considered a refactor and no other behavior should be changed.
6. Add pydantic models to GET-NEXT-BLOCKS, BEST-BLOCK and GET-TRANSACTIONS-BFS payloads.
> feat(sync-v2): Add both BlockchainStreamingClient and TransactionStreamingClient to manage streamings from the client side

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/events_simulator/scenario.py
- hathor/cli/mining.py
- hathor/daa.py
- hathor/manager.py
- hathor/p2p/resources/mining_info.py
- hathor/simulator/simulator.py
- hathor/simulator/tx_generator.py
- hathor/stratum/stratum.py
- hathor/transaction/resources/create_tx.py
- hathor/verification/block_verifier.py
- hathor/verification/transaction_verifier.py
- hathor/verification/verification_service.py
- hathor/verification/vertex_verifier.py
- hathor/wallet/resources/nano_contracts/execute.py
- hathor/wallet/resources/send_tokens.py
- hathor/wallet/resources/sign_tx.py
- tests/resources/wallet/test_thin_wallet.py
- tests/simulation/test_simulator.py
- tests/tx/test_block.py
- tests/tx/test_blockchain.py
- tests/tx/test_genesis.py
- tests/tx/test_tx.py
- tests/tx/test_tx_deserialization.py
- tests/unittest.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/800
This PR changes the DAA module so it stops depending on global settings, allowing its simulator patch to be removed.
- Move DAA functions to a new class with injected settings. No code logic should be changed.
- Remove `daa.MIN_BLOCK_WEIGHT` and `daa.AVG_TIME_BETWEEN_BLOCKS` global variables, moving them to the class instance.
- Add the new DAA class to be injected in `HathorManager`.
- Add the new DAA class to be injected in `VertexVerifiers`.
- Update `Builder` and `CliBuilder` accordingly.
- Update `Simulator` to use injected DAA class, removing the DAA simulator patch.
- Update all code using the `daa` module to use the DAA class.
> refactor(settings): change daa to use injected settings

- hathor/builder/cli_builder.py
- hathor/daa.py
- hathor/p2p/peer_id.py
- hathor/simulator/simulator.py
- tests/p2p/test_split_brain.py
- tests/resources/base_resource.py
- tests/resources/transaction/test_create_tx.py
- tests/resources/wallet/test_send_tokens.py
- tests/tx/test_blockchain.py
- tests/tx/test_cache_storage.py
- tests/tx/test_genesis.py
- tests/tx/test_tx.py
- tests/tx/test_tx_storage.py
- tests/unittest.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/801
This PR refactors the global daa `TEST_MODE`, allowing its simulator patch to be removed.
- Remove the global `daa.TEST_MODE` and `daa._set_test_mode()`, moving it to an attribute in the DAA class. Also, update respective usages.
- Create temporary DAA singleton to be used exclusively in the `PeerId` class. It should be removed in a future PR.
- Remove `_set_test_mode()` simulator patch.
> refactor(daa): remove global daa test mode

- hathor/manager.py
- hathor/transaction/base_transaction.py
- hathor/transaction/block.py
- hathor/transaction/merge_mined_block.py
- hathor/transaction/resources/create_tx.py
- hathor/transaction/token_creation_tx.py
- hathor/transaction/transaction.py
- hathor/verification/transaction_verifier.py
- hathor/verification/verification_service.py
- poetry.lock
- pyproject.toml
- tests/tx/test_verification.py
This PR is the first one in a series of 9 PRs that finishes the vertex verification refactors. The objective is to completely remove all inheritance from the verification process, removing implicit dependencies between verifiers, streamlining the verification process and improving clarity on the scope/origin of each verification method, all to improve code readability, maintainability, and patching (for the simulator).
This is done incrementally. In previous PRs, we moved the verification out of the model classes. Now, in this series, we'll first change inheritance to composition, and then completely remove the composition too, leaving each verifier with the least possible amount of dependencies.
Also, in this PR, we install the [typing_extensions](https://github.com/python/typing_extensio …
> refactor(verification): organization and typing improvements [part 1/9]

- hathor/p2p/sync_v2/agent.py
- hathor/p2p/sync_v2/blockchain_streaming_client.py
- hathor/p2p/sync_v2/streamers.py
- hathor/p2p/sync_v2/transaction_streaming_client.py
After running our latest QA, we noticed that the sync-v2 logging can be improved in a way that we don't get too many duplicated log messages but got enough messages to debug an issue.
1. Add `_HeightInfo.__str__()` because it is used by the log json serializer.
2. Only log "blocks are synced" and "nothing to sync because peer is behind me at the same best blockchain" when we transition from not synced to synced. So it stops logging duplicated messages all the time.
3. Improve other log levels and messages.
> feat(sync-v2): Improve overall logging

- hathor/p2p/sync_v2/streamers.py
An unhandled exception is raised by `current_block.get_next_block_best_chain()` when a reorg occurs during a streaming of transactions. This unhandled exception causes the `send_next()` to stop being called because it is not scheduled to run anymore, so the other peer stays hanging waiting for more transactions.
1. Check if block is still in the best blockchain before calling `get_next_block_best_chain()`. If not, stop the streaming.
2. Add a `safe_send_next()` that will either schedule the next call or stop the streaming.
3. Add `StreamEnd.INTERNAL_ERROR`.
> feat(sync-v2): Fix issue when a reorg occurs during a streaming of transactions

- hathor/p2p/sync_v2/agent.py
Sync-v2 might get stale if an unhandled exception occurs. Even though we want to learn about the issue to get it fixed, we also want the full node to recover from issues. So, this PR introduces a watchdog that closes the connection if the sync gets stale. The full node will automatically reconnect and try to sync again.
1. Add a watchdog that detects if the syncing is stale.
2. A sync is considered stale if a single loop has been running for more than 30 minutes.
> feat(sync-v2): Watchdog to detect stale syncing

- hathor/p2p/sync_v2/agent.py
The logic to decide whether we would relay real-time vertices to peer used by in the sender. But now we moved it to the client, which means each peer can independently decide whether they want to receive real-time vertices or not.
This PR removes an outdated condition that was preventing the peer to decide.
1. Remove `is_synced()` verification of `send_tx_to_peer_if_possible()`
> feat(sync-v2): Always relay vertices in real-time if the peer requested it

- hathor/verification/verification_service.py
- tests/tx/test_verification.py
In new sync-v2 sync flow, a node can receive a transaction that it already has, but the node might run `validate_basic` before processing the transaction. Before this PR running `validate_basic` on an existing and fully verified transaction would run the validation and _downgrade_ the validation state from FULL to BASIC.
- Adjust both `validate_basic` to skip the validation if the given transaction has already been validated at the same or higher validation level.
- ~Adjust both `validate_full` to skip the validation if the given transaction has already been validated at the same or higher validation level.~ Removed from this PR because it affects other tests which require changes to `HathorManager.on_new_tx` for a proper fix and this isn't needed for anything in sync-v2
> fix(verification): avoid validation downgrade by not running it twice

- hathor/p2p/sync_v2/transaction_streaming_client.py
The `first_block` issue caused us to not stop the streaming of transactions when an unexpected vertex is received. But it not necessary to do it anymore because the streamer server is handling this case.
1. Stop the streaming of transactions if an unexpected vertex is received.
> feat(sync-v2): Stop streaming of transactions if an unexpected vertex is received

- hathor/p2p/sync_v2/agent.py
- hathor/p2p/sync_v2/transaction_streaming_client.py
This PR enhances the `on_block_complete()` method, which initially processed transactions and added blocks to the DAG in a synchronous manner, thus occupying the event loop for the duration of this task. Due to the synchronous execution, the larger the transaction set, the longer the event loop was blocked, preventing the full node from attending to other critical operations like managing connections and processing API requests.
This PR transforms the method into an asynchronous operation. By doing so, after the addition of each transaction, control is yielded back to the event loop, allowing the full node to multitask effectively. This change is particularly beneficial during periods of heavy transaction processing, ensuring that node responsiveness and efficiency are maintained.
1. …
> refactor(sync-v2): Modify TransactionStreamingClient to process vertices asynchronously

- hathor/p2p/sync_v2/transaction_streaming_client.py
When syncing transactions, there was a valid case where a node would incorrectly raise `UnexpectedVertex` if a transaction was previously present in the database, which could happen from a different sync agent running.
- When considering the missing dependencies, remember the ones that already exist in the database and don't consider those unexpected.
> fix(sync-v2): do not consider existing vertex as unexpected

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/p2p/manager.py
- hathor/p2p/states/hello.py
- tests/others/test_cli_builder.py
- tests/p2p/test_sync.py
- tests/p2p/test_whitelist.py
- tests/unittest.py
This PR refactors internal code in order to make it easier to add sysctl controls for enabling and disabling specific sync versions.
- Refactor `ConnectionsManager` so that instead of having `enable_sync_v1` and `enable_sync_v2` it has "available sync versions" and "enabled sync versions". A sync version being available means that it can be enabled or disabled at runtime. This distinction is useful because there are init-time requirements for making specific sync versions available and it is practical to deal with these separately from whether a specific sync version is enabled or not.
- Make both sync-v1 and sync-v2 available by default, there's no CLI option to make them not available, CLI options only control whether they will be enabled, which can subsequently be controlled in …
> refactor(p2p): have two internal tiers for sync: available and enabled

- hathor/sysctl/p2p/manager.py
- tests/sysctl/test_p2p.py
If during the sync-v2 trial period we end up in a situation where sync-v2 fails to advance, working around this would require at the very least a node restart, but usually in practice a re-deploy. With this change it is now possible to enable sync-v1 and disable sync-v2 in runtime without restarting a node.
- Add sysctl controls `p2p.available_sync_versions` (readonly) and `p2p.enabled_sync_versions` (read-write)
> feat(sysctl): add controls for enabling/disabling sync versions

- hathor/p2p/sync_v2/agent.py
- hathor/p2p/sync_v2/streamers.py
Stream servers were being stopped in multiple places but sometimes without sending an end message or sending the wrong type of message.
1. Add `StreamEnd.PER_REQUEST`.
2. Introduce both `stop_tx_streaming_server()` and `stop_blk_streaming_server()` methods.
3. Update previous calls to `send_transactions_end()` to `stop_tx_streaming_server()`.
4. Update previous calls to `send_blocks_end()` to `stop_blk_streaming_server()`.
5. Fix internal errors in streamers always sending `BLOCKS-END` messages.
6. Fix `handle_get_transactions_bfs()` wrongfully sending `BLOCKS-END` message.
> fix(sync-v2): Fix stream end messages for both blockchains and transactions

- hathor/p2p/sync_v2/agent.py
- hathor/p2p/sync_v2/streamers.py
- hathor/p2p/sync_v2/transaction_streaming_client.py
Sync-v2 had some issues when syncing with multiple peers. It was causing some tests with three or more peers to be flaky. Notice that peers could still sync but it was taking longer because of the reconnections.
1. Fix `on_block_complete()` to handle vertices that already exists. It might happen because other peer had added these vertices before the current peer.
2. Fix `BlockchainStreamingServer.send_next()` which was sending one block more than the limit.
3. Fix `TransactionStreamingClient.process_tx()` which was not correctly handling dependencies that already exists in the storage. This condition might happen because of a resume or because other peer had added these dependencies before the current peer.
4. Always add vertex to `_existing_deps` if it already exists. This is necessary …
> fix(sync-v2): Fix issues caused by concurrent syncing peers

- hathor/p2p/sync_v2/agent.py
The `handle_get_peer_block_hashes()` method used to schedule a later call if one of the requested blocks was voided. This behavior was implemented due to issues in a previous implementation of the n-ary search. The current n-ary search implementation properly handles when a reorg occur during the search.
1. Stop scheduling a later call if a block is voided in `handle_get_peer_block_hashes()`.
2. If a voided block is found, skip it and all following blocks in the response of the `handle_get_peer_block_hashes()`. It's safe to do it because the n-ary search algorithm can handle empty responses.
3. It's safe to skip the first voided block and all following blocks because this method assumes the list of heights will be increasingly sorted so all following blocks must be voided too.
> feat(sync-v2): Stop running callLater when a block is voided in handle_get_peer_block_hashes()

- hathor/consensus/block_consensus.py
- tests/unittest.py
The `tests/simulation/test_simulator.py::SyncV2RandomSimulatorTestCase::test_many_miners_since_beginning` was flaky because of this issue.
When the consensus algorithm updates the `best_block_tips_cache`, it does not include the current block being evaluated. Notice that the current block is not part of the `heads`.
1. Include `block` to the list of best block tips used to update the `best_block_tips_cache`.
2. In the `assertTipsEqualSyncV2()`, we shouldn't assert `b1 == b2` because the height index keeps its previous entry when two or more blocks have the same score. So we can safely just check if `b1 in s1` and `b2 in s2`.
3. Notice that, when `len(s1) == len(s2) == 1`, checking if `b1 in s1` and `b2 in s2` is exactly the same as checking if `b1 == b2`.
> fix(storage): Fix wrong update to the best_block_tips_cache

- hathor/transaction/token_creation_tx.py
- hathor/verification/token_creation_transaction_verifier.py
- hathor/verification/transaction_verifier.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/830
Currently, `TokenCreationTransactionVerifier.verify_sum()` has duplicate code from `TransactionVerifier.verify_sum()`. This PR changes it so it calls the super method instead.
- Implement `TransactionVerifier.get_complete_token_info()` and update its `verify_sum()` to use it.
- Implement `TokenCreationTransaction.get_token_info_from_inputs()`, overriding the `Transaction` implementation.
- Update `TokenCreationTransaction.verify_sum()` to use the new `get_complete_token_info()`.
> refactor(verification): refactor verify_sum [part 2/9]

- hathor/transaction/token_creation_tx.py
- hathor/transaction/transaction.py
- hathor/verification/token_creation_transaction_verifier.py
- hathor/verification/transaction_verifier.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/831
During the verification refactors, some methods were moved from `Transaction` to `TransactionVerifier`. Now that the refactors are complete (with PRs still to be merged), it's clear that those methods should be indeed in `Transaction`, so they were moved back.
- Move `update_token_info_from_outputs()` from `TransactionVerifier` to `Transaction`, changing it to private.
- Move `get_complete_token_info()` from `TransactionVerifier` to `Transaction`. 
- Change `Transaction.get_token_info_from_inputs()` to private.
> refactor(verification): move token info [part 2b/9]

- hathor/conf/testnet.py
- hathor/conf/testnet.yml
- hathor/feature_activation/feature.py
- hathor/manager.py
Configure the new NOP features in testnet to restart the Phased Testing.
The start height is 3.386.880, which is 38.000 blocks from the current best height in testnet. This is equivalent to 13 days, meaning the Phase Testing should start around Dec 6th. We need to deploy this code before that.
- Configure new NOP features in `testnet.yml` and `testnet.py`.
- Update logging from old to new NOP features.
> feat(feature-activation): configure new NOP features on testnet

- hathor/verification/token_creation_transaction_verifier.py
- tests/tx/test_verification.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/858
Simplify `TokenCreationTransaction` verification to remove any calls to `super()`, as it's not necessary.
- Remove the `TokenCreationVerifier.verify_sum()` override, moving its only custom check to a new `verify_minted_tokens()`, which is now explicitly called in the `verify()` override.
- Add `verify_minted_tokens()` to `test_verification`.
> refactor(verification): implement verify_minted_tokens [part 3/9]

- hathor/p2p/sync_v2/transaction_streaming_client.py
During the QA of sync-v2 some errors were caught during a sync from scratch ([see here](https://github.com/HathorNetwork/internal-issues/issues/199#issuecomment-1808646707)). In particular this one:
```
2023-11-12 05:10:57 [warning  ] [hathor.p2p.protocol] send error                     msg=internal error peer_id=7181d23 remote=127.0.0.1:9001
2023-11-12 05:10:57 [error    ] [hathor.p2p.sync_v2.agent] unhandled exception            peer=7181d23
File "/Users/jan/Projects/hathor-core/hathor/p2p/sync_v2/agent.py", line 296, in run_sync
yield self._run_sync()
File "/Users/jan/Library/Caches/pypoetry/virtualenvs/hathor-JIQwCn9w-py3.11/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
result = context.run(
^^^^^^^^^^^^
File …
```
> fix(sync-v2): adjust init assertion

- hathor/simulator/trigger.py
- tests/simulation/test_trigger.py
This trigger gives control to stop the simulator when a given message is sent from one node to another.
1. Add `StopWhenSendLineMatch` trigger which monitors a connection and stops the simulator when a message matches a regex pattern.
> feat(simulator): Add StopWhenSendLineMatch trigger

- hathor/p2p/sync_v2/transaction_streaming_client.py
- tests/p2p/test_sync_v2.py
During the last QA when a node was syncing from scratch, we caught a case where more than one unexpected transaction was sent on a streamer, the first one correctly failed the streamer client, but the second one lead to an error because the deferred had already been called.
- Add test to reproduce the case;
- Make it so `TransactionStreamingClient.fails` will not call `self._deferred.errback` if the deferred has already been called.
> fix(sync-v2): stop _process_transaction on error

- hathor/cli/mining.py
- hathor/simulator/simulator.py
- hathor/verification/block_verifier.py
- hathor/verification/merge_mined_block_verifier.py
- hathor/verification/verification_service.py
- tests/tx/test_verification.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/832
Simplify block verification by removing the `BlockVerifier` inheritance from `MergeMinedBlockVerifier`, as it was not necessary.
To do that, the main verification "entrypoints" (`verify_basic()`, `verify()`, and `verify_without_storage()`) are moved to the `VerificationService`, making it a single source of verification definition for all vertex types (the same will be done for other types in the next PRs).
This also guarantees that it's not possible to call `BlockVerifier.verify()`  with a `MergeMinedBlock`, for example, which would be wrong. By using the single implementation from the `VerificationService`, we make sure the most specific verifier is called.
- Move `verify_basic()`, `verify()`, and …
> refactor(verification): remove BlockVerifier inheritance [part 4/9]

- hathor/transaction/scripts/execute.py
- hathor/transaction/scripts/opcode.py
- hathor/transaction/scripts/script_context.py
- tests/tx/test_scripts.py
Create the `ScriptContext` scaffolding that may be used by future opcodes.
- Create new, currently empty, `ScriptContext` class.
- Change function opcodes execution to use a new  `execute_op_code()`, that takes a `ScriptContext` as an argument.
- Remove unused arguments from all opcode functions.
> refactor(scripts): implement ScriptContext

- hathor/simulator/simulator.py
- hathor/verification/token_creation_transaction_verifier.py
- hathor/verification/transaction_verifier.py
- hathor/verification/verification_service.py
- tests/tx/test_verification.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/833
Simplify transaction verification by removing the `TransactionVerifier` inheritance from `TokenCreationTransactionVerifier`, as it was not necessary. It's changed to composition instead, but this is also going to be removed in a next PR.
For more info, read the previous PR (https://github.com/HathorNetwork/hathor-core/pull/833).
- Move `verify_basic()`, `verify()`, and `verify_without_storage()` from `TransactionVerifier` to `VerificationService`.
- Move `verify()` from `TokenCreationTransactionVerifier` to `VerificationService`, removing its `TransactionVerifier` inheritance, and changing it to composition instead.
- Update usages accordingly.
> refactor(verification): remove TransactionVerifier inheritance [part 5/9]

- hathor/p2p/manager.py
- hathor/p2p/peer_discovery.py
- hathor/p2p/peer_id.py
- hathor/p2p/protocol.py
- hathor/p2p/states/base.py
- hathor/p2p/states/peer_id.py
- hathor/p2p/utils.py
- tests/p2p/test_peer_id.py
While studying for another project, I found out that our version of Twisted actually supports using the `async/await` python syntax, and even recommends it ([docs](https://docs.twisted.org/en/twisted-22.10.0/core/howto/defer-intro.html#coroutines-with-async-await)):
> Unless your code supports Python 2 (and therefore needs compatibility with older versions of Twisted), writing coroutines with the functionality described in “Coroutines with async/await” is preferred over `inlineCallbacks`. Coroutines are supported by dedicated Python syntax, are compatible with `asyncio`, and provide higher performance.
This has multiple benefits, improving readability, static type checking, and may even boost performance, according to the docs above.
We should aim to gradually convert this code, where it …
> refactor(p2p): use async/await syntax on peer discovery

- hathor/verification/block_verifier.py
- hathor/verification/verification_service.py
- hathor/verification/vertex_verifiers.py
- tests/tx/test_block.py
- tests/tx/test_tx.py
- tests/tx/test_verification.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/835
Simplify code by removing the `VertexVerifier` composition from `BlockVerifier`.
- Remove `BlockVerifier.verify_outputs()`, moving its only custom verification to a new `verify_output_token_indexes()` method, and moving its call to `VerificationService._verify_without_storage_block()`. This allows us to remove the `VertexVerifier` composition from `BlockVerifier`.
- Update usages accordingly.
> refactor(verification): remove VertexVerifier from BlockVerifier [part 7/9]

- hathor/transaction/resources/create_tx.py
- hathor/verification/transaction_verifier.py
- hathor/verification/verification_service.py
- hathor/verification/vertex_verifiers.py
- tests/tx/test_tx.py
- tests/tx/test_verification.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/836
Simplify code by removing the `VertexVerifier` composition from `TransactionVerifier`.
- Remove `TransactionVerifier.verify_outputs()`, moving its only custom verification to a new `verify_output_token_indexes()` method, and moving its call to `VerificationService._verify_without_storage_tx()`. This allows us to remove the `VertexVerifier` composition from `TransactionVerifier`.
- Update usages accordingly.
> refactor(verification): remove VertexVerifier from TransactionVerifier [part 8/9]

- hathor/transaction/resources/create_tx.py
- hathor/verification/token_creation_transaction_verifier.py
- hathor/verification/transaction_verifier.py
- hathor/verification/verification_service.py
- tests/tx/test_tx.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/837
Remove unnecessary duplicate calculation of `token_info`, as requested in this comment: https://github.com/HathorNetwork/hathor-core/pull/831#discussion_r1379437477.
- Remove `TransactionVerifier.verify_sum()` as it only called `verify_authorities_and_deposit()`.
- Change `TokenCreationTransactionVerifier.verify_minted_tokens()` to receive a `token_dict`.
- Change `VerificationService._verify_tx()` and `_verify_token_creation_tx()` to prevent duplicate calculation of the `token_dict`.
> refactor(verification): remove token info duplication [part 9/9]

- hathor/cli/openapi_files/register.py
We need the `/health` endpoint to be included in the OpenAPI definitions that generate the Nginx config
- The Nginx config should contain the `/health` endpoint when generated
> fix: add health endpoint to openapi

- hathor/p2p/sync_v1/agent.py
Code is out of use since #886 
- Remove `SendDataPush` class, `send_data_queue` property and related code.
> feat(sync-v1): remove SendDataPush queue

- hathor/pubsub.py
- tests/pubsub/test_pubsub.py
In the sync-v1 process, there's a bottleneck occurring due to the differing speeds of data processing and data arrival. Firstly, the `sync_v1_agent.send_data_queue.priority_queue` is unable to process transactions as quickly as they arrive. This discrepancy results in the queue continuously expanding throughout the synchronization process, keeping references to `BaseTransaction` objects.
In addition, each set of blocks received by sync-v1 triggers approximately 200 events in the pubsub system. However, similar to the first issue, the event queue processes these transactions at a slower rate than their arrival rate. Consequently, this queue also grows continually during synchronization, maintaining references to `BaseTransaction` objects.
Both of these issues contribute to a critical …
> fix(pubsub): Event queue becoming too long

- extras/custom_checks.sh
- hathor/builder/cli_builder.py
- hathor/cli/db_import.py
- hathor/cli/events_simulator/event_forwarding_websocket_factory.py
- hathor/cli/events_simulator/event_forwarding_websocket_protocol.py
- hathor/cli/mining.py
- hathor/cli/multisig_spend.py
- hathor/cli/nginx_config.py
- hathor/cli/openapi_files/register.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/cli/twin_tx.py
Sometimes, when something is imported from the `hathor` module in an entrypoint file (from CLI commands), a circular import could happen, causing the full node node startup to fail. This has happened a couple times in the past ([example](https://github.com/HathorNetwork/hathor-core/pull/762)).
This problem would not be caught by our linters and neither tests, so it would only appear after the merge to `master`, when the docker image is generated. This PR aims to prevent this by adding a custom lint check that prohibits importing from `hathor` in the module-level of CLI entrypoints. For specific cases, a `# no-custom-check` comment can be added to opt-out of this check. [Here's an example](https://github.com/HathorNetwork/hathor-core/actions/runs/7121270335/job/19390180920?pr=887) of a …
> chore(custom-checks): add check to prevent circular imports

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/reactor/__init__.py
- hathor/reactor/reactor.py
- tests/conftest.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/888
Considering the general improvements we plan to make in the full node related to concurrent and parallel execution, using async/await and multiprocessing, it may be useful to interop with Python's native `asyncio`. Currently we used Twisted's default reactor, but they provide a reactor that has compatibility with asyncio: [AsyncioSelectorReactor](https://docs.twisted.org/en/stable/api/twisted.internet.asyncioreactor.AsyncioSelectorReactor.html). In theory, it is a drop-in replacement for what we're currently using.
This PR adds an experimental CLI option to enable this custom reactor, so we can test its usage in some full nodes for a while. Then, we'll have data to assess whether it's worth it using it as the default, in the …
> feat(reactor): implement option to use asyncio reactor

- hathor/p2p/sync_v2/transaction_streaming_client.py
During QA, a full node syncing from scratch got stuck with the following logs:
```
2023-12-20 22:26:29 [info     ] [hathor.p2p.sync_v2.agent] requesting blocks streaming    end_block=[4094036, "b'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01[\\xf20\\x82a\\x08\\x14\\xb2\\x83\\xe8\\x82\\xfc\\x8d*\\xe0f Ri6\\xb0@OS'"] peer=5a3040d quantity=424075 start_block=[3669962, "b'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x11\\x00\\xd7\\x93o\\xd9Y\\x02\\x0e\\x85\\xec\\xa6y*\\x0b7:LD;\\xa2\\xc2V\\x04'"]
2023-12-20 22:26:29 [info     ] [hathor.p2p.sync_v2.agent] requesting transactions streaming first_block=0000000000000062a0a3c362758d468f37692a14f1cf5cf2df2e08d5c92eab5a last_block=00000000000000005ea2ade4fdc528cd7ce5bb64bf942350e28c46aa8f79cf47 peer=5a3040d start_from=[]
2023-12-20 22:26:29 [info     ] …
```
> fix(sync-v2): Fix dependencies update for the first block

- hathor/conf/testnet.py
- hathor/conf/testnet.yml
- hathor/transaction/storage/migrations/remove_first_nop_features.py
- hathor/transaction/storage/transaction_storage.py
Clear all metadata related to the unused first Feature Activation Phased Testing.
- Remove NOP features from testnet config files.
- Add migration for cleaning first Phased Testing metadata.
> fix: remove unused NOP features

- hathor/manager.py
During the Feature Activation Phased Testing on testnet, we noticed that logs were missing the block hash, which makes it harder to search for specific logs.
- Add block hash to Feature Activation Phased Testing logs.
> chore(feature-activation): improve phased testing logs

- hathor/cli/events_simulator/events_simulator.py
- hathor/cli/stratum_mining.py
There was a regression in one of the latest refactors related to reactors. The `get` function is being called in CLI tools instead of the `initialize` one, which would be correct.
- Change `get_global_reactor()` to `initialize_global_reactor()` on CLI tools.
> fix(reactor): fix reactor initialization on CLI tools

- hathor/cli/events_simulator/event_forwarding_websocket_factory.py
- hathor/cli/events_simulator/events_simulator.py
- tests/cli/test_events_simulator.py
The events simulator CLI is not working.
- Fix import problem in events simulator CLI and add a test for it.
> fix(events): fix events simulator CLI

- tests/p2p/test_protocol.py
The test for maximum line length in the P2P protocol is not correctly testing what it is supposed to. Currently, it checks whether the protocol is disconnecting, which happens even if the payload is smaller than the max length. Also, the size of the test payload was way larger than the actual limit. We should test the edges, 1 byte short.
- Improve `test_invalid_size()`.
> tests(p2p): improve protocol test

- .github/workflows/docker.yml
- .github/workflows/main.yml
- hathor/event/storage/rocksdb_storage.py
- hathor/util.py
- poetry.lock
- pyproject.toml
This Python release is out, there may not be specific features motivating the upgrade, but it's generally good to ensure everything is working on that version before we decide to use it.
- Update CI to include Python 3.12
- Update packages directly (`pyproject.toml`) or indirectly (`poetry.lock`) as needed
- Avoid changes not needed to make it work
> chore: add support for Python 3.12

- hathor/conf/testnet.py
- hathor/conf/testnet.yml
- hathor/feature_activation/settings.py
Decrease the Feature Activation Evaluation Interval from 2 weeks to 1 week, to decrease the time to release new features.
- Change the default Feature Activation settings value of Evaluation Interval from 2 weeks to 1 week.
- Update the testnet Evaluation Interval value to keep it 2 weeks (this is necessary since we're currently running tests on testnet, but after that, we can also use 1 week for testnet).
> feat(feature-activation): decrease mainnet evaluation interval to 1 week

- hathor/p2p/manager.py
- tests/p2p/test_whitelist.py
There are some Twisted errors that are logged raw, causing each log line to become an alert in OpsGenie, as in this incident: https://github.com/HathorNetwork/on-call-incidents/issues/153.
After some investigation, the reason for this is not 100% clear, but there are some suspicions. This PR attempts to fix at least one case that would cause the problem. We've tested a full node running on mainnet for a few days, and by inspecting its logs, it looks like the error has improved.
- Remove custom timeout handling in `update_whitelist()` to use `Deferred.addTimeout()`.
- Move the `readBody()` call to be included in the timeout.
- Change `update_whitelist()` so the errback is after the callback, so the errback handles exceptions from the callback.
- Add unit tests for `update_whitelist()`, …
> fix(p2p): fix update whitelist handler

- hathor/conf/mainnet.py
- hathor/conf/mainnet.yml
Depends on https://github.com/HathorNetwork/hathor-core/pull/903
Configure NOP features for Feature Activation on mainnet, so we can test the process there, according to the Phased Testing plan.
- Enable Feature Activation usage on mainnet.
- Configure `NOP_FEATURE_1` and `NOP_FEATURE_2` on mainnet.
> feat(feature-activation): configure NOP features on mainnet

- hathor/conf/mainnet.py
- hathor/conf/mainnet.yml
The `start_height` of `NOP_FEATURE_2` is not correct.
- Fix the NOP features config on mainnet.
> feat(feature-activation): update NOP features config on mainnet

- hathor/cli/mining.py
- hathor/conf/mainnet.py
- hathor/conf/mainnet.yml
- hathor/conf/testnet.py
- hathor/conf/testnet.yml
- hathor/feature_activation/settings.py
- hathor/manager.py
- hathor/verification/block_verifier.py
- hathor/verification/vertex_verifiers.py
- tests/feature_activation/test_feature_simulation.py
- tests/tx/test_block.py
- tests/tx/test_genesis.py
- tests/tx/test_tx_deserialization.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/908
Since Feature Activation was enabled on mainnet on the previous PR, we can now remove the `enable_usage` setting, as its only purpose was making Feature Activation available on testnet but not mainnet.
- Make `FeatureService` mandatory on `VertexVerifiers`.
- Remove `enable_usage` property from Feature Activation settings, and update code accordingly.
> refactor(feature-activation): remove enable_usage

- hathor/daa.py
- hathor/manager.py
- hathor/reward_lock/__init__.py
- hathor/reward_lock/reward_lock.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/storage/vertex_storage_protocol.py
- hathor/transaction/transaction.py
- hathor/verification/transaction_verifier.py
To externalize storage dependencies from the verification process, we need to inject a storage into some methods used in verification, so it can either receive a `TransactionStorage` (rocksdb), or a simple memory storage that will be implemented in next PRs. To unify both of them in a single interface, a Python protocol is introduced, `StorageProtocol`.
- Create `StorageProtocol`, a protocol for unifying a subset of storage methods.
- Add methods to `TransactionStorage` so it conforms to the `StorageProtocol`.
- Update DAA so its calculation depends on a `StorageProtocol`, and update usages accordingly.
- Update Reward Lock `Transaction` methods so they depend on a `StorageProtocol`, and update usages accordingly.
> refactor(storage): create StorageProtocol

- hathor/feature_activation/feature_service.py
- tests/feature_activation/test_feature_service.py
- tests/feature_activation/test_feature_simulation.py
I noticed there was a bug in the `_get_ancestor_at_height()` method of Feature Activation. It receives a block and an ancestor height, and returns the ancestor block with that height. In current code, it checks whether the block is voided, and if it's not, it's in the best blockchain, so we can use the height index. Otherwise, it would iterate over all parents using `block.get_block_parent()`, which is less performatic than using the index.
The issue is that this method may be called _before_ the consensus runs for this block. This means that we do not know if the block is part of the best blockchain, and checking `not meta.voided_by` is wrong. This PR fixes this issue simply by forwarding the existing rule to the first parent block, which is guaranteed to have gone through the consensus …
> fix(feature-activation): fix get ancestor

- tests/cli/test_multisig_spend.py
- tests/cli/test_twin_tx.py
- tests/consensus/test_consensus.py
- tests/consensus/test_soft_voided.py
- tests/consensus/test_soft_voided2.py
- tests/consensus/test_soft_voided3.py
- tests/consensus/test_soft_voided4.py
- tests/crypto/test_util.py
- tests/event/test_event_reorg.py
- tests/feature_activation/test_feature_service.py
- tests/others/test_init_manager.py
- tests/p2p/test_capabilities.py
- tests/p2p/test_get_best_blockchain.py
- tests/p2p/test_peer_id.py
- tests/p2p/test_protocol.py
- tests/p2p/test_sync.py
- tests/p2p/test_sync_rate_limiter.py
- tests/p2p/test_sync_v2.py
- tests/resources/test_mining_info.py
- tests/resources/transaction/test_mempool.py
- tests/resources/transaction/test_pushtx.py
- tests/resources/transaction/test_utxo_search.py
- tests/test_memory_reactor_clock.py
Continue with settings refactors. Part 2 of https://github.com/HathorNetwork/hathor-core/pull/920.
- Remove some calls to `HathorSettings()`, changing them to `get_global_settings()`.
- Add `__test__ = False` to `TestMemoryReactorClock` as it was incorrectly being collected by pytest.
> refactor(settings): remove some more calls to HathorSettings

- hathor/conf/testnet.py
- hathor/conf/testnet.yml
- hathor/feature_activation/feature.py
- hathor/manager.py
- hathor/transaction/storage/migrations/remove_second_nop_features.py
- hathor/transaction/storage/transaction_storage.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/927
Clean up Phased Testing artifacts from testnet, so we can update its Evaluation Interval from 2 weeks to 1 week, making it the same as mainnet.
- Remove NOP feature configs from testnet config files.
- Update the testnet Evaluation Interval from 40320 to 20160 blocks (1 week), so it's the same as mainnet.
- Update the testnet default threshold to 15120 blocks (75% of the Evaluation Interval).
- Fix NOP feature logging in `HathorManager` to support mainnet features.
- Add a migration to clean testnet Phased Testing metadata.
> chore(feature-activation): phased testing adjustments

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
On the previous release sync-v2 was available as "experimental" and was marked as "unsafe", our tests showed it ran really well, so in this release it is being marked as "safe", making it more user friendly to enable.
- `--x-sync-v2-only` and `--x-sync-bridge` are still accepted but give a warning saying they're deprecated and will be removed in a later release (possibly `v0.60.0`)
- `--sync-v2-only` and `--sync-bridge` are added and have the same meaning as the `--x-*` variants.
- internally they are mutually exclusive flags also with the `--x-*` variants, meaning `--x-sync-v2-only` and `--sync-v2-only` can't be used at the same time, and as long as one of them is true, the value used is true
> feat(cli): mark sync-v2 parameters as safe and deprecate --x-* ones

- poetry.lock
- pyproject.toml
Hathorlib v0.5.2 has support for NanoContract transactions and this will be needed for the next PRs.
- Upgrade hathorlib to v0.5.2.
- All other packages should **NOT** be upgraded.
> chore(deps): Upgrade hathorlib to v0.5.2

- hathor/healthcheck/resources/healthcheck.py
- tests/resources/healthcheck/test_healthcheck.py
In case the `--x-asyncio-reactor` option was used to run hathor-core, we would get the following error when sending requests to `/v1a/health`:
```
File "/usr/local/lib/python3.10/site-packages/twisted/web/server.py", line 227, in process
self.render(resrc)
File "/usr/local/lib/python3.10/site-packages/twisted/web/server.py", line 292, in render
body = resrc.render(self)
File "/usr/local/lib/python3.10/site-packages/twisted/web/resource.py", line 268, in render
return m(request)
File "/usr/local/lib/python3.10/site-packages/hathor/healthcheck/resources/healthcheck.py", line 46, in render_GET
status = asyncio.get_event_loop().run_until_complete(healthcheck.run())
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 625, in run_until_complete …
```
> fix: health endpoint when using --x-asyncio-reactor

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- tests/others/test_cli_builder.py
It's getting harder to use sync-v1 in practice, might be time to switch the default to sync-v2.
- ~Remove `--sync-v2-only` since it hasn't been released yet~
- ~Add `--x-sync-v1-only`~
- Hide `--x-sync-2-only` (default) and `--x-sync-bridge` (already replaced by `--sync-bridge`)
- Refactor sync-choice logic to make it easier to understand
- Add more tests to cover all sync version parameters
> refactor(cli): improve handling of sync version from arguments

- hathor/p2p/sync_v2/agent.py
- hathor/p2p/sync_v2/mempool.py
The sync protocol handles the synchronization of the best blockchain and the mempool. Sync-v2 currently reports only the status of the best blockchain synchronization. This PR extends the status to report on the mempool synchronization.
Monitoring the mempool synchronization is relevant because it might impact the transaction confirmation by blocks. If a full node operated by a miner stops syncing the mempool for any reason, that miner will stop confirming transactions.
1. Add `sync_v2.agent.NodeBlockSync._synced_mempool: bool`.
2. Add the mempool sync status to the `sync_v2.agent.NodeBlockSync.get_status()`, including `is_sync: bool`, `tips_count: int`, `tips: list[VertexId]`, and `has_more: bool`.
3. Modify `SyncMempoolManager.run()` to resolve the deferred with a boolean.
4. Capture …
> feat(sync-v2): Add mempool sync status

- hathor/sysctl/p2p/manager.py
- hathor/sysctl/sysctl.py
- tests/sysctl/test_p2p.py
We currently do not have the capacity to kill connections from sysctl. The only alternative is to kill all connections using SIGUSR1.
1. Add `p2p.kill_connection` to sysctl. The expected behavior is to kill a connection with a given peer-id or to kill all connections if the provided peer-id is "*".
> feat(sysctl): Add p2p.kill_connection to sysctl

- hathor/builder/sysctl_builder.py
- hathor/manager.py
- hathor/sysctl/core/__init__.py
- hathor/sysctl/core/manager.py
- tests/sysctl/test_core.py
We currently must use an HTTP API to start and stop a global profiler. Such an API might not be accessible due to networking issues so having the ability to do it through sysctl becomes relevant.
1. Create commands `core.profiler.status`, `core.profiler.start`, and `core.profiler.stop` in sysctl.
2. Add `HathorManagerSysctl` which handles all these commands.
3. Add `HathorManager.is_profiler_running` to keep track whether the profiler is running or not.
4. Add `HathorManager.profiler_last_start_time` to be able to calculate how long the profiler has been running.
> feat(sysctl): Add core module with profiler commands to sysctl

- hathor/cli/run_node.py
- hathor/sysctl/p2p/manager.py
- hathor/sysctl/runner.py
- hathor/sysctl/sysctl.py
- tests/sysctl/test_p2p.py
- tests/sysctl/test_sysctl.py
- tests/sysctl/test_websocket.py
Sometimes the CPU is so high that sysctl become irresponsive. So this PR adds another method to send command to sysctl.
1. Handle SIGUSR2 on cli `run_node`.
2. Create a named pipe to receive a list of sysctl commands, one per line.
3. Execute the sysctl commands and log their results.
4. The named pipe will be created at the data directory if it exists. Otherwise, a temporary folder will be created.
5. Add decorator `@signal_handler_safe` to mark setters as safe to be executed during a signal handling.
6. Add `require_signal_handler_safe: bool = False` to the `SysctlRunner.run()` method.
7. Rename `_get_getter()` and `_set_setter()` to `get_getter()` and `set_setter()` on `Sysctl`.
8. Rename `set()` to `unsafe_set()` on `Sysctl`. It also updates the docstring to explain that it is unsafe …
> feat(cli): Use SIGUSR2 to run sysctl commands

- tests/sysctl/test_core.py
CI broke after #951 but the fix is trivial.
- Use `unsafe_set` (renamed method) instead of `set` (old method)
- All tests should pass
> fix: test broke after #951

- hathor/cli/run_node.py
macOS has a different behavior when handling named pipes created by `mkfifo`.
In macOS, if a fifo is opened for reading, the `open()` call will block if there are no writers—that is, if somebody else does not have the fifo open for writing.
In Linux, the `open()` call is not blocking so the previous code worked fine and logged the fifo path as expected.
1. Move out the `open()` call from `temp_fifo()`.
2. Run the `open()` after logging the fifo path.
> fix(cli): Fix issue when running sysctl through USR2 in macOS

- hathor/sysctl/core/manager.py
Being able to stop the event loop for debugging is useful to get a better understanding of issues. This PR introduces two different sysctl commands: (i) pudb and (ii) ipython.
The pudb commands is a full-screen console debugger that allows us to run step-by-step and inspect the stack trace and its local variables. The event loop will be paused during its execution.
The ipython command will pause the event loop and open an ipython console so we can inspect the objects internal state and call methods.
In both cases, the event loop is resumed after the debugging is finished. But it's important to highlight that these tools might crash the full node so we should avoid using it on production.
These are experimental tools that will probably be improved in future PRs.
1. Add command …
> feat(sysctl): Add sysctl tools for debugging

- hathor/conf/mainnet.py
- hathor/conf/mainnet.yml
Since the miners did not update their nodes for the last test, we have to introduce new NOP features to test that bit signaling is working correctly.
The features are configured to start in approximately 1 week from now, and the voting period will last for 10 weeks, giving enough time for miners to udpate.
- Configure NOP features for a new Feature Activation test on mainnet.
> feat(feature-activation): configure new NOP features on mainnet

- hathor/consensus/transaction_consensus.py
We got this issue during the QA of hathor-core v0.59.0-rc1. This is triggered when a node does a sync from scratch using sync-v2 and, later on, switches to sync-v1. The sync-v1 works properly but the processing of some transactions get considerably slower.
Fixes https://github.com/HathorNetwork/internal-issues/issues/246.
1. Stop marking transactions confirmed by the best blockchain as voided during conflict resolution. Notice that this edge case only occurs when the conflicting transaction is soft voided and is confirmed by the best blockchain.
> fix: Fix slow tx processing on some edge cases

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- tests/others/test_cli_builder.py
The current default of only enabling `sync-v1` is proving to be taxing on CPU, while `sync-v2` has been running very well on tests and seems stable enough. Defaulting to bridge mode allows for the best connectivity (connecting to updated and outdated nodes) and will gradually and naturally improve along with nodes being updated.
- Add new cli option `--x-sync-v1-only`
- Make the default be sync bridge (sync-v1 and sync-v2 enabled)
- Tweak some warnings accordingly
- Adapt tests to the new defaults and the new cli option
> chore(cli): make sync-bridge the default

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/conf/mainnet.py
- hathor/conf/mainnet.yml
- hathor/consensus/transaction_consensus.py
- hathor/sysctl/core/manager.py
- tests/others/test_cli_builder.py
> Release-candidate v0.59.0-rc.3

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/consensus/consensus.py
- hathor/event/event_manager.py
- hathor/event/model/event_type.py
- hathor/execution_manager.py
- hathor/manager.py
- hathor/transaction/storage/transaction_storage.py
- tests/consensus/test_consensus.py
- tests/execution_manager/test_execution_manager.py
Currently, when an exception happens during a consensus update, it marks the tx as voided with a custom marker and continues to operate. This operation may be faulty, though, as the database is likely in an undesired state. For example, if such exception happens when a block is received, no following block will be accepted and the full node will not be able to sync anymore. If the full node is manually stopped and restarted, it starts up but continues to be unable to sync.
This PR's goal is to, instead, completely halt and exit the full node in those cases, forcing manual intervention. When some exception happens during a consensus update, the full node process exits with a non-zero exit code. This also guarantees that the database is marked as corrupted, so the full node cannot be …
> feat(unrecoverable-error): implement halting of full node execution

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/main.py
- hathor/cli/reset_feature_settings.py
- hathor/feature_activation/bit_signaling_service.py
- hathor/feature_activation/feature.py
- hathor/feature_activation/settings.py
- hathor/feature_activation/storage/feature_activation_storage.py
- tests/feature_activation/test_bit_signaling_service.py
- tests/feature_activation/test_settings.py
- tests/others/test_metrics.py
This PR implements a validation that compares the Feature Activation settings from the configuration file, against the previous value that is stored in the database. This runs during full node initialization and is just to prevent human errors when editing those files, since one cannot remove or change existing features from there.
- Create new `FeatureActivationStorage` that validates configured feature activation settings against the previous value from the database.
- Add new `reset-feature-settings` CLI tool for erasing saved feature settings.
> feat(feature-activation): add feature settings validation

- hathor/indexes/memory_tx_group_index.py
`MemoryTxGroupIndex._get_sorted_from_key()` is returning transactions in the wrong order. The correct order is sorted by (timestamp, hash) but it is actually only sorting by hash.
1. Replace `set[bytes]` to `set[tuple[int, bytes]]` so we can simply sort before returning the results.
2. Fix `_get_sorted_from_key()` sorting the tuple but returning only the hashes.
> fix(indexes): Fix wrong order in MemoryTxGroupIndex

- hathor/transaction/base_transaction.py
- hathor/transaction/token_creation_tx.py
- hathor/transaction/transaction.py
- tests/utils.py
Currently, the `BaseTransaction.hash` property is of type `Optional[bytes]`, which is pretty inconvenient considering the hash has (and should have) a value most times. For that, we have to use asserts in multiple places to guarantee the value is not `None`.
This PR renames the existing optional property to `_hash`, creating a new calculated `hash` property that performs the assert for us. By doing it like this, every place that already uses the existing `hash` property will continue to work (only a few places that rely on the possibility of the value being `None` had to be updated).
- Rename current optional `BaseTransaction.hash` property to `_hash` and add new non-null `hash` property.
- Remove some unnecessary asserts.
> refactor: create non-null hash property

- hathor/indexes/address_index.py
- hathor/indexes/memory_address_index.py
- hathor/indexes/memory_tx_group_index.py
- hathor/indexes/rocksdb_address_index.py
- hathor/indexes/rocksdb_tx_group_index.py
- hathor/indexes/tx_group_index.py
- hathor/wallet/resources/thin_wallet/address_history.py
- tests/tx/test_indexes.py
We had some users with wallets that had many transactions in single addresses, then the API request `address_history` got really slow.
More details [here](https://github.com/HathorNetwork/internal-issues/issues/256)
- Add parameter in the `get_sorted_from_key` method of tx group index to find the first tx to return the iterator from.
- Refactor address history API to remove O(n) operation and use rocksdb tree to find tx with hash and improve performance.
> refactor(indexes): Optimize RocksDBAddressIndex to handle pagination in O(log n)

- hathor/simulator/tx_generator.py
- pyproject.toml
- tests/consensus/test_consensus.py
- tests/consensus/test_consensus2.py
- tests/consensus/test_consensus3.py
- tests/consensus/test_consensus4.py
- tests/consensus/test_consensus5.py
- tests/consensus/test_soft_voided.py
- tests/consensus/test_soft_voided2.py
- tests/consensus/test_soft_voided3.py
- tests/consensus/test_soft_voided4.py
- tests/crypto/test_util.py
- tests/event/test_base_event.py
- tests/event/test_event_manager.py
- tests/event/test_event_reorg.py
- tests/event/test_event_simulation_scenarios.py
- tests/event/test_event_storage.py
- tests/event/websocket/test_factory.py
- tests/event/websocket/test_protocol.py
- tests/feature_activation/test_bit_signaling_service.py
- tests/feature_activation/test_criteria.py
- tests/feature_activation/test_settings.py
- tests/pubsub/test_pubsub.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/969
This PR continues to improve the strictness of mypy in test modules. For more info see the previous PR, https://github.com/HathorNetwork/hathor-core/pull/969.
- Add stricter mypy rules to some test modules and update them to conform.
> refactor(mypy): add stricter rules to some test modules [part II/VI]

- hathor/profiler/resources/cpu_profiler.py
When going through the docs with @BrunoCampana we noticed that this endpoint wasn't showing up on the docs.
- The correct endpoint for the "top API" (cpu profiler) is `/top` and the OpenAPI should use that, `/profiler` is used by a different endpoint and using it causes one to overshadow the other.
> docs: fix OpenAPI url of cpu profiler endpoint

- hathor/util.py
When testing #938 I got a division by zero error. I haven't debugged if the situation is realistic, but either way it seems to be better to handle the case where the denominator is 0.
- Handle the case where `progress_ == 0` by simply doing `remaining_time = '?'`
> fix(util): division by zero when logging progress in some cases

- hathor/manager.py
- hathor/transaction/storage/transaction_storage.py
- pyproject.toml
- tests/p2p/netfilter/test_factory.py
- tests/p2p/netfilter/test_match.py
- tests/p2p/netfilter/test_match_remote.py
- tests/p2p/netfilter/test_tables.py
- tests/p2p/netfilter/test_utils.py
- tests/p2p/test_capabilities.py
- tests/p2p/test_connections.py
- tests/p2p/test_double_spending.py
- tests/p2p/test_get_best_blockchain.py
- tests/p2p/test_peer_id.py
- tests/p2p/test_protocol.py
- tests/p2p/test_rate_limiter.py
- tests/p2p/test_split_brain.py
- tests/p2p/test_split_brain2.py
- tests/p2p/test_sync.py
- tests/p2p/test_sync_bridge.py
- tests/p2p/test_sync_enabled.py
- tests/p2p/test_sync_mempool.py
- tests/p2p/test_sync_rate_limiter.py
- tests/p2p/test_sync_v2.py
- tests/p2p/test_twin_tx.py
- tests/p2p/test_whitelist.py
- tests/unittest.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/972
This PR continues to improve the strictness of mypy in test modules. For more info see the first PR in this series, https://github.com/HathorNetwork/hathor-core/pull/969.
- Add stricter mypy rules to `tests.p2p` module and update it to conform.
> refactor(mypy): add stricter rules to p2p tests [part IV/VI]

- hathor/daa.py
- hathor/transaction/base_transaction.py
- hathor/transaction/storage/simple_memory_storage.py
- hathor/verification/block_verifier.py
- tests/tx/test_genesis.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/909
Change the DAA so it does not access the storage directly. Instead, block verification can pass pre-fetched dependencies through a new `SimpleMemoryStorage`. This will be useful for Multiprocess Verification.
- Create new `SimpleMemoryStorage` class that will be used for storing pre-fetched verification dependencies in memory.
- Change DAA methods `calculate_block_difficulty` and `calculate_next_weight` to accept a `SimpleMemoryStorage`, which is used to retrieve pre-fetched parent blocks.
- Update block's `verify_weight` to pre-fetch DAA dependencies.
> refactor(daa): externalize block dependencies

- pyproject.toml
- tests/p2p/test_double_spending.py
- tests/tx/test_indexes2.py
- tests/unittest.py
- tests/utils.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/973
This PR continues to improve the strictness of mypy in test modules. For more info see the first PR in this series, https://github.com/HathorNetwork/hathor-core/pull/969.
- Add stricter mypy rules to `tests.unittest` and `tests.utils` modules and update them to conform.
> refactor(mypy): add stricter rules to unittest and utils [part V/VI]

- hathor/p2p/sync_v1/agent.py
- hathor/p2p/sync_v1/downloader.py
The `failed to download tx` alerts currently spams our on-call engineer unnecessarily. There are two places where this can happen, and both generate alerts for different reasons ([1a](https://hathor.app.opsgenie.com/alert/detail/594a1544-4d01-422f-ac7a-f6093fd4b673-1709097028412/details), [1b](https://hathor.app.opsgenie.com/alert/detail/5c023dab-27e7-46a7-89fd-c6f4f691410e-1709061530497/details), [1c](https://hathor.app.opsgenie.com/alert/detail/1d427242-fe89-451a-a699-edabbb228030-1708976131712/details) and [2a](https://hathor.app.opsgenie.com/alert/detail/a0a6691b-4da0-45b9-a6bb-e814e409c07f-1709097027440/details), [2b](https://hathor.app.opsgenie.com/alert/detail/af4cb3ed-1486-4d7d-b2b4-8bfb6b261bfd-1709075260033/details)).
This PR prevents alerts caused by Twisted's `CancelledError` …
> fix: improve unnecessary alerts

- pyproject.toml
- tests/consensus/test_consensus3.py
- tests/event/test_event_simulation_responses.py
- tests/feature_activation/test_feature_simulation.py
- tests/feature_activation/test_mining_simulation.py
- tests/feature_activation/test_settings.py
- tests/p2p/test_get_best_blockchain.py
- tests/p2p/test_protocol.py
- tests/p2p/test_split_brain.py
- tests/p2p/test_sync.py
- tests/p2p/test_sync_mempool.py
- tests/pubsub/test_pubsub2.py
- tests/resources/healthcheck/test_healthcheck.py
- tests/unittest.py
- tests/utils.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/974
This PR continues to improve the strictness of mypy in test modules. For more info see the first PR in this series, https://github.com/HathorNetwork/hathor-core/pull/969.
- Unify the custom mypy override sections into a single one by updating test modules accordingly.
> refactor(mypy): unify hathor and test modules strictness [part VI/VI]

- tests/tx/test_verification.py
I noticed some verification tests were incorrect by a missing assertion.
- Fix wrong Mock used in assertions from `verify_pow_wrapped` to `verify_aux_pow_wrapped`.
> tests(verification): add missing assertions

- hathor/builder/builder.py
- hathor/builder/sysctl_builder.py
- hathor/cli/run_node.py
- hathor/feature_activation/bit_signaling_service.py
- hathor/sysctl/__init__.py
- hathor/sysctl/feature_activation/manager.py
- tests/sysctl/test_feature_activation.py
Add sysctl commands to control Feature Activation bit signaling without having to restart the full node (previously, this was only available through CLI options). The commands are the following:
Return features that are explicitly enabled. Read-only.
Return features that are explicitly disabled. Read-only.
Return which feature are currently in a signaling phase. Read-only.
Add support for a feature. Write-only.
Remove support for a feature. Write-only.
```bash
$ nc -U /tmp/hathor.sock
core.features.signaling_features
["NOP_FEATURE_5"]
core.features.remove_support="NOP_FEATURE_5"
core.features.not_supported_features
["NOP_FEATURE_5"]
core.features.supported_features
[]
core.features.add_support="NOP_FEATURE_5"
core.features.not_support_features
[]
core.features.supported_features …
```
> feat(feature-activation): implement bit signaling sysctl

- hathor/wallet/resources/thin_wallet/address_history.py
- tests/resources/wallet/test_thin_wallet.py
We deprecated the `address_history` API without `paginate=true` parameter on March 2020 (https://github.com/HathorNetwork/hathor-core/commit/a8ae6d86be8a04aaf8a7aae9b5ead1272303cad7). This API has low performance for addresses with many transactions and that's why it was deprecated. 
After many years, we are removing it to prevent someone from using it by mistake and consuming the full node's CPU.
- Remove deprecated method resource from `address_history` API.
> refactor: remove deprecated resource method from address history API

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/conf/settings.py
- hathor/manager.py
- hathor/p2p/manager.py
- hathor/p2p/peer_id.py
- hathor/p2p/sync_v2/agent.py
- hathor/p2p/utils.py
- hathor/simulator/tx_generator.py
- hathor/sysctl/p2p/manager.py
- hathor/transaction/aux_pow.py
- hathor/util.py
- tests/p2p/test_sync_v2.py
Implement ability to update the full node public IP while the sync is running, as requested in the issue: resolves https://github.com/HathorNetwork/internal-issues/issues/261.
Here are the new ways of interacting with entrypoints and the hostname:
Get and manually set the full node's hostname. Entrypoints will automatically reflect this change, and connections will be reset.
Automatically set the hostname to an auto discovered one. Entrypoints will automatically reflect this change, and connections will be reset.
Reload the `peer_id.json` file, replacing the entrypoints list with the new one. Then, connections will be reset.
This is just a shortcut to the sysctl `reload_entrypoints_and_connections` command.
- Remove `CliBuilder.create_peer_id()` and add `PeerId.create_from_json_path()`.
- …
> feat(p2p): add ability to update peer_id.json with SIGUSR1

- hathor/execution_manager.py
The sorting of `ExecutionManager` callbacks would fail for callbacks with the same priority, as the `Callable`s in the second sorting field are not orderable.
- Fix sorting of `ExecutionManager` callbacks.
> fix: sorting execution manager callbacks

- .github/workflows/main.yml
Codecov's upload task on CI broke, it used to be unstable so we suspected that was the case but apparently it is now required to use a token.
- Add a secret token to the repo's settings
- Add CI config to expose the token to codecov's upload task
> chore: fix codecov coverage upload

- hathor/p2p/peer_id.py
There is a bug in the `p2p.reload_entrypoints_and_connections` sysctl command, because the `PeerId.source_file` is not being set.
- Set missing `PeerId.source_file` property.
> fix: missing PeerId.source_file

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/db_import.py
- hathor/cli/run_node.py
- hathor/manager.py
- hathor/p2p/sync_v1/agent.py
- hathor/vertex_handler/__init__.py
- hathor/vertex_handler/vertex_handler.py
- tests/unittest.py
Move all `HathorManager.on_new_tx()` related code to its own new class, `VertexHandler`, improving organization and modularization, and as a prerequisite for the upcoming changes related to multiprocess verification.
- Move `HathorManager.on_new_tx()` implementation to new `VertexHandler`, along with other methods used only by it.
- Everything should be moved as-is, no behavior should change. The only exception is that the `conn` and `skip_block_weight_verification` arguments were removed, since they were not used.
- Keep `HathorManager.on_new_tx()` with a call to `VertexHandler.on_new_tx()`, compatibility with current code.
- Update `Builder` and `CliBuilder` accordingly.
- Fix `TestBuilder._get_reactor()` (it was not persisting the newly created reactor instance).
> refactor: create VertexHandler [part 1/2]

- hathor/transaction/base_transaction.py
- hathor/transaction/resources/dashboard.py
- hathor/transaction/resources/transaction.py
- hathor/wallet/resources/thin_wallet/address_history.py
- hathor/wallet/resources/thin_wallet/token_history.py
Wallet Mobile needs the ability to show a nano contract transaction "status" in the token's transaction details modal, but this "status" requires to know if a nano contract transaction was already confirmed by a block of not, thus the `first_block` as a first citizen of a transaction.
- It should add `first_block` to the `to_json_extended` to BaseTransaction for transactions.
- It should update documentation in the following resources:
- `/dashboard_tx`
- `/transaction`
- `/thin_wallet/address_history`
- `/thin_wallet/token_history`
> feat: add first_block to the to_json_extended method of base transaction class

- hathor/manager.py
- hathor/vertex_handler/vertex_handler.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/987
Modularize `on_new_tx()` as a prerequisite for the upcoming changes related to multiprocess verification, in order to create a new aysnc `on_new_tx()` (we should be able to duplicate the method without copying all code).
- Rename `VertexHandler.on_new_tx()` to `on_new_vertex()`.
- Break `on_new_vertex()` into modularized methods, `_validate_vertex()`, `_save_and_run_consensus()`, and `_post_consensus()` (renamed from `tx_fully_validated()`).
- No behavior should change, only a couple unnecessary assertions were removed.
> refactor(vertex-handler): modularize methods [part 2/2]

- hathor/consensus/transaction_consensus.py
- hathor/manager.py
- hathor/reward_lock/reward_lock.py
- hathor/simulator/utils.py
- hathor/transaction/base_transaction.py
- hathor/transaction/storage/transaction_storage.py
- hathor/verification/transaction_verifier.py
- hathor/vertex_handler/vertex_handler.py
- hathor/wallet/resources/send_tokens.py
- hathor/wallet/resources/thin_wallet/send_tokens.py
- tests/consensus/test_consensus.py
- tests/event/test_event_reorg.py
- tests/feature_activation/test_feature_simulation.py
- tests/p2p/test_sync.py
- tests/p2p/test_sync_mempool.py
- tests/p2p/test_sync_v2.py
- tests/resources/transaction/test_mining.py
- tests/tx/test_blockchain.py
- tests/tx/test_indexes.py
- tests/tx/test_reward_lock.py
- tests/tx/test_tips.py
- tests/tx/test_tokens.py
- tests/tx/test_tx.py
- tests/tx/test_tx_storage.py
- tests/tx/test_verification.py
- tests/utils.py
- tests/wallet/test_balance_update.py
- tests/wallet/test_wallet.py
Reorganize the `min_height` verification.
- Improve modularization of methods related to `min_height` verification.
> refactor(verification): reorganize min_height verification

- hathor/builder/cli_builder.py
- tests/others/test_cli_builder.py
As part of the sync-v2 roll out process we should have a release where sync-v1 is not enabled by default but is still fully supported.
- Change the default behavior from having both sync-v1 and sync-v2 enabled to having only sync-v2 enabled but still allow sync-v1 to be enabled at runtime by default.
> chore(cli): default to sync-v1 disabled

- hathor/builder/__init__.py
- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- tests/simulation/base.py
- tests/simulation/test_simulator_itself.py
- tests/unittest.py
In preparation to phase-out sync-v1, we would benefit from having a method for starting the node without sync-v1 indexes. This PR does not go into the details of which index is used, it only makes it possible to start with a node where sync-v1 is "not available" as opposed to just "disabled"; "not available" means it cannot be enabled in runtime.
- Refactor the builder/cli to make it clear to understand how each sync protocol is enabled or made available
- Add `--x-remove-sync-v1` CLI option to make sync-v1 unavailable from the start
> feat(cli): add argument to make sync-v1 unavailable

- hathor/vertex_handler/vertex_handler.py
Correctly handle exceptions raised by `update_reward_lock_metadata()`.
- Move `update_reward_lock_metadata()` call to inside the `validate_full()` try block.
> fix: catch update_reward_lock_metadata exceptions

- hathor/conf/mainnet.py
- hathor/conf/mainnet.yml
We're ready to introduce this upgrade on the mainnet.
- Set up the max-merkle-path increase on the mainnet
> feat(merged-mining): configure new max merkle path length on mainnet

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/vertex_handler/vertex_handler.py
We faced some difficulties replicating issue reports from developers. So this PR introduces a parameter to make replication easier just by sharing the full node log with us.
- Add the `--log-vertex-bytes` parameter in the run_node cli.
- Add the `VertexHandler._log_vertex_bytes: bool` which defaults to false.
- Log the transaction bytes when this new option is enabled.
> feat(cli): Add --log-vertex-bytes for debugging

- hathor/cli/load_from_logs.py
- hathor/cli/main.py
This new command makes it easier to replay logs generated using `--log-vertex-bytes` (https://github.com/HathorNetwork/hathor-core/pull/1033).
I initially thought that we could replay even the timestamp by using a custom reactor and getting a tighter control of the time. But it was not needed yet for my debugging so I decided to postpone it to another PR.
1. Add command `load_from_logs` that loads blocks and transactions as they are found in a log dump generated using `--log-vertex-bytes`. All vertices are processed in the same order as they appear in the log file.
2. The full node exits after the replay is complete.
3. All arguments from `run_node` are available so one can configure the environment where the replay will take place. A new required argument `--log-dump` was added to get …
> feat(cli): Add load_from_logs cli command to load blocks and transactions as they are found in a log dump

- hathor/wallet/resources/thin_wallet/address_history.py
- tests/resources/base_resource.py
- tests/resources/wallet/test_thin_wallet.py
After the release o v0.60.0 [a bug was reported](https://github.com/HathorNetwork/on-call-incidents/issues/173) in the address-history API. The bug was introduced after the optimizations in #978, reverting the PR makes the bug disappear.
- Restore the correct behavior without undoing the optimizations
- Add a test that reproduces the issue
> fix(resources): regression in address history endpoint

- hathor/vertex_handler/vertex_handler.py
Now that the Feature Activation Phased Testing has ended, we can remove some extra logs. Feature states are now logged together with the existing new block log. There's a small performance gain for removing the overhead of doubling logs.
- Remove feature activation specific logging methods and move logging of feature states to `_log_new_object()`.
> chore: clean up feature activation logs

- hathor/cli/util.py
This PR contains 2 separate but related fixes that will improve our on-call overhead. They would cause some errors to be logged in multiple unstructured lines, generating several unnecessary alerts.
The first problem was that a bug in string formatting would generate an exception during log event processing, triggering the "error when logging event" path. The second problem was with the logging of this error itself, that was using print statements, and therefore generating the multiple unstructured lines.
This finally resolves https://github.com/HathorNetwork/on-call-incidents/issues/153.
- Fix incorrect string formatting that caused a `KeyError` to be raised during logging.
- Remove `print()` statements when errors occur during logging.
> fix(log): correctly handle errors when logging events

- hathor/p2p/resources/add_peers.py
There is a bug in the add peers API after a refactor to use `async/await` syntax. This PR fixes it.
- Add a fire and forget mechanism to the coroutine in the add peers API.
> fix: add peers api

- hathor/p2p/peer_discovery/__init__.py
- hathor/p2p/peer_discovery/bootstrap.py
- hathor/p2p/peer_discovery/dns.py
- hathor/p2p/peer_discovery/peer_discovery.py
The `hathor.p2p.peer_discovery` module aggregates the abstraction and implementations, it could be split to make future implementations cleaner to review.
- Split `hathor.p2p.peer_discovery` into the following submodules: `peer_discovery` (abstraction), `dns` (DNS implementation), `bootstrap` (bootstrap implementation), expose everything the same way they were being exposed before.
> refactor(p2p): split hathor.p2p.peer_discovery into separate modules

- hathor/cli/main.py
- hathor/cli/quick_test.py
- hathor/cli/run_node.py
- hathor/cli/side_dag.py
- hathor/cli/util.py
- pyproject.toml
- tests/cli/test_side_dag.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1040
Implement a new `side_dag` CLI command that is able to run two independent full nodes, each in its own separate process. The command accepts the same options as the `run_node` command, however options can be duplicate with a `--side-dag` prefix. Each full node is configured with the respective set of options. Processes are automatically terminated when one of the full nodes exits.
Here's an example on how this command could be used:
```bash
$ python -m hathor side_dag
--testnet
--procname-prefix testnet-
--memory-storage
--disable-logs
--side-dag-config-yaml ./my-side-dag.yml
--side-dag-procname-prefix my-side-dag-
--side-dag-memory-storage
--side-dag-json-logs
```
- Implement new `cli.util.process_logging_options()`.
- …
> feat(side-dag): implement side_dag CLI command

- hathor/cli/generate_poa_keys.py
- hathor/cli/main.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1039
Implement a new CLI command to generate private/public keys to be used in Proof-of-Authority signing. 
- Implement `gen_poa_keys` CLI command.
> feat(side-dag): implement gen_keys CLI command

- hathor/stratum/stratum.py
We're receiving some calls to the stratum API with wrong arguments, but current code doesn't allow us to investigate it. This PRs adds logs that will help debugging this. See https://github.com/HathorNetwork/on-call-incidents/issues/176.
- Add logs and try to convert stratum `params` to a `dict`.
> fix: improve stratum logs

- SECURITY.md
Update the "security" document link to point to the new security page on the main Hathor Network website.
Updated link from:
https://docs.hathor.network/references/besides-documentation#security
To:
https://hathor.network/bug-bounty/
> docs(security): update link to bug bounty program

- hathor/consensus/block_consensus.py
- hathor/consensus/context.py
- hathor/consensus/transaction_consensus.py
- hathor/profiler/cpu.py
- hathor/reactor/reactor.py
- hathor/transaction/block.py
- hathor/transaction/transaction.py
The `get_cpu_profiler()` function which is called at the module-level in multiple places indirectly installed the Twisted reactor by calling `LoopingCall()`. This meant that when a module with a profiler was imported before reactor initialization (in `initialize_global_reactor`), a `ReactorAlreadyInstalledError` could be thrown.
This PR prevents the profiler from indirectly installing a reactor before it has been initialized.
- Change `SimpleCPUProfiler` so it does not create a `LoopingCall` in its `__init__`.
- Remove some unused calls to `get_cpu_profiler()`.
> fix: profiler reactor initialization

- hathor/cli/side_dag.py
- tests/cli/test_side_dag.py
The new `run_node_with_side_dag` command timed out in 10 seconds if the Hathor node did not start. This was incorrect because when loading from an existing storage, the Hathor node will always take more than 10 seconds to initialize.
This PR removes the timeout and simply waits indefinitely until the Hathor node is either ready or errored. This will be further improved when the monitor process is implemented (see https://github.com/HathorNetwork/hathor-core/issues/1051).
- Remove Hathor node init timeout in favor of waiting.
> fix(side-dag): remove init timeout

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/memory_storage.py
- hathor/transaction/storage/rocksdb_storage.py
- hathor/transaction/storage/transaction_storage.py
- tests/consensus/test_consensus.py
- tests/others/test_init_manager.py
- tests/others/test_metrics.py
- tests/tx/test_accumulated_weight.py
- tests/tx/test_block.py
- tests/tx/test_blockchain.py
- tests/tx/test_genesis.py
- tests/tx/test_indexes.py
- tests/tx/test_indexes4.py
- tests/tx/test_mining.py
- tests/tx/test_reward_lock.py
- tests/tx/test_scripts.py
- tests/tx/test_stratum.py
Continue improving settings management by removing calls to global settings.
- Update storage classes to use injected settings instead of the global one.
> refactor(storage): change storages to use injected settings

- hathor/builder/cli_builder.py
- hathor/cli/generate_genesis.py
- hathor/cli/main.py
- hathor/cli/run_node.py
- hathor/cli/side_dag.py
- hathor/consensus/consensus_settings.py
- hathor/consensus/poa/__init__.py
- hathor/consensus/poa/poa.py
- hathor/consensus/poa/poa_block_producer.py
- hathor/consensus/poa/poa_signer.py
- hathor/manager.py
- hathor/merged_mining/coordinator.py
- hathor/mining/block_template.py
- hathor/transaction/poa/poa_block.py
- hathor/verification/poa_block_verifier.py
- tests/others/test_hathor_settings.py
- tests/tx/test_block.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1060
Finish the Proof-of-Authority side-dag implementation by implementing the `PoaBlockProducer` which is analogous to a mining service, in the full node itself.
- Implement `poa` module and `PoaBlockProducer`.
- Implement `gen_genesis` CLI command.
> feat(side-dag): implement PoaBlockProducer

- hathor/builder/builder.py
- hathor/indexes/base_index.py
- hathor/indexes/manager.py
- hathor/indexes/memory_height_index.py
- hathor/transaction/base_transaction.py
- hathor/transaction/block.py
- hathor/transaction/merge_mined_block.py
- hathor/transaction/poa/poa_block.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/token_creation_tx.py
- hathor/transaction/transaction.py
- hathor/transaction/transaction_metadata.py
- hathor/transaction/util.py
- hathor/verification/transaction_verifier.py
- tests/tx/test_tokens.py
- tests/utils.py
Continue refactoring `HathorSettings` usages to use an injected instance rather than global.
- Updated to use injected settings:
- `BaseIndex`, `MemoryIndexesManager`, and `MemoryHeightIndex`.
- `BaseTransaction` and all its subclasses, and `TransactionMetadata`.
- `get_deposit_amount()` and `get_withdraw_amount()` functions.
- Updated `TransactionStorage` to inject its settings into constructed genesis.
> refactor(settings): more settings injection refactors

- hathor/cli/side_dag.py
- hathor/cli/util.py
- hathor/conf/settings.py
- hathor/consensus/poa/__init__.py
- hathor/consensus/poa/poa.py
- hathor/transaction/poa/poa_block.py
- hathor/verification/poa_block_verifier.py
- hathor/version_resource.py
- tests/poa/test_poa.py
Update API response models to include side-dag and Proof-of-Authority related data.
- Add `NATIVE_TOKEN_NAME` and `NATIVE_TOKEN_SYMBOL` to `HathorSettings` and to the `/v1a/version` API.
- Add `DECIMAL_PLACES` and genesis hashes to the `/v1a/version` API.
- Update `PoaBlock.to_json()` to include PoA fields.
- Implement `poa.get_signer_index_and_public_key()` and update `PoaBlockVerifier` to use it.
- Add missing `PoaBlock` timestamp verification.
- Change pre-argument parsers to use `create_parser()`, adding support for environment variables.
> feat(side-dag): update APIs

- hathor/builder/cli_builder.py
- hathor/metrics.py
- hathor/p2p/entrypoint.py
- hathor/p2p/manager.py
- hathor/p2p/peer_discovery/bootstrap.py
- hathor/p2p/peer_discovery/dns.py
- hathor/p2p/peer_discovery/peer_discovery.py
- hathor/p2p/peer_id.py
- hathor/p2p/protocol.py
- hathor/p2p/resources/add_peers.py
- hathor/p2p/utils.py
- hathor/types.py
- tests/others/test_metrics.py
- tests/p2p/test_connections.py
- tests/p2p/test_peer_id.py
- tests/resources/p2p/test_add_peer.py
Using a `str` is not ideal.
- introduce new `Entrypoint` class that can be parsed from and converted back to the `tcp://hostname:port` format, optionally allowing a peer-id (this was already supported): `tcp://hostname:port/?id=peer-id`
- introduce `Hash` class that works as a `bytes` with fixed length of 32, to be used as base for `PeerId` class that `Entrypoint` uses for storing peer-ids (this `Hash` class can be slowly used in more places in the future)
- replace every instance of `str` used as an endpoint description with `Entrypoint`
> refactor(p2p): use Entrypoint type instead of str

- hathor/p2p/states/hello.py
Different version log is unnecessarily a warning.
- Change from `log.warn` to `log.debug`.
> fix(logging): make different version logging less obtrusive

- hathor/consensus/poa/__init__.py
- hathor/consensus/poa/poa.py
- hathor/consensus/poa/poa_block_producer.py
- tests/poa/test_poa.py
- tests/poa/test_poa_block_producer.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1071
Improve the mechanism used in `PoaBlockProducer` to generate new block timestamps, as requested in https://github.com/HathorNetwork/hathor-core/pull/1061#discussion_r1635167050.
- Change `poa.is_in_turn()` to `poa.in_turn_signer_index()`.
- Change `PoaBlockProducer` timestamp generation to use a signer round-robin approach instead of random delay.
> feat(side-dag): implement signer round-robin

- hathor/consensus/consensus_settings.py
- hathor/consensus/poa/__init__.py
- hathor/consensus/poa/poa.py
- hathor/consensus/poa/poa_block_producer.py
- tests/others/test_hathor_settings.py
- tests/poa/test_poa.py
- tests/poa/test_poa_block_producer.py
- tests/poa/test_poa_simulation.py
- tests/poa/test_poa_verification.py
- tests/poa/utils.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1074
Implement ability to update the signers list on PoA networks by configuring start and end block heights where each signer is active. By the default, a signer is active from height 0 to infinity. By setting the start height on a new signer, the network can coordinate to add it without disrupting existing blocks.
- Update PoA settings to be able to configure `start_height` and `end_height` for signers.
- Implement `poa.get_active_signers()` and update all usages of `poa_settings.signers` to use it instead.
- Update `PoaBlockProducer` to calculate the signer index depending on active signers.
> feat(side-dag): add ability to update signers list

- hathor/p2p/entrypoint.py
- hathor/p2p/manager.py
- hathor/p2p/peer_discovery/dns.py
- hathor/p2p/peer_id.py
- hathor/p2p/states/ready.py
- tests/p2p/test_bootstrap.py
#1086 introduced a regression as can be seen [in the failed docker build, during the image test](https://github.com/HathorNetwork/hathor-core/actions/runs/9997668572/job/27634764715)
- `Entrypoint.peer_id` should default to `None` (mypy didn't catch this)
- `defer.gatherResults` had to be chained before passing it to `set`
- `ProtocolMessages.PEERS` data was being constructed with `Entrypoint` objects, which can't be used in `json.dumps`, it needed to be converted to `str`
- Adjust `PeerId.__str__` so it uses `str(entrypoint)` instead of `repr(entrypoint)` to keep it less verbose
- Add tests that cover all the lines that have errors
> fix(p2p): regression after entrypoint refactor

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/consensus/consensus_settings.py
- hathor/consensus/poa/poa.py
- hathor/consensus/poa/poa_block_producer.py
- hathor/p2p/factory.py
- hathor/p2p/manager.py
- hathor/p2p/protocol.py
- hathor/p2p/states/base.py
- hathor/p2p/states/hello.py
- hathor/p2p/states/peer_id.py
- hathor/p2p/states/ready.py
- hathor/p2p/utils.py
- tests/others/test_metrics.py
- tests/p2p/test_bootstrap.py
- tests/p2p/test_whitelist.py
- tests/poa/test_poa.py
- tests/poa/test_poa_block_producer.py
- tests/poa/test_poa_simulation.py
- tests/unittest.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1075
This PR adds a validation of PoA signers list when peers connect.
- Add consensus algorithm validation on peer hello.
- Change `Builder` so it requires settings to be set.
- Update P2P related code to use injected settings.
> feat(side-dag): add signers validation on peer hello

- Makefile
- extras/custom_tests.sh
- extras/custom_tests/side_dag/test_both_fail.py
- extras/custom_tests/side_dag/test_one_fails.py
- extras/custom_tests/side_dag/utils.py
- hathor/cli/side_dag.py
- tests/cli/test_side_dag.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1078
Improve the `run_node_with_side_dag` command so instead of a main process running the side dag node and a subprocess running the Hathor node, it's a main process running a monitor and multiple possible subprocesses running any number of nodes. For now, it only runs one side dag node and one Hathor node, but it can be easily changed to support more in the future.
Resolves https://github.com/HathorNetwork/hathor-core/issues/1051.
- Refactor side dag CLI tool.
- Simplify how monitoring is made and remove all message passing between processes.
> refactor(side-dag): refactor node processes management

- hathor/builder/resources_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/wallet/hd_wallet.py
- hathor/websocket/exception.py
- hathor/websocket/factory.py
- hathor/websocket/iterators.py
- hathor/websocket/messages.py
- hathor/websocket/protocol.py
- hathor/websocket/streamer.py
- tests/sysctl/test_websocket.py
- tests/unittest.py
- tests/websocket/test_async_iterators.py
- tests/websocket/test_streamer.py
- tests/websocket/test_websocket.py
Wallets might need to download their transaction history. The full node currently offers a polling API but this is too slow to both large wallets and high latency environments. This PR implements a streaming API that speeds up the download for wallets.
Client sends either `request:history:xpub` or `request:history:manual`.
Server open the streaming and follows the documented protocol (see the streamer docustring).
Testing with a wallet that has 1,060 addresses and 1,187 transactions with 480ms of latency between the wallet and the full node.
Download time
- Polling API: 17,764ms
- XPub Streamer: 3,284ms
- Manual Streamer: 2,893ms
Total time (including a post-processing that occurs after the download):
- Polling API: 27,336ms
- XPub Streamer: 13,189ms
- Manual Streamer: 13,551ms
Notice …
> feat(wallet): Add a vertex history streamer to the wallet websocket API

- hathor/manager.py
This verification has to happen anyway and doing it earlier avoids wasting time with more expensive verifications.
- Check for tx existence on `HathorManager.push_tx` directly before waiting for `HathorManger.on_new_tx` to do it.
> refactor(api): prevent duplicate tx earlier

- hathor/p2p/peer_id.py
- hathor/p2p/resources/status.py
- hathor/p2p/states/peer_id.py
- hathor/p2p/states/ready.py
- tests/p2p/test_protocol.py
- tests/resources/p2p/test_status.py
After #1086 there were some other parts that broke that weren't covered by any test.
- Add `.entrypoints_str()` helper method that returns a list of `str` serialized entrypoints
- Use `.entrypoints_str()` where previously `.entrypoints` was used with the expectation of being a list of `str`
- Add tests that cover the main 2 breakages: the `status` API and the `PEER-ID` message (when entrypoint is present)
> fix(p2p): status regression after entrypoint refactor

- hathor/indexes/manager.py
- hathor/indexes/mempool_tips_index.py
When we made sync-v2 always available, even when not enabled, it implied having to initialize the mempool-tips index, but its RocksDB implementation had been disabled for having a very slow initialization but using a memory index has the downside of always initializing the index on every start.
The mempool is defined as the set of transactions that don't have a `first_block` and are not voided, the mempool-tips index only stores only the mempool transactions that are "tips" (in the sense that all the other transactions can be reached by traversing to the left), the practical definition is the set of all transactions that don't have a `first_block`, don't have a non-voided child and don't have a non-voided spent_output (that is, they aren't literal "tips" because they can have children or …
> fix(indexes): efficient rocksdb mempool-tips initialization

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
We're at a point where every node is running only `sync-v2`, except for a few nodes that we maintain in bridge mode that run `sync-v1 + sync-v2`. So for the next release we can safely disincentivize `sync-v1` from being used either through `--sync-v1-only` or `--sync-bridge`.
- hide `--sync-bridge`, mark it as unsafe and unhide `--x-sync-bridge` (also unsafe) to be used instead
- hide `--sync-v1-only`, mark it as unsafe and add `--x-sync-v1-only` (also unsafe) to be used instead
- hide `--sync-v2-only`, since it's the default, using it will only show a warning
- after the above, every cli option that enables `sync-v1` should require `--unsafe=...` to be used
> chore(cli): mark sync-v1 and bridge as unsafe

- hathor/consensus/poa/__init__.py
- hathor/consensus/poa/poa.py
- hathor/consensus/poa/poa_block_producer.py
- tests/poa/test_poa.py
- tests/poa/test_poa_block_producer.py
- tests/poa/test_poa_simulation.py
Implement some of the requested changes in previous PRs.
- Remove `poa.in_turn_signer_index()` and add `poa.get_signer_index_distance()`.
- Update `poa.calculate_weight()` to decrease the block weight inversely proportional to the index distance.
- Changes in `PoaBlockProducer`:
- Merge both looping calls into one.
- Add delayed block production cancellation.
- Update logs.
- Change block delay function to include a constant offset for out of turn blocks, and increase the interval between each signer.
- Update tests accordingly.
> refactor(side-dag): general improvements

- hathor/transaction/genesis.py
There's a bug in the `gen-genesis` CLI tool where the timestamps are changed when the genesis weights are greater than zero.
- Set `update_time=False` on genesis generation.
> fix: fix timestamps on gen-genesis CLI

- hathor/indexes/manager.py
With the deploy of `v0.62.0-rc.1` the sync from scratch took significantly longer than expected. The cause was confirmed to be the use of `RocksDBMempoolTipsIndex` that was introduced. The simplest solution to quickly advance with the release is to revert to `MemoryMempoolTipsIndex`.
- Revert back to `MemoryMempoolTipsIndex` for `RocksDBIndexesManager.mempool_tips`
> fix(performance): using RocksDBMempoolTipsIndex made the sync too slow

- .github/actions/setup-hathor-env/action.yml
- .github/workflows/base_benchmarks.yml
- .github/workflows/main.yml
- .github/workflows/pr_benchmarks.yml
- extras/benchmarking/benchmark_sync_v2.sh
This PR implements the basic infrastructure for running benchmarks in our CI through GitHub Actions and the [Bencher](https://bencher.dev) tool, which automatically tracks changes in performance across PRs (though it is more flexible than that). Bencher is [open source](https://github.com/bencherdev/bencher) and provides their cloud to run the Bencher service, which we're using through a free tier plan. We can consider upgrading our plan or running our own self-hosted service if necessary, but I don't see any reasons for now. This means our benchmarking results are public on the [Bencher Console](https://bencher.dev/console/projects/hathor-core/).
We setup a benchmark for tracking sync-v2 performance. It works by:
1. Setting up a temporary node connected to testnet that exits after …
> feat: add sync-v2 benchmark to CI

- hathor/cli/merged_mining.py
- hathor/client.py
- hathor/merged_mining/coordinator.py
On the mainnet miners mostly use pools with custom integrations, but on the testnet the whole stack is in our control. For testing the newly activated (on the testnet) extended merkle_path len, we benefit from having the merged mining coordinator be able to do it seamlessly with some injected dummy merkle path.
- Add `--x-dummy-merged-mining` and `--x-dummy-merkle-len` to `run_merged_mining` subcommand, for running a coordinator with a dummy chain (instead of BTC), and with a dummy merkle path with the specified length;
- Adapt the merged mining coordinator to support mining without a BTC node and with dummy data instead.
> feat(mergedmining): support dummy mining on coordinator

- hathor/builder/resources_builder.py
We had a report from someone accidentally using an invalid prefix through `HATHOR_PROMETHEUS_PREFIX` which had a message that was hard to understand.
- Check for invalid Prometheus prefix when building and give a more helpful message.
> feat(cli): early protection for invalid prometheus prefix

- Dockerfile
- extras/github/test_docker.py
The default has been 3.10 for a while now and it's the lowest supported version, meanwhile 3.11 has some useful performance improvements.
- Change the default Python version used on Docker images from 3.10 to 3.11
> chore(ci): update default Python version used on docker images

- .github/workflows/base_benchmarks.yml
- .github/workflows/pr_benchmarks.yml
PR https://github.com/HathorNetwork/hathor-core/pull/1117 attempted to fix the benchmark CI on master but it was still missing some configs. This PR fixes this, again.
- Add config to prevent multiple benchmark CI actions from running concurrently.
- Fix base benchmark workflow.
> fix(benchmark): fix CI on master

- .envrc
- .gitignore
- flake.lock
- flake.nix
Improve developer experience running the fullnode when using nix (with nix-flakes and direnv) by having a reproducible dev environment with fixed versions
- We should have a `direnv` with all dependencies needed by the fullnode to run
- We should use flake-utils to make the dev env available to all default systems supported by nixpkgs  (e.g., x86_64-linux, aarch64-linux, x86_64-darwin, etc.)
- We should use python 3.10
- The dev env should set the poetry env python to v3.10
This flake uses a hybrid approach (nix + poetry), which is fine as poetry has a rich lock file which results in deterministic installs and builds, but we could use [poetry2nix](https://github.com/nix-community/poetry2nix) to have nix also managing python dependencies. More on this …
> chore: flake.nix creating a devshell with all fullnode dependencies needed to run the fullnode

- .github/actions/setup-hathor-env/action.yml
- .github/workflows/docker.yml
- .github/workflows/main.yml
Some workflows were giving warnings that they were using actions running on node16 and node16 has reached EOL for almost a year.
For now all node16 runners are forced to run on node20 and this behavior will be set to fail the action in a few months.
[Github announcement](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)
- upgrade actions to a version that use node20 (LTS)
> chore: upgrade actions to a version that use node20 (LTS)

- docs/legacy/ref/p2p.rst
- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/peer_id.py
- hathor/cli/run_node.py
- hathor/daa.py
- hathor/manager.py
- hathor/p2p/factory.py
- hathor/p2p/manager.py
- hathor/p2p/peer.py
- hathor/p2p/peer_storage.py
- hathor/p2p/protocol.py
- hathor/p2p/states/peer_id.py
- hathor/p2p/states/ready.py
- hathor/simulator/fake_connection.py
- hathor/simulator/simulator.py
- tests/cli/test_sysctl_init.py
- tests/event/event_simulation_tester.py
- tests/others/test_metrics.py
- tests/p2p/netfilter/test_match.py
- tests/p2p/test_bootstrap.py
- tests/p2p/test_peer_id.py
- tests/p2p/test_protocol.py
- tests/p2p/test_sync_v2.py
- tests/resources/p2p/test_add_peer.py
- tests/simulation/base.py
- tests/simulation/test_simulator_itself.py
- tests/unittest.py
This is the first part of a series of refactors. This first refactor is a step to make using `PeerId` for only the `id` part of `Peer`.
- rename `hathor.p2p.peer_id.PeerId` to `hathor.p2p.peer.Peer`
> refactor(p2p): rename peer_id.PeerId to peer.Peer

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/manager.py
- hathor/metrics.py
- hathor/p2p/entrypoint.py
- hathor/p2p/manager.py
- hathor/p2p/netfilter/matches.py
- hathor/p2p/peer.py
- hathor/p2p/peer_id.py
- hathor/p2p/peer_storage.py
- hathor/p2p/protocol.py
- hathor/p2p/resources/status.py
- hathor/p2p/states/peer_id.py
- hathor/p2p/states/ready.py
- hathor/p2p/utils.py
- hathor/stratum/stratum.py
- hathor/sysctl/p2p/manager.py
- tests/event/event_simulation_tester.py
- tests/p2p/test_peer_id.py
- tests/resources/p2p/test_status.py
- tests/sysctl/test_p2p.py
This is the second refactor in this series. It makes it so `Peer.id` is a `PeerId` instead of a `str`, that way it is already checked to be a valid hash.
- Change the type of `hathor.p2p.peer.Peer.id` from `str` to `hathor.p2p.peer_id.PeerId`
> refactor(p2p): use PeerId type instead of str

- hathor/healthcheck/resources/healthcheck.py
- tests/resources/healthcheck/test_healthcheck.py
We are getting an error from aiohttp in explorer-service when trying to get `/health` from hathor-core and parse it as json.
- The `/health` endpoint should use the correct Content-Type which should be `application/json`, instead of `text/html`
> fix: healthcheck content-type

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/builder/resources_builder.py
- hathor/feature_activation/bit_signaling_service.py
- hathor/feature_activation/feature_service.py
- hathor/feature_activation/model/feature_info.py
- hathor/feature_activation/model/feature_state.py
- hathor/feature_activation/resources/feature.py
- hathor/transaction/__init__.py
- hathor/transaction/static_metadata.py
- hathor/transaction/storage/rocksdb_storage.py
- hathor/verification/block_verifier.py
- hathor/verification/verification_service.py
- hathor/vertex_handler/vertex_handler.py
- tests/feature_activation/test_bit_signaling_service.py
- tests/feature_activation/test_feature_service.py
- tests/feature_activation/test_feature_simulation.py
- tests/resources/feature/test_feature.py
- tests/tx/test_verification.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1014
---
Continuing with the static metadata refactor introduced in PRs https://github.com/HathorNetwork/hathor-core/pull/1013 and https://github.com/HathorNetwork/hathor-core/pull/1014, the next step is to move the `feature_states` attribute from metadata to static metadata.
This was initially implemented in PR https://github.com/HathorNetwork/hathor-core/pull/1015, which turned out to be too large, so it was divided into 3 PRs: this one, https://github.com/HathorNetwork/hathor-core/pull/1017, and https://github.com/HathorNetwork/hathor-core/pull/1018. The latter is the one that actually moves the `feature_states` attribute, and the first two PRs perform simple refactors that were either necessary or small improvements. …
> refactor(metadata): pre-refactors for migrating feature states to static metadata [part 3/12]

- hathor/cli/load_from_logs.py
- hathor/cli/main.py
- hathor/cli/parse_logs.py
Currently, the `load-from-logs` CLI command reads a raw logs file as outputted by a full node. This PR changes it so instead you have to process the log file with the `parse-logs` command, only then to use it with `load-from-logs`. This makes the log files much smaller, as the parser strips every information but the vertex bytes.
Also, previously that command only called `on_new_tx` in a loop, but didn't actually run the reactor or the full node itself. This PR also changes this.
The new intended workflow would be something like this:
```bash
$ poetry run hathor-cli run_node --testnet --memory-storage --json-logs --log-vertex-bytes &> json_logs
$ poetry run hathor-cli parse-logs --output-file parsed_logs --json-logs-file json_logs
$ poetry run hathor-cli load-from-logs --testnet …
```
> feat: improve load-from-logs CLI command

- hathor/websocket/messages.py
- hathor/websocket/protocol.py
- hathor/websocket/streamer.py
- tests/websocket/test_streamer.py
When the stream ended, an ACK message arrived late, causing an error response to be generated.
Check out the state diagram in the Reference-level explanation here: https://github.com/HathorNetwork/internal-rfcs/pull/25
1. Do nothing if the ACK received from the client is duplicated.
2. Stop the streamer if the ACK received from the client decreases.
3. Stop the streamer if the ACK received from the client is higher than the last sent message sequence number.
4. Add some protection to the `pauseProducing`, `stopProducing`, and `resumeProducing` methods.
5. Replace flags `_started`, `_paused`, and `_stop` by a state machine.
6. Introduce the new state `CLOSING` which means the streaming has ended and it is just waiting for the last ACK.
7. Modify streamer to expect ack for the stream end …
> fix(ws): Add a graceful close mechanism to handle late messages and prevent errors

- hathor/p2p/resources/status.py
- tests/resources/p2p/test_status.py
The `/v1a/status` had a regression after merging #1114 
- Convert PeerId to str for the status response
- Tweak test to not have an empty whitelist so that this is covered
> fix(api): status regression after p2p refactor

- hathor/websocket/streamer.py
Twisted can call `pauseProducing()` multiple times before calling `resumeProducing()`. This transition from PAUSED to PAUSED was not expected and it was generating a wrong warning log message.
1. Allow transition `PAUSED -> PAUSED` which actually does nothing.
> fix(ws): Fix tx history streamer wrong logging when pauseProducing() is called multiple times

- hathor/cli/events_simulator/scenario.py
- hathor/consensus/consensus.py
- hathor/event/model/event_data.py
- hathor/wallet/base_wallet.py
- tests/tx/test_reward_lock.py
We noticed that the `wallet.get_balance_per_address()` method was not working correctly in the end of the reward lock event simulation — it was not considering the removed tx. This PR fixes this.
- Add voidance assertion in `_remove_transactions()`.
- Prevent event processing from reloading metadata.
- Add `CONSENSUS_TX_REMOVED` event handling on test wallet.
- Add typing to `test_reward_lock.py`.
- Add balance and voidance assertions in reward lock test and event simulation scenario.
> fix: removed txs from test wallet

- hathor/cli/openapi_files/openapi_base.json
- hathor/version.py
- pyproject.toml
Start preparing for a release.
- Bump version from v0.62.0 to v0.63.0
> chore: bump version to v0.63.0

- hathor/prometheus.py
We want to observe how the garbage collector is behaving, as part of https://github.com/HathorNetwork/internal-issues/issues/379
- The main goal is to have metrics to show us how many objects the garbage collector has collected over time and how many objects it's tracking in each moment, but we added some other metrics that seemed nice to have
This is an example of the generated metrics:
```
hathor:python_gc_objects{generation="0"} 80.0
hathor:python_gc_objects{generation="1"} 10.0
hathor:python_gc_objects{generation="2"} 14.0
hathor:python_gc_collections{generation="0"} 1671.0
hathor:python_gc_collections{generation="1"} 151.0
hathor:python_gc_collections{generation="2"} 10.0
hathor:python_gc_collected{generation="0"} 162881.0
hathor:python_gc_collected{generation="1"} 33275.0 …
```
> chore: collect garbage collector metrics

- hathor/builder/resources_builder.py
- hathor/builder/sysctl_builder.py
- hathor/cli/run_node.py
- hathor/manager.py
- hathor/metrics.py
- tests/cli/test_run_node.py
- tests/cli/test_sysctl_init.py
I had a problem while trying to write a test for `run_node.py` in another PR. The reason was that the `HathorAdminWebsocketFactory` was started and never stopped.
I noticed that its stop method was never called, and its start was called inside `ResourcesBuilder.create_resources`, which was unlike any other resource we start.
I've included a test similar to the one I had problems with to make my difficulties clearer.
- The `HathorAdminWebsocketFactory` should be started as a consequence of starting the Manager, and should be stopped when the Manager is stopped
- There should be no impact in the overall logic of hathor-core. Everything should work like before.
> refactor[websocket]: improve websocket factory start

- hathor/transaction/static_metadata.py
- hathor/transaction/storage/rocksdb_storage.py
- hathor/transaction/transaction_metadata.py
- tests/feature_activation/test_feature_service.py
- tests/feature_activation/test_feature_simulation.py
A couple PRs were previously merged in preparation for migrating the `feature_states` attribute from "normal" metadata to static metadata (https://github.com/HathorNetwork/hathor-core/pull/1016, https://github.com/HathorNetwork/hathor-core/pull/1017). As this migration has been postponed, this PR undoes some of those previous changes such as bringing back removed tests.
Effectively, it cancels the unmerged https://github.com/HathorNetwork/hathor-core/pull/1018. The reason for cancelling it is that it changes the Feature Activation algorithm a bit, requiring careful review, and we don't want to invest the time in it right now. Instead, we want to merge Feature Activation for Transactions (https://github.com/HathorNetwork/hathor-core/pull/933) as soon as possible to begin testing it, so …
> refactor(static-metadata): undo migration of feature_states to static metadata

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/events_simulator/events_simulator.py
- hathor/event/websocket/factory.py
- hathor/manager.py
- hathor/metrics.py
- hathor/p2p/factory.py
- hathor/p2p/manager.py
- hathor/p2p/protocol.py
- hathor/p2p/states/hello.py
- hathor/simulator/simulator.py
- hathor/transaction/block.py
- hathor/transaction/storage/__init__.py
- hathor/transaction/storage/traversal.py
- tests/cli/test_events_simulator.py
- tests/event/websocket/test_factory.py
- tests/others/test_metrics.py
- tests/p2p/test_bootstrap.py
- tests/poa/test_poa_verification.py
- tests/tx/test_cache_storage.py
- tests/unittest.py
This PR contains some useful pre-refactors for the P2P Multiprocess project.
- Remove unnecessary `network` parameter from multiple classes. They use `settings.NETWORK_NAME` instead.
- Refactor `p2p/factory.py`, unifying client and server factories in a base class to simplify it.
- Update typings in the `traversal` module so it can receive the more flexible `VertexStorageProtocol` instead of a `TransactionStorage`.
- No changes in behavior.
> refactor(p2p): simplify factory [part 1/5]

- .github/workflows/pr_benchmarks.yml
A [recent update](https://bencher.dev/docs/reference/changelog/#v0421) in our benchmark CI tool, bencher, broke our alerts. This PR fixes it.
- Fix benchmark CI.
> fix(benchmark): fix benchmark CI after bencher update

- hathor/builder/builder.py
- hathor/conf/settings.py
- hathor/manager.py
- hathor/reward_lock/reward_lock.py
- hathor/simulator/simulator.py
- hathor/transaction/storage/transaction_storage.py
- hathor/verification/transaction_verifier.py
- hathor/wallet/base_wallet.py
- hathor/wallet/hd_wallet.py
- hathor/wallet/wallet.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1146
Remove global settings from reward lock and test wallets. This will be useful for Feature Activation for Transaction tests.
- Move `HathorSettings.HATHOR_TOKEN_UID` to a constant.
- Change reward lock functions to use injected settings.
- Change test wallets to use injected settings.
> refactor(settings): change wallets and reward lock to use injected settings

- hathor/manager.py
- hathor/p2p/sync_v2/agent.py
- hathor/p2p/sync_v2/blockchain_streaming_client.py
- hathor/transaction/base_transaction.py
- hathor/transaction/storage/transaction_storage.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1151
As part of the P2P Multiprocess project, move a `BaseTransaction` method that is used by the sync to the storage.
- Move `can_validate_full` method from `BaseTransaction` to `TransactionStorage`.
- Remove similar and unused `BaseTransaction.is_ready_for_validation` method.
- No changes in behavior.
> refactor: move can_validate_full method [part 2/8]

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/manager.py
- hathor/p2p/sync_v1/agent.py
- hathor/p2p/sync_v2/agent.py
- hathor/p2p/sync_v2/blockchain_streaming_client.py
- hathor/p2p/sync_v2/mempool.py
- hathor/profiler/cpu.py
- hathor/transaction/storage/transaction_storage.py
- hathor/vertex_handler/vertex_handler.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1153
As part of the P2P Multiprocess project, this PR refactors the `VertexHandler` so it does not depend on the `p2p_manager` anymore.
- Remove the `p2p_manager` dependency from `VertexHandler`. This means it does not propagate vertices anymore, and it's the caller's responsibility to do it.
- Remove duplicate `partial_vertex_exists` methods from sync classes and move it to the storage.
- Update all calls to `VertexHandler.on_new_vertex` to propagate vertices accordingly:
- If the call explicitly set `propagate_to_peers=False`, no change was necessary.
- If the call didn't provide the `propagate_to_peers` argument or set it as `True`, add a follow-up call to `p2p_manager.send_tx_to_peers`.
- Move CPU profiler from …
> refactor(vertex-handler): remove p2p_manager dependency [part 1/8]

- hathor/conf/mainnet.py
- hathor/conf/mainnet.yml
- hathor/feature_activation/feature.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1149
Since we are forcing recalculation of all metadata, we can remove unused features.
- Remove all unused features.
> chore: remove all unused features

- hathor/feature_activation/bit_signaling_service.py
- hathor/feature_activation/feature_service.py
- hathor/feature_activation/resources/feature.py
- hathor/transaction/static_metadata.py
- hathor/transaction/storage/migrations/add_closest_ancestor_block.py
- hathor/verification/merge_mined_block_verifier.py
- hathor/vertex_handler/vertex_handler.py
- tests/feature_activation/test_bit_signaling_service.py
- tests/feature_activation/test_feature_service.py
- tests/feature_activation/test_feature_simulation.py
- tests/resources/transaction/test_tx.py
- tests/tx/test_cache_storage.py
- tests/tx/test_static_metadata.py
- tests/tx/test_tx.py
Depends on https://github.com/HathorNetwork/hathor-core/pull/1150
Implement the new `closest_ancestor_block` static metadata and Feature Activation for Transactions.
- Create new `closest_ancestor_block` static metadata for Transactions.
- Implement Feature Activation for Transactions.
> feat(feature-activation): implement closest_block metadata and Feature Activation for Transactions

- hathor/conf/testnet.py
- hathor/conf/testnet.yml
Add a Feature Activation config for a NOP feature to test Feature Activation for Transactions in testnet.
- Add NOP feature config in testnet.
> chore(feature-activation): config NOP feature to test FA for transactions

- hathor/p2p/protocol.py
In a recent PR we changed the error handling when processing P2P protocol messages. It was changed from a `try-except` to an errback on a Deferred. Because of that, logging with `exc_info` is not useful, since we're not in an exception context anymore, it's empty. Instead, we should log the traceback from the `twisted.Failure`.
Also, I changed it from `warn` to `error` as any error should be handled before reaching this code, and if it does, it's an unhandled error that we should know about. 
- When logging errors during processing of a P2P protocol message, include the traceback and change it to `error` instead of `warn`.
> chore: improve p2p protocol error logging

- hathor/consensus/block_consensus.py
- hathor/transaction/storage/migrations/include_funds_for_first_block.py
- hathor/transaction/storage/transaction_storage.py
- tests/consensus/test_first_block.py
When setting the metadata `first_block`, the consensus algorithm currently traverses only the DAG of verifications (i.e., the parents). This PR changes this behavior and begin to traverse the DAG of funds as well (i.e., the inputs).
1. Traverse the DAG of funds when setting the `first_block` in the `BlockConsensusAlgorithm`.
2. Traverse the DAG of funds when clearing the `first_block` in the `BlockConsensusAlgorithm`.
> feat(consensus): Use DAG of funds to set first_block

- .github/workflows/main.yml
The macos-12 runner will be dropped by Github Actions: https://github.com/actions/runner-images/issues/10721
- We should use macos-13 instead. There are newer ones, but I preferred the safe path of just one version up.
> ci: use macos-13 on Github Actions as macos-12 will be dropped

- hathor/p2p/sync_v2/agent.py
- tests/poa/test_poa_simulation.py
The sync v2 main loop already have protection against multiple executions. But it just checks if it is running every 5 seconds per connection. We can safely reduce this interval to 1 second, speeding up the sync.
1. Reduce the interval from 5s to 1s.
> feat(p2p): Change sync-v2 main loop interval to one second

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/nginx_config.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/conf/settings.py
- hathor/manager.py
- hathor/p2p/manager.py
- hathor/p2p/peer.py
- hathor/p2p/peer_endpoint.py
- hathor/p2p/states/peer_id.py
- hathor/p2p/states/ready.py
- hathor/simulator/fake_connection.py
- tests/cli/test_run_node.py
- tests/p2p/test_bootstrap.py
- tests/p2p/test_connections.py
- tests/p2p/test_entrypoint.py
- tests/p2p/test_peer_id.py
- tests/p2p/test_protocol.py
- tests/unittest.py
We want to support IPv6 connections between fullnodes and support exposing their API through IPv6
- We should be able to listen the API, the Stratum and the P2P port in IPv6 interfaces. This will be activated by a new CLI argument deemed initially as experimental: `--x-enable-ipv6`
- We will also have a `--x-disable-ipv4`, to make nodes stop connecting to IPv4 endpoints. For now this will be used mostly for tests though, to force a fullnode to behave as IPv6-only.
- The peers should relay IPv6 endpoints only to other peers that also have the IPv6 capability. Relaying them to old fullnodes would cause errors when they try to parse IPv6.
- For simplicity, this PR only implements support for IPv6 addresses in endpoints, not domains that contain AAAA records
> feat(p2p): support IPv6

- hathor/cli/events_simulator/events_simulator.py
- hathor/conf/testnet.py
- hathor/conf/testnet.yml
Delay the configuration of the NOP feature configuration to test Feature Activation for Transactions, as the new hathor-core version has not been released yet.
- Delay NOP feature config on testnet.
- I'm also using this PR to add an unrelated log line in the `events_simulator` CLI.
> chore(feature-activation): delay NOP feature

- hathor/builder/cli_builder.py
- hathor/builder/resources_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- tests/others/test_cli_builder.py
The Event Queue feature has been used for a while now by the Wallet Service, so we can remove it from unsafe/experimental mode.
- Remove `--x-enable-event-queue` from unsafe mode.
- Add `--enable-event-queue` and warning to deprecate `--x-enable-event-queue`.
> chore(events): remove event queue from unsafe mode

- hathor/conf/settings.py
- hathor/p2p/manager.py
- hathor/p2p/peer.py
- hathor/p2p/peer_discovery/bootstrap.py
- hathor/p2p/peer_discovery/dns.py
- hathor/p2p/peer_discovery/peer_discovery.py
- hathor/p2p/peer_endpoint.py
- hathor/p2p/peer_storage.py
- hathor/p2p/protocol.py
- hathor/p2p/resources/add_peers.py
- hathor/p2p/states/ready.py
- hathor/simulator/fake_connection.py
- tests/others/test_metrics.py
- tests/p2p/test_bootstrap.py
- tests/p2p/test_connections.py
- tests/p2p/test_connectivity.py
- tests/p2p/test_peer_id.py
- tests/p2p/test_peer_storage.py
- tests/p2p/test_protocol.py
- tests/poa/test_poa_simulation.py
- tests/resources/p2p/test_status.py
Names of methods `connect_to` and `connect_to_if_not_connected` don't clearly reflect what they do, and also storing received peers in connections manager is not ideal.
- Rename `connect_to` to `connect_to_endpoint`
- Rename `connect_to_if_not_connected` to `connect_to_peer`
- Move `ConnectionsManager.unverified_peer_storage` to `HathorProtocol.unverified_peer_storage`
- Add `ConnectionsManager.new_connection_from_queue` to choose which protocol to get a new peer from
- Add `lc_connect: LoopingCall` to call `connect_to_peer_from_connection_queue` and start new connections
> refactor(p2p): move received peers storage to protocol

- extras/github/docker.py
- extras/github/test_docker.py
I couldn't use `-python3.12` suffix on the release candidate image for testing.
- Include `-python{Version}` tags even for rc images
> chore(docker): include python suffix tags on rc images

- hathor/transaction/base_transaction.py
- hathor/transaction/resources/transaction_confirmation.py
- tests/resources/transaction/test_transaction_confirmation.py
The recent typing change in the `meta.accumulated_weight` introduced a regression in the `BaseTransaction.update_accumulated_weight()` method. Its implementation was not updated to consider the change. Also, the `/transaction_acc_weight` API was changed to incorrectly return work instead of weight, making it a breaking change for clients.
- Fix `BaseTransaction.update_accumulated_weight()` so it correctly compares work to the provided `stop_value`.
- Fix `update_accumulated_weight()` call in the consensus which was passing the incorrect `stop_value`.
- Fix `/transaction_acc_weight` API so it returns the correct values (weight instead of work).
> fix: acc weight regression

- hathor/conf/settings.py
The default value of 16 can be slower than expected in certain cases.
- Reduce the default value to 8, it can still be adjusted through the settings and even in runtime through sysctl.
> chore(p2p): decrease p2p.max_enabled_sync's default value: 16 -> 8

- hathor/conf/testnet.py
- hathor/conf/testnet.yml
The original test window for the transaction feature activation on testnet has passed.
- Move the time window to the present.
> chore(feature_activation): update start_height before release

- hathor/websocket/messages.py
- hathor/websocket/protocol.py
Fix an unhandled exception when a websocket command was malformed.
1. Send a `WebsocketErrorMessage` when a command is malformed.
> fix(ws): Fix JSON decode error on invalid commands

- hathor/websocket/factory.py
- hathor/websocket/protocol.py
The current implementation of empty addresses was too slow. It was running in O(n) where n is the number of subscribed addresses. So, the time complexity to load a wallet was O(n^2) because the check was executed for each address.
This PR reduces the time complexity to O(m) where m is the number of empty addresses. So, the load time is reduced to O(nm). Notice that `m < n / gap_limit`.
1. Add a separate list of empty addresses.
2. On address subscription, add empty addresses to the empty address set.
3. Only validate the list of empty addresses if the empty address set is greater than the limit.
> fix(ws): Slow empty address verification on address subscription

- hathor/dag_builder/vertex_exporter.py
- tests/dag_builder/test_dag_builter.py
If might happen that two different transactions have the same hash if their description is exactly the same. This PR fixes it by increasing the nonce.
1. Assert that each transaction has a unique hash.
2. Fix conflicts by increasing the nonce.
3. Set a maximum of 100 attempts to fix conflicts. If it fails, an exception is raised.
> fix(dag_builder): Fix generating two or more vertices with the same hash

- tests/event/test_event_simulation_responses.py
- tests/event/test_event_simulation_scenarios.py
- tests/p2p/test_sync_v2.py
- tests/simulation/base.py
We recently removed Sync-v1 from our tests suite, and I just found out that multiple tests are not running because they don't set `__test__ = True` anymore.
- Remove `__test__ = False` from the `SimulatorTestCase`.
> tests: re-enable tests

- docs/event-queue-feature.md
- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/consensus/consensus.py
- hathor/indexes/manager.py
- hathor/indexes/memory_tokens_index.py
- hathor/indexes/rocksdb_tokens_index.py
- hathor/indexes/tokens_index.py
- hathor/manager.py
- hathor/p2p/states/peer_id.py
- hathor/vertex_handler/vertex_handler.py
- tests/cli/test_shell.py
- tests/consensus/test_consensus.py
- tests/event/event_simulation_tester.py
- tests/event/test_event_storage.py
- tests/feature_activation/test_feature_simulation.py
- tests/others/test_cli_builder.py
- tests/others/test_metrics.py
- tests/p2p/test_sync_v2.py
- tests/poa/test_poa_simulation.py
- tests/tx/test_indexes.py
- tests/tx/test_indexes2.py
- tests/tx/test_tokens.py
- tests/tx/test_tx_storage.py
- tests/utils.py
This PR accumulates some minor cleanups, see below.
- Update event queue docs to remove mention of unsafe — that feature is no longer unsafe, but the docs were outdated.
- Handle unhandled exception in the deferred returned by `handle_peer_id()` — this currently generates unnecessary alerts.
- Remove `HAS_ROCKSDB` variable and all its usage — since we removed support for windows, this is not necessary anymore.
- Deprecate `--x-full-verification`.
- Refactor execution manager call.
- No changes in behavior.
> refactor(misc): minor maintenance changes

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- tests/cli/test_cli_main.py
Doing `python -m hathor run_node --help` broke in some cases due to a bug in some versions of argparse.
- Remove all mutually exclusive groups where all arguments have `help=SUPRESS`, but keep the arguments in the base parser
- Add a test that runs the CLI's help and have a basic sanity check (exit code 0 and at least 80 lines)
> fix(cli): regression on `run_node --help`

- hathor/daa.py
- hathor/indexes/manager.py
- hathor/reward_lock/reward_lock.py
- hathor/transaction/storage/__init__.py
- hathor/transaction/storage/cache_storage.py
- hathor/transaction/storage/memory_storage.py
- hathor/transaction/storage/rocksdb_storage.py
- hathor/transaction/storage/transaction_storage.py
- hathor/transaction/vertex_parser.py
- hathor/verification/transaction_verifier.py
Some files are still causing circular imports. This PR improve some imports to avoid it.
1. Move `HathorSettings` to the `TYPE_CHECKING` condition.
2. Add `from __future__ import annotations` in some files.
> chore: Improve HathorSettings imports

- hathor/dag_builder/artifacts.py
- hathor/dag_builder/tokenizer.py
- hathor/dag_builder/vertex_exporter.py
- hathor/transaction/base_transaction.py
- tests/consensus/test_first_block.py
- tests/dag_builder/test_dag_builder.py
This PR cherry-picks some `DAGBuilder` improvements from our private repo.
- Introduce `DAGArtifacts.get_typed_vertex`, `get_typed_vertices`, `propagate_with` convenience methods.
- Add node name to vertex objects, to aid debugging.
- Improve syntax docs.
> feat(dag-builder): improve DAGBuilder

- hathor/builder/builder.py
- hathor/builder/cli_builder.py
- hathor/cli/events_simulator/events_simulator.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/conf/settings.py
- hathor/manager.py
- hathor/simulator/simulator.py
- hathor/transaction/storage/transaction_storage.py
- tests/event/event_simulation_tester.py
- tests/event/test_event_manager.py
- tests/event/test_event_reorg.py
- tests/feature_activation/test_feature_simulation.py
- tests/others/test_init_manager.py
- tests/p2p/test_sync_v2.py
- tests/poa/test_poa_simulation.py
- tests/tx/test_tx_storage.py
- tests/unittest.py
Recent PR https://github.com/HathorNetwork/hathor-core/pull/1206 deprecated `--x-full-verification`, but its code was not cleaned up. This PR does this.
- Remove all mentions to full verification.
- Rename `HathorManager._initialize_components_new()` to `_initialize_components()`.
> refactor: cleanup full verification

- hathor/builder/cli_builder.py
- hathor/cli/run_node.py
- hathor/cli/run_node_args.py
- hathor/storage/rocksdb_storage.py
- tests/others/test_cli_builder.py
In preparation for removing memory storage and indexes, this PR adds the `--temp-data` CLI option to substitute `--memory-storage`
- Implement `--temp-data`.
- Deprecate `--memory-storage` and `--memory-indexes`.
> feat: add --temp-data CLI option

- poetry.lock
macOS CI is currently failing on `master` because rocksdb bindings are outdated. This PR fixes this.
- Update `python-rocksdb` to the latest commit.
> fix: update python-rocksdb

- hathor/vertex_handler/vertex_handler.py
As a node operator, having access to detailed log information is crucial for understanding the behavior of the system. Currently, log entries for block and tx events do not specify whether those blocks or transactions are valid or have been voided. This lack of clarity can create confusion—one might see multiple block log entries and incorrectly assume that mining is proceeding normally, when in fact those blocks could be voided.
1. Update the log messages so they explicitly differentiate between voided and non-voided vertices.
> feat(vertex_handler): Improve new vertex log

- Makefile
Sometimes when rocksdb is upgraded, the `python-rocksdb` bindings installation stops working, and a simple reinstall with `--no-binary` fixes it. This PR adds this command to the Makefile so it's easier for new devs to deal with this.
PS: Poetry does support [the no-binary option](https://python-poetry.org/docs/configuration/#installerno-binary) as a local config, but I couldn't get it to work. It seems it doesn't work with dependencies from git.
- Add `make fix-rocksdb` command.
> chore: add make fix-rocksdb command

- poetry.lock
- pyproject.toml
Dependency version drifted from the one in nano-hathor-core.
- Update python-hathorlib to v0.8.0
> chore: update python-hathorlib to 0.8.0

- hathor/indexes/rocksdb_tokens_index.py
- hathor/wallet/resources/thin_wallet/tokens.py
- tests/resources/transaction/test_tx.py
- tests/resources/wallet/test_thin_wallet.py
Acceptance criteria:
- Adds the token version in the database (rocksdb) when a tx is created.
- Adds version prop to `thin_wallet/tokens` endpoints
> feat: adds version field to thin_wallet tokens resource

- hathor/p2p/protocol.py
- hathor/p2p/rate_limiter.py
- hathor/p2p/sync_v2/agent.py
This PR introduces a misbehavior score but simply close the connection when the threshold is reached. A future PR can enforce better responses to misbehavior (e.g., temporary ban for the peer id or ip address).
1. Reject unsolicited vertices.
2. Add `_inbound_relay_enabled: bool` to control whether we request relay from the peer.
3. Add a misbehavior score for each connection which decays to zero in 1h.
4. If a peer misbehaves above a threshold, its connection is closed.
> feat(p2p): Add misbehavior score for unsolicited vertices

- hathor/nanocontracts/blueprint.py
- hathor/nanocontracts/fields/__init__.py
- hathor/nanocontracts/fields/container_field.py
- hathor/nanocontracts/fields/deque_field.py
- hathor/nanocontracts/fields/dict_field.py
- hathor/nanocontracts/fields/field.py
- hathor/nanocontracts/fields/nc_type_field.py
- hathor/nanocontracts/fields/set_field.py
- hathor/nanocontracts/fields/utils.py
Implement Blueprint and fields module.
Implement Blueprint and fields module.
> feat(nano): implement fields module [part 5]

- hathor/builder/resources_builder.py
- hathor/cli/events_simulator/scenario.py
- hathor/cli/openapi_files/register.py
- hathor/dag_builder/vertex_exporter.py
- hathor/event/event_manager.py
- hathor/event/model/event_data.py
- hathor/event/model/event_type.py
- hathor/manager.py
- hathor/nanocontracts/resources/__init__.py
- hathor/nanocontracts/resources/blueprint.py
- hathor/nanocontracts/resources/blueprint_source_code.py
- hathor/nanocontracts/resources/builtin.py
- hathor/nanocontracts/resources/history.py
- hathor/nanocontracts/resources/nc_creation.py
- hathor/nanocontracts/resources/nc_exec_logs.py
- hathor/nanocontracts/resources/on_chain.py
- hathor/nanocontracts/resources/state.py
- hathor/pubsub.py
- tests/event/test_base_event.py
- tests/event/websocket/test_protocol.py
Continue with the nano merges, adding all resources and event handling.
- Add nano resources.
- Update event handling.
> feat(nano): implement resources and events [part 12]

- Makefile
- tests/nanocontracts/test_execution_verification.py
- tests/nanocontracts/test_fallback_method.py
- tests/nanocontracts/test_follow_up_call.py
- tests/nanocontracts/test_indexes.py
- tests/nanocontracts/test_method_parser.py
- tests/nanocontracts/test_nanocontract.py
- tests/nanocontracts/test_nc_exec_logs.py
- tests/nanocontracts/test_patricia_trie.py
- tests/nanocontracts/test_rng.py
- tests/nanocontracts/test_seqnum.py
- tests/nanocontracts/test_serializer.py
- tests/nanocontracts/test_sorter.py
- tests/nanocontracts/test_storage.py
- tests/nanocontracts/test_syscalls.py
- tests/nanocontracts/test_syscalls_in_view.py
- tests/nanocontracts/test_token_creation.py
- tests/nanocontracts/test_types.py
- tests/nanocontracts/test_violations.py
- tests/resources/nanocontracts/test_nc_exec_logs.py
Proceed with merging Nano on master.
- Second batch of merging all tests.
> test(nano): add tests (batch 2) [part 16]

- hathor/cli/events_simulator/events_simulator.py
- hathor/cli/events_simulator/scenario.py
Nano-related scenarios are currently broken on the `events_simulator` CLI. This PR fixes this.
- Configure the correct reward lock for nano scenarios.
> fix(events): nano scenarios on simulator

- hathor/cli/events_simulator/scenario.py
When using Docker, the `tests` module is not copied to the image. So we cannot use imports from it in the CLI.
- Remove `TestDAGBuilder` usage from the `events_simulator` CLI.
> fix(events): nano scenarios on simulator when using Docker

- tests/nanocontracts/test_reentrancy.py
Blueprint developers must exercise caution when invoking external contracts, as this can introduce reentrancy vulnerabilities.
This PR includes an example blueprint that demonstrates a common reentrancy flaw: calling an external contract before updating the internal state. This mistake can allow an attacker to exploit the contract and repeatedly withdraw funds before the balance is properly updated.
1. Add a blueprint that is vulnerable to a reentrancy attack, enabling an attacker to drain all funds from the contract by bypassing the per-address withdrawal limit.
> test(nano): Add a test for reentrancy attack

- hathor/nanocontracts/blueprint_env.py
- hathor/nanocontracts/runner/runner.py
- tests/nanocontracts/test_execution_order.py
- tests/nanocontracts/test_syscalls_in_view.py
The `get_balance` syscall was deprecated in favor of the explicit methods `get_current_balance` and `get_balance_before_current_call`. This PR removes it.
Originally the task was to remove the `*_before_current_call` syscalls. But I gave more thought into it and I think it's good to keep them both, as it makes it clear for the user that there are different ways of interpreting the balance, and that they should choose the right one for their use case. Otherwise, it requires more knowledge of how our system works (for example, knowing when actions are executed).
- Remove `get_balance` syscall.
> chore(nano): remove deprecated get_balance

- hathor/nanocontracts/nc_types/__init__.py
- hathor/nanocontracts/nc_types/sized_int_nc_type.py
Timestamps don't make use of negative integers, so it's not useful to use a signed integer encoding.
- Introduce `Uint32NCType` that is similar to `Int32NCType` but unsigned instead of signed
- Change `Timestamp`'s mapping to `Uint32NCType`
> fix(nano): use Uint32 for Timestamp instead of Int32

- hathor/nanocontracts/nc_types/sized_int_nc_type.py
- tests/serialization/test_sized_int.py
Lower bound for signed integer was incorrectly using byte-size instead of bit-size.
- Fix lower bound calculation of sized signed integer serializer.
> fix(nano): incorrect lower bound in _SizedIntNCType

- hathor/nanocontracts/custom_builtins.py
- hathor/nanocontracts/on_chain_blueprint.py
- tests/nanocontracts/test_exposed_properties.py
The `type()` builtin is currently allowed on OCBs, but since it can be used to do introspection, getting the class of an object (which would equivalent to `obj.__class__`) and its metaclass, we should disallow unless we're sure it's safe.
- Disable `type()`, `object()`, and `super()` on OCBs.
> feat(nano): block usage of more builtins

- hathor/nanocontracts/allowed_imports.py
`CallerId` support for OCBs was missing.
- Add `CallerId` to allowed imports.
> fix(nano): allow import CallerId on OCBs

- hathor/nanocontracts/context.py
Fix compatibility with existing APIs.
- Readd `address` attribute to `Context.to_json()`, for compatibility with existing APIs.
> fix(nano): fix NC context on tx API

- hathor/nanocontracts/resources/state.py
- tests/resources/nanocontracts/test_state.py
When we refactored `ctx.address` into `ctx.caller_id` we also introduced specialized classes `Address(bytes)`, `VertexId(bytes)`, etc, and those broke a `if type(value) is bytes` check, either way that check was not the correct way to do it.
- Fix state API to return the value properly formatted (like its NCType specifies)
- Expand the existing test to have fields of types `Address`, `VertexId` and others
> fix(nano): state API regression after ctx.address refactor

- hathor/conf/mainnet.py
- hathor/conf/mainnet.yml
Activation window could be a bit tight since the start is late.
- Extend from 6 to 10 weeks
> chore: increase activation window for new feature

- hathor/nanocontracts/method.py
`Method.from_callable` could leak a `StopIteration` exception in some cases where an unsupported callable was given.
- Raise a `TypeError` instead of `StopIteration`
> fix(nano): `Method.from_callable` could leak `StopIteration`

- tests/nanocontracts/test_actions.py
Improve nano tests by making sure sending actions in different orders doesn't impact the final result.
- Update `test_actions.py` to run tests with different action orders in tests with more than one action.
> tests(nano): test actions order

- hathor/nanocontracts/storage/contract_storage.py
- hathor/nanocontracts/storage/patricia_trie.py
- tests/nanocontracts/test_patricia_trie.py
Benchmark shows similar (and slightly better) performance in some cases.
- Use SHA256 for storage hashing (both the patricia-trie and attribute-keys)
> feat(nano): change internal storage hashing to sha256

- hathor/consensus/block_consensus.py
- hathor/verification/transaction_verifier.py
- hathor/verification/verification_service.py
- hathor/verification/vertex_verifier.py
- tests/nanocontracts/on_chain_blueprints/test_script_restrictions.py
- tests/nanocontracts/test_consensus.py
- tests/nanocontracts/test_restricted_ocb.py
This PR improves test coverage of important nano or consensus related code, mostly by implementing new tests.
- Add `# pragma: no cover` comments on unreachable code branches.
- Add tests for allowed `match` syntax on OCBs.
- Add test for invalid Python syntax on OCBs.
- Add test for reorg with NC txs that have conflicts with other txs.
- Add missing tests for restricted signature mechanism on OCBs.
> tests(nano): increase coverage

- hathor/builder/resources_builder.py
- hathor/nanocontracts/utils.py
- hathor/verification/transaction_verifier.py
- hathor/version_resource.py
- tests/resources/test_version.py
The `/version` API was indirectly changed to return a string enum instead of a bool for the `nano_contracts_enabled` key, which made all clients believe the nano feature is active for all networks. This PR fixes this.
- Refactor `is_nano_active` logic into its own utils function.
- Change the `nano_contracts_enabled` key on the `/version` API to return a bool instead of an string enum.
> fix(nano): fix nano_contracts_enabled on /version api

- hathor/nanocontracts/nc_exec_logs.py
The previous limit of 100KiB is high, especially because there's no way to select specific contracts when enabling `NC_EVENT`s.
- Reduce limit from `100KiB` to `1KiB`
> feat(nano): reduce NC_EVENT max size to 1KiB

- hathor/nanocontracts/faux_immutable.py
- hathor/nanocontracts/types.py
- tests/nanocontracts/test_address_example.py
- tests/nanocontracts/test_blueprints/address_example.py
Currently there isn't a way to convert to/from string and addresses in Blueprint code. Instead of simply exposing the internal functions to do it, this PR exposes a friendlier API.
- add `str(address)` support for `address: Address`
- add `Address.from_str(raw_address)`
> feat(nano): add str utils for Address class

- hathor/consensus/block_consensus.py
- hathor/graphviz.py
- hathor/indexes/manager.py
- hathor/indexes/mempool_tips_index.py
- hathor/transaction/base_transaction.py
- hathor/vertex_handler/vertex_handler.py
- setup.cfg
- tests/consensus/test_consensus6.py
- tests/p2p/test_sync_v2.py
- tests/tx/test_mempool_tips_index.py
Improve handling of mempool tips on the index.
- When available, use `vertex.name` on graphviz and on vertex `repr`, which is useful for tests that use the `DAGBuilder`.
- Remove duplicate call to `mempool_tips.update` in vertex handler and move it to `indexes.update`.
- Refactor `mempool_tips.update` method:
- Change the `remove` argument from an optional bool to just a bool. Since the code is only ever called with either `True` or `None`, we could remove the current `False` case and use it instead of `None`, allowing simplification of the logic. Also, it's renamed to `force_remove`.
- Change logic to use the existing `any_non_voided` function instead of repeating it manually.
- Disable flak8 rule `E731 do not assign a lambda expression, use a def`. It was unnecessary and inconvenient.
> refactor(indexes): improve mempool tips index

- hathor/nanocontracts/__init__.py
- hathor/nanocontracts/allowed_imports.py
- hathor/nanocontracts/custom_builtins.py
- hathor/nanocontracts/on_chain_blueprint.py
- hathor/nanocontracts/types.py
- hathor/verification/on_chain_blueprint_verifier.py
- tests/nanocontracts/test_blueprints/bet.py
- tests/nanocontracts/test_exposed_properties.py
The current method of assigning to `__blueprint__` has some drawbacks. This proposal uses a decorator which should already be familiar because of `@view` and `@public` decorators.
- Move `hathor.nanocontracts.on_chain_blueprints.BLUEPRINT_CLASS_NAME` to `hathor.nanocontracts.types.BLUEPRINT_EXPORT_NAME`
- Introduce `hathor.nanocontracts.export` which just sets `__blueprint__` at the module where it is called, which means it is backwards compatible:
```python
@export
class Foo(Blueprint):
pass
```
Has the same runtime effect of:
```python
class Foo(Blueprint):
pass
__blueprint__ = Foo
> feat(nano): use decorator to export a Blueprint

- hathor/consensus/block_consensus.py
- tests/nanocontracts/test_nano_feature_activation.py
There's a bug in the initialization of block root IDs that makes the sync become too slow. This PR fixes it. Before this PR, `_nc_initialize_empty` was called only for the genesis and for the first active block. Instead, it should be called for every block where nano is not active.
- Use feature activation to decide whether we should call nano execution on the consensus.
- Call `_nc_initialize_empty` for every block non-active block, instead of just the genesis and the first active block.
> fix(nano): initialization of block root ids

- hathor/nanocontracts/context.py
- hathor/nanocontracts/resources/blueprint.py
- tests/nanocontracts/test_exposed_properties.py
Remove deprecated property in preparation for nano on mainnet.
- Remove deprecated `ctx.timestamp` property.
- Add `OCBBlueprintNotConfirmed` handling on blueprint API.
> chore(nano): remove deprecated ctx.timestamp

- hathor/nanocontracts/resources/blueprint.py
- tests/resources/nanocontracts/my_blueprint.py
- tests/resources/nanocontracts/test_blueprint.py
> Release-candidate v0.66.0-rc.5

- hathor/nanocontracts/resources/blueprint.py
- tests/resources/nanocontracts/my_blueprint.py
- tests/resources/nanocontracts/test_blueprint.py
Blueprint endpoint was always returning empty arguments for initialize method.
- Update test so the issue can show up
- Use `inspect.signature` instead of `inspect.getfullargspec` because it can properly take into account wrapped functions
> fix(nano): API was not processing initialize method correctly

- hathor/indexes/manager.py
- hathor/nanocontracts/blueprint_env.py
- hathor/nanocontracts/exception.py
- hathor/nanocontracts/nc_types/dataclass_nc_type.py
- hathor/nanocontracts/nc_types/sized_int_nc_type.py
- hathor/nanocontracts/runner/runner.py
- hathor/nanocontracts/runner/types.py
- hathor/nanocontracts/storage/block_storage.py
- hathor/nanocontracts/storage/changes_tracker.py
- hathor/nanocontracts/storage/contract_storage.py
- hathor/nanocontracts/storage/token_proxy.py
- hathor/nanocontracts/syscall_token_balance_rules.py
- hathor/transaction/token_info.py
- tests/nanocontracts/test_execution_order.py
- tests/nanocontracts/test_syscalls.py
- tests/nanocontracts/test_syscalls_in_view.py
- tests/nanocontracts/test_token_creation.py
To enable fee tokens in nano contracts with the create_fee_token, mint, and melt syscalls.
- allow `create_fee_tokens` paying with HTR by default
- allow `create_fee_tokens` paying with deposit token
- added the class `TokenSyscallBalanceRules` which is responsible for determine the fee amounts for each token version.
- Refactor `create_deposit_tokens` syscall to use `TokenSyscallBalanceRules`
- Remove duplicate call to `changes_tracker`, `call_records`, and `self._updated_tokens_totals`  in syscalls that deals with tokens (create, mint, melt).
- Mint and melt operations now will raise if the token isn't created.
- [] If you are requesting a merge into `master`, confirm this code is production-ready and can be included in future releases as soon as it gets merged
> feat(dynamic-transaction-model): create fee tokens in nano

- hathor/nanocontracts/blueprint.py
- hathor/nanocontracts/fields/container.py
- hathor/nanocontracts/fields/deque_container.py
- hathor/nanocontracts/fields/dict_container.py
- hathor/nanocontracts/fields/field.py
- hathor/nanocontracts/runner/runner.py
- tests/nanocontracts/fields/test_compound_field.py
- tests/nanocontracts/fields/test_deque_field.py
- tests/nanocontracts/fields/test_nested_containers.py
- tests/nanocontracts/fields/test_set_field.py
- tests/nanocontracts/test_blueprint.py
- tests/nanocontracts/test_blueprint_syntax.py
- tests/nanocontracts/test_blueprints/all_fields.py
- tests/nanocontracts/test_blueprints/bet.py
- tests/nanocontracts/test_get_contract.py
- tests/nanocontracts/test_reentrancy.py
- tests/nanocontracts/test_token_creation.py
- tests/resources/nanocontracts/test_state.py
When merging #1312 we left some changes to be made in a future PR, this is the PR.
- Do not initialize fields implicitly.
- Fail execution of initialize call if there are fields that were not initialized.
- Add more complete tests with more nested container combinations.
> feat(nano): key-mangling continuation
