hathor/cli/grafana/mm.json
hathor/cli/grafana/nodes.json
hathor/cli/grafana_dashboard.py
hathor/util.py

Previous conversations on [MR!412](https://gitlab.com/HathorNetwork/hathor-python/-/merge_requests/412).

chore(grafana): generate dashboard for MM

---

hathor/p2p/node_sync.py

I printed `len(pending)` and it grows until we finish syncing, i.e., it goes from 0 to N, where N is the number of transactions/blocks. It increases memory consumption because we keep all deferrals and their results (i.e., the transactions).  
When we use a `WeakSet`, the deferrals are cleared after they resolve and the memory is released. I checked and `len(pending)` stops growing. In my tests, the download was so fast that it remained around 40 all the time.

fix(sync): Use weakref to prevent keeping deferred results in memory

---

DEBUG.md
hathor/cli/main.py
hathor/indexes.py
hathor/manager.py
hathor/metrics.py
hathor/p2p/node_sync.py
hathor/transaction/base_transaction.py
hathor/transaction/genesis.py
hathor/transaction/storage/binary_storage.py
hathor/transaction/storage/cache_storage.py
hathor/transaction/storage/compact_storage.py
hathor/transaction/storage/memory_storage.py
hathor/transaction/storage/remote_storage.py
hathor/transaction/storage/rocksdb_storage.py
hathor/transaction/storage/transaction_storage.py
tests/p2p/test_split_brain.py
tests/resources/transaction/test_decodetx.py
tests/resources/transaction/test_pushtx.py
tests/resources/transaction/test_tips.py
tests/resources/transaction/test_transaction_confirmation.py
tests/resources/transaction/test_tx.py
tests/resources/wallet/test_nano_contract.py
tests/tx/test_genesis.py
tests/tx/test_scripts.py
tests/tx/test_stratum.py
tests/tx/test_tx_storage.py
tests/wallet/test_wallet.py
tests/websocket/test_websocket.py

Migrated from [MR!385](https://gitlab.com/HathorNetwork/hathor-python/-/merge_requests/385)

feat(storage): Save genesis and its metadata in storage

---

hathor/merged_mining/coordinator.py

Also, thanks to Discord user EuroLine#5553 for the tip on the NiceHash user agent.

feat(merged_mining): detect NiceHash and initial diff from user-agent

---

.editorconfig
README.md
extras/README.md

[Rendered](https://github.com/HathorNetwork/hathor-core/blob/chore/readme-revamp/README.md)

chore: revamp README.md with badges

---

hathor/merged_mining/bitcoin_rpc.py
hathor/merged_mining/coordinator.py
tests/tx/test_merged_mining.py

feat(mergedmining): use longpoll on bitcoin.getblocktemplate

---

hathor/p2p/node_sync.py
hathor/p2p/protocol.py
hathor/p2p/states/ready.py
tests/p2p/test_protocol.py
tests/p2p/test_split_brain.py
tests/p2p/test_sync.py
tests/utils.py

This PR adds nothing new, and thus it's marked as "refactor". The changes stem from the learning and experimentation when doing #94.

refactor: small reorder and improve sync tests

---

hathor/cli/openapi_files/openapi_components.json
hathor/cli/run_node.py
hathor/transaction/base_transaction.py
hathor/transaction/resources/__init__.py
hathor/transaction/resources/create_tx.py
hathor/transaction/resources/validate_address.py
hathor/transaction/scripts.py
hathor/transaction/transaction.py
hathor/wallet/resources/send_tokens.py
tests/resources/base_resource.py
tests/resources/transaction/test_create_tx.py
tests/resources/transaction/test_validate_address.py
tests/tx/test_scripts.py
tests/utils.py

feat(api): new APIs

---

.coveragerc_full
hathor/cli/run_node.py
hathor/cli/top.py
hathor/profiler/resources/cpu_profiler.py
hathor/profiler/site.py

feat(cli): Show hostname, network, version, alias, and CPU meter in top command

---

.github/workflows/docker.yml
Dockerfile.github
Dockerfile.github-pypy
poetry.lock
pyproject.toml

Test run: https://github.com/jansegre/hathor-core/actions/runs/801167847
Some of the generated images:
- `docker run --rm jansegre/hathor-core:experimental-docker-tweaks-python3.8`
- `docker run --rm ghcr.io/jansegre/hathor-core:experimental-docker-tweaks-python3.8`

chore(ci): use GITHUB_TOKEN for ghcr login

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

Draft until we merge all PRs that will be included on this release.

chore: bump version

---

hathor/cli/run_node.py
hathor/daa.py
hathor/manager.py
hathor/p2p/peer_id.py
hathor/p2p/resources/mining_info.py
hathor/simulator/simulator.py
hathor/simulator/tx_generator.py
hathor/transaction/resources/create_tx.py
hathor/util.py
hathor/wallet/resources/nano_contracts/execute.py
hathor/wallet/resources/send_tokens.py
hathor/wallet/resources/sign_tx.py
tests/p2p/test_split_brain.py
tests/resources/base_resource.py
tests/resources/transaction/test_create_tx.py
tests/resources/wallet/test_send_tokens.py
tests/resources/wallet/test_thin_wallet.py
tests/tx/test_blockchain.py
tests/tx/test_cache_storage.py
tests/tx/test_genesis.py
tests/tx/test_tx.py
tests/tx/test_tx_storage.py
tests/unittest.py

Co-authored-by: Marcelo Salhab Brogliato <msbrogli@gmail.com>

refactor(daa): split from HathorManager into separate module

---

hathor/cli/run_node.py
hathor/cli/util.py
hathor/manager.py
hathor/transaction/storage/cache_storage.py
hathor/transaction/storage/rocksdb_storage.py
hathor/transaction/storage/transaction_storage.py
hathor/transaction/transaction_metadata.py
tests/cli/test_shell.py
tests/tx/test_cache_storage.py
tests/utils.py

This branch now depends on #189

feat(sync-v2): automatic database migration for backwards compatibility

---

hathor/manager.py
tests/others/test_init_manager.py
tests/unittest.py

This fixes a regression caused by PR #226.

fix(init): Remove voided tx tips from indexes

---

hathor/api_util.py
hathor/cli/openapi_files/openapi_base.json
hathor/transaction/resources/push_tx.py
hathor/version.py
pyproject.toml

Release v0.42.1

---

.github/workflows/main.yml

Acceptance criteria: have all checks in the test matrix finish running without getting cancelled with a comfortable margin.

chore(ci): increase timeout for tests

---

hathor/cli/run_node.py
hathor/transaction/storage/rocksdb_storage.py

Apparently the RocksDB indexes made a significant impact on the sync performance.
Acceptance criteria:
- RocksDB indexes should be opt-in, and memory indexes should be used by default instead
- tests should primarily still use RocksDB indexes
- the param should be `--x` prefixed to indicate it is somewhat experimental and it will also be removed in the future when RocksDB indexes become the default again

fix(indexes): make RocksDB indexes opt-in

---

hathor/cli/openapi_files/openapi_base.json
hathor/cli/run_node.py
hathor/conf/mainnet.py
hathor/transaction/storage/rocksdb_storage.py
hathor/version.py
pyproject.toml

Release v0.47.1

---

.github/workflows/docker.yml
Dockerfile
hathor/cli/main.py
hathor/cli/openapi_files/openapi_base.json
hathor/cli/quick_test.py
hathor/conf/mainnet.py
hathor/conf/testnet.py
hathor/indexes/manager.py
hathor/indexes/memory_timestamp_index.py
hathor/indexes/rocksdb_timestamp_index.py
hathor/indexes/timestamp_index.py
hathor/transaction/storage/transaction_storage.py
hathor/version.py
poetry.lock
pyproject.toml
slow_tests/test_simulator.py
tests/resources/transaction/test_pushtx.py
tests/simulation/test_simulator.py
tests/tx/test_indexes3.py
tests/unittest.py
tests/utils.py

Merged PRs:
- #390 
- #391 
- #393 
- #395 
- #399 
- #400

Release v0.48.0

---

.github/workflows/main.yml
hathor/cli/openapi_files/openapi_base.json
hathor/conf/mainnet.py
hathor/crypto/util.py
hathor/transaction/storage/cache_storage.py
hathor/transaction/storage/transaction_storage.py
hathor/version.py
poetry.lock
pyproject.toml
tests/tx/test_cache_storage.py
tests/tx/test_tx_storage.py

Release v0.49.1

---

hathor/cli/openapi_files/openapi_base.json
hathor/cli/quick_test.py
hathor/cli/run_node.py
hathor/conf/settings.py
hathor/indexes/manager.py
hathor/indexes/memory_tokens_index.py
hathor/indexes/rocksdb_address_index.py
hathor/manager.py
hathor/p2p/manager.py
hathor/p2p/peer_id.py
hathor/simulator/simulator.py
hathor/storage/__init__.py
hathor/storage/rocksdb_storage.py
hathor/transaction/storage/rocksdb_storage.py
hathor/util.py
hathor/version.py
hathor/wallet/resources/thin_wallet/tokens.py
pyproject.toml
tests/resources/base_resource.py
tests/resources/wallet/test_thin_wallet.py
tests/tx/test_indexes.py
tests/tx/test_tx_storage.py
tests/unittest.py

PRs:
- #448 
- #447 
- #445 
- #449 
- #446 
- #452 
- #434 
- #455 
- #462 
- #458
- #459

Release v0.50.0

---

hathor/cli/openapi_files/openapi_base.json
hathor/manager.py
hathor/p2p/node_sync.py
hathor/transaction/aux_pow.py
hathor/transaction/exceptions.py
hathor/transaction/storage/transaction_storage.py
hathor/version.py
pyproject.toml
tests/tx/test_tx.py

Release v0.50.1

---

hathor/indexes/manager.py
hathor/transaction/storage/cache_storage.py

Garbage collector (gc) was optimized during initialization in #445, and it worked very well when using `TransactionCacheStorage` with cache size up to 10k. But it becomes too slow when cache size is increased to 1M or more because the garbage collector has to collect too many items each execution.
Note that during initialization time, the full node does not benefit from a large cache size since it's traversing the whole database.
1. Use a small cache size during initialization time, then restore the original cache size.

feat(init): Reduce cache size during initialization

---

.github/workflows/main.yml
hathor/manager.py
hathor/metrics.py
hathor/prometheus.py
tests/others/test_metrics.py
tests/tx/test_prometheus.py

design: https://github.com/HathorNetwork/ops-tools/issues/435
- We want to be able to have a metric of network bandwith usage for each peer connection in the fullnodes.
- Some other metrics we were already collection will also be sent to Prometheus

feat: monitor network usage segmented by peer

---

hathor/p2p/downloader.py
hathor/p2p/node_sync.py
tests/p2p/test_sync.py

fix(sync): downloader could wrongfully re-order pending transactions

---

hathor/cli/run_node.py
hathor/event/__init__.py
hathor/event/base_event.py
hathor/event/storage/__init__.py
hathor/event/storage/event_storage.py
hathor/event/storage/memory_storage.py
hathor/event/storage/rocksdb_storage.py
hathor/manager.py
hathor/pubsub.py
tests/event/test_event_storage.py
tests/utils.py

Relevant design is [here](https://github.com/HathorNetwork/hathor-core/issues/405).
Implement a persistence layer for events, so it can be retrieved by the event management layer.

feat: add storage mechanism for events

---

hathor/event/__init__.py
hathor/event/base_event.py
hathor/event/event_manager.py
hathor/event/storage/event_storage.py
hathor/event/storage/memory_storage.py
hathor/event/storage/rocksdb_storage.py
hathor/manager.py
tests/event/test_event_manager.py
tests/event/test_event_storage.py
tests/unittest.py
tests/utils.py

Relevant design is [here](https://github.com/HathorNetwork/hathor-core/issues/405).

feat(events): add management layer

---

hathor/transaction/storage/memory_storage.py

The previous PR (#509) was merged with failing tests (that were only noticed post-merge). This PR fixes those.

fix(tests): simple regression from #509 that ended up being merged

---

hathor/builder.py
hathor/cli/run_node.py
hathor/manager.py

- remove unused `--x-retain-events` flag and related code.

feat(remove-retain-events-flag): remove --retain-events flag

---

hathor/builder/builder.py
hathor/builder/cli_builder.py
hathor/manager.py
hathor/simulator/simulator.py
tests/unittest.py

- Refactor `Simulator` to use `Builder`
- Changes to `Builder`
- Add `full_verification` setting
- Add `soft_voided_tx_ids` setting
- Add `set_enable_sync_v1` and `set_enable_sync_v2` helper methods
- Add `full_verification` argument to `HathorManager.__init__()`
- Update `CliBuilder` to use it
- Update `TestCase` to use it

refactor: use new Builder class on Simulator

---

hathor/wallet/base_wallet.py

1) Remove indentation for readability without changing the behavior.

refactor(wallet): Reduce indentations to increase readability

---

hathor/event/model/event_data.py
tests/event/test_event_reorg.py
tests/utils.py

- Fix model bugs on `EventData`
- Move `zip_chunkify()` function to `tests/utils`

fix: EventData model

---

hathor/cli/top.py
hathor/cli/tx_generator.py
hathor/client.py
hathor/event/storage/memory_storage.py
hathor/metrics.py
hathor/transaction/resources/transaction_confirmation.py
hathor/transaction/storage/transaction_storage.py
hathor/wallet/resources/unlock.py
hathor/websocket/factory.py
hathor/websocket/protocol.py
tests/tx/test_indexes.py

1. Fix all warnings messages that showed up after a mypy upgrade.

chore: Fix mypy warnings

---

hathor/p2p/node_sync.py

- Improve exception message to prevent overreaction

chore: improve exception message

---

hathor/util.py

We faced some issues running full nodes with memory indexes. The initialization process was getting stuck and processing one transaction every 30 seconds. After a profiling, we found out that CPU was being fully consumed by the gc because we were manually controlling it.
1) Remove the manual control of the garbage collector.
2) Reduce the loglevel from `warn` to `debug` for slow transactions.

fix(init): gc consuming high CPU for a long time

---

hathor/manager.py

1. Change `HathorManager.on_new_tx()` to accept only fully validated transactions.
2. Add `HathorManager.log_new_object()` to log new vertices.

refactor: Change HathorManager.on_new_tx() to accept only fully validated transactions

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

New release.
- Bump version on all files.

chore: bump version to v0.56.0

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

Prepare for new release.
- Bump version to 0.57.0 since new features will be included in the next release.

chore: bump version to v0.57.0

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

A release is near.
- bump to v0.58.0 because we have new features to release

chore: bump version to v0.58.0

---

hathor/conf/testnet.py
hathor/conf/testnet.yml
hathor/transaction/storage/migrations/remove_first_nop_features.py
hathor/transaction/storage/transaction_storage.py

Release-candidate v0.58.0-rc.4

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

A release is approaching.
- Bump version to v0.59.0

chore: bump version to v0.59.0

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

New release soon.
- Bump version to v0.60.0

chore: bump version to v0.60.0

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

Bump for fix release.
- Bump version from 0.60.0 to 0.60.1

chore: bump version to v0.60.1

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

Prepare for release.
- Bump version to v0.61.0

chore: bump version to v0.61.0

---

hathor/builder/builder.py
hathor/builder/cli_builder.py
hathor/cli/db_import.py
hathor/cli/generate_genesis.py
hathor/cli/load_from_logs.py
hathor/cli/side_dag.py
hathor/cli/util.py
hathor/conf/settings.py
hathor/consensus/consensus_settings.py
hathor/manager.py
hathor/mining/ws.py
hathor/p2p/sync_v1/agent.py
hathor/p2p/sync_v1/factory.py
hathor/p2p/sync_v2/agent.py
hathor/p2p/sync_v2/factory.py
hathor/transaction/base_transaction.py
hathor/transaction/genesis.py
hathor/transaction/resources/decode_tx.py
hathor/transaction/resources/mining.py
hathor/transaction/resources/push_tx.py
hathor/transaction/resources/transaction.py
hathor/transaction/storage/rocksdb_storage.py
hathor/transaction/vertex_parser.py
hathor/wallet/resources/thin_wallet/address_history.py
hathor/wallet/resources/thin_wallet/send_tokens.py
tests/others/test_hathor_settings.py
tests/p2p/test_sync.py
tests/tx/test_indexes.py

Depends on https://github.com/HathorNetwork/hathor-core/pull/1085
This PRs contains multiple small and unrelated improvements that were relevant in other recent PRs.
- Refactor `generate_genesis` CLI command so it doesn't need a config file.
- Add ability to add static log information to loggers and use it in the `side_dag` CLI.
- Refactor `tx_or_block_from_bytes()` and `NodeBlockSync` to use injected settings.
- Implement `GENESIS_TOKENS` validation on `HathorSettings`.
- Improve logging and responses from `/transaction` and `/thin_wallet/address_history` APIs.

refactor: miscellaneous small improvements

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

New release.
- Bump version to v0.62.0

chore: bump version to v0.62.0

---

hathor/indexes/manager.py

Release-candidate v0.62.0-rc.2

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

Prepare for minor release.
- Bump version from `v0.63.0` to `v0.63.1`

chore: bump version to v0.63.1

---

poetry.lock
pyproject.toml

chore: update hathorlib to v0.8.1

---

poetry.lock
pyproject.toml

- Update hathorlib to `v0.9.0`.

chore: update hathorlib to v0.9.0

---

poetry.lock
pyproject.toml

chore: update hathorlib to v0.9.1

---

poetry.lock
pyproject.toml

- Update hathorlib to v0.10.0.

chore: update hathorlib to v0.10.0

---

hathor/nanocontracts/nc_types/__init__.py
hathor/nanocontracts/nc_types/address_nc_type.py
hathor/nanocontracts/nc_types/bool_nc_type.py
hathor/nanocontracts/nc_types/bytes_nc_type.py
hathor/nanocontracts/nc_types/collection_nc_type.py
hathor/nanocontracts/nc_types/dataclass_nc_type.py
hathor/nanocontracts/nc_types/map_nc_type.py
hathor/nanocontracts/nc_types/namedtuple_nc_type.py
hathor/nanocontracts/nc_types/nc_type.py
hathor/nanocontracts/nc_types/null_nc_type.py
hathor/nanocontracts/nc_types/optional_nc_type.py
hathor/nanocontracts/nc_types/sized_int_nc_type.py
hathor/nanocontracts/nc_types/str_nc_type.py
hathor/nanocontracts/nc_types/tuple_nc_type.py
hathor/nanocontracts/nc_types/utils.py
hathor/nanocontracts/nc_types/varint_nc_type.py

Implement the `nc_types` module.
- Implement the `nc_types` module.
- Signed data support is left out.

feat(nano): implement nc_types module [part 3]

---

hathor/conf/settings.py
hathor/nanocontracts/api_arguments_parser.py
hathor/nanocontracts/balance_rules.py
hathor/nanocontracts/blueprints/__init__.py
hathor/nanocontracts/catalog.py
hathor/nanocontracts/custom_builtins.py
hathor/nanocontracts/metered_exec.py
hathor/nanocontracts/method.py
hathor/nanocontracts/nc_exec_logs.py
hathor/nanocontracts/on_chain_blueprint.py
hathor/nanocontracts/rng.py
hathor/nanocontracts/runner/__init__.py
hathor/nanocontracts/runner/types.py
hathor/nanocontracts/sorter/random_sorter.py
hathor/nanocontracts/sorter/timestamp_sorter.py
hathor/nanocontracts/sorter/types.py
hathor/nanocontracts/types.py
hathor/nanocontracts/utils.py
hathor/transaction/base_transaction.py
hathor/transaction/block.py
hathor/transaction/exceptions.py
hathor/transaction/nc_execution_state.py
hathor/transaction/transaction.py
hathor/transaction/types.py
hathor/verification/nano_header_verifier.py
hathor/verification/on_chain_blueprint_verifier.py
hathor/verification/verification_service.py
hathor/verification/vertex_verifiers.py
tests/nanocontracts/test_blueprints/swap_demo.py

Implement multiple other fundamental nano structures. This is the first PR in the series of nano merges that _updates_ some lines (instead of just _adding_ new lines).
- Implement multiple other fundamental nano structures.

feat(nano): implement more fundamental structures [part 6]

---

poetry.lock
pyproject.toml

- Update hathorlib to v0.11.0.

chore: update hathorlib to v0.11.0

---

hathor/cli/openapi_files/openapi_base.json
hathor/version.py
pyproject.toml

Prepare for a release.
- Bump version 0.63.1 -> 0.64.0

chore: bump version to v0.64.0

---

hathor/nanocontracts/nc_types/str_nc_type.py

What was the motivation for the changes in this PR?
- Include here all things that this PR should solve

chore: Fix typo in StrNCType

---

hathor/cli/main.py
hathor/cli/nc_dump.py
hathor/nanocontracts/fields/container.py
hathor/nanocontracts/runner/types.py

- #1423
- #1422
- #1420
- #1426

Release-candidate v0.66.0-rc.2
